CREATE TABLE IF NOT EXISTS `bireportbusinesssignal` (
  `id` VARCHAR(191) NOT NULL,
  `workspaceId` VARCHAR(191) NOT NULL,
  `sourceRunId` VARCHAR(191) NOT NULL,
  `skillKey` VARCHAR(191) NOT NULL,
  `signalType` VARCHAR(191) NOT NULL,
  `signalKey` VARCHAR(191) NOT NULL,
  `title` VARCHAR(191) NOT NULL,
  `summary` LONGTEXT NOT NULL,
  `severity` ENUM('CLEAR','WATCH','WARN','ALERT','CRITICAL') NOT NULL,
  `continuityStatus` VARCHAR(191) NULL,
  `dimensionsJson` LONGTEXT NULL,
  `metricsJson` LONGTEXT NULL,
  `evidenceJson` LONGTEXT NULL,
  `recommendedActionsJson` LONGTEXT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'open',
  `ownerUserId` VARCHAR(191) NULL,
  `ownerUserName` VARCHAR(191) NULL,
  `ownerUserEmail` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `bireportbusinesssignal_workspace_skill_status_created_idx` (`workspaceId`, `skillKey`, `status`, `createdAt`),
  KEY `bireportbusinesssignal_workspace_signaltype_severity_created_idx` (`workspaceId`, `signalType`, `severity`, `createdAt`),
  KEY `bireportbusinesssignal_sourcerunid_idx` (`sourceRunId`),
  KEY `bireportbusinesssignal_owner_status_created_idx` (`ownerUserId`, `status`, `createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bireportsignalnotification` (
  `id` VARCHAR(191) NOT NULL,
  `workspaceId` VARCHAR(191) NOT NULL,
  `signalId` VARCHAR(191) NOT NULL,
  `targetUserId` VARCHAR(191) NULL,
  `channel` VARCHAR(191) NOT NULL,
  `targetKey` VARCHAR(191) NOT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'pending',
  `providerMessageId` VARCHAR(191) NULL,
  `errorMessage` LONGTEXT NULL,
  `sentAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `bireportsignalnotification_workspace_status_created_idx` (`workspaceId`, `status`, `createdAt`),
  KEY `bireportsignalnotification_signal_channel_created_idx` (`signalId`, `channel`, `createdAt`),
  KEY `bireportsignalnotification_target_status_created_idx` (`targetUserId`, `status`, `createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bireportbusinesshandoffdecision` (
  `id` VARCHAR(191) NOT NULL,
  `workspaceId` VARCHAR(191) NOT NULL,
  `signalId` VARCHAR(191) NOT NULL,
  `targetType` VARCHAR(191) NOT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'open',
  `reviewedByUserId` VARCHAR(191) NULL,
  `reviewComment` LONGTEXT NULL,
  `reviewedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `bireportbusinesshandoffdecision_workspace_status_created_idx` (`workspaceId`, `status`, `createdAt`),
  KEY `bireportbusinesshandoffdecision_signal_target_status_idx` (`signalId`, `targetType`, `status`),
  KEY `bireportbusinesshandoffdecision_reviewer_status_created_idx` (`reviewedByUserId`, `status`, `createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bireporthandoffexecutionlog` (
  `id` VARCHAR(191) NOT NULL,
  `workspaceId` VARCHAR(191) NOT NULL,
  `signalId` VARCHAR(191) NOT NULL,
  `decisionId` VARCHAR(191) NOT NULL,
  `actionItemId` VARCHAR(191) NULL,
  `approvalTaskId` VARCHAR(191) NULL,
  `stage` VARCHAR(191) NOT NULL,
  `authorUserId` VARCHAR(191) NOT NULL,
  `summary` LONGTEXT NOT NULL,
  `detailsJson` LONGTEXT NULL,
  `isEffective` BOOLEAN NULL,
  `followUpNeeded` BOOLEAN NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `bireporthandoffexecutionlog_workspace_signal_stage_created_idx` (`workspaceId`, `signalId`, `stage`, `createdAt`),
  KEY `bireporthandoffexecutionlog_decision_stage_created_idx` (`decisionId`, `stage`, `createdAt`),
  KEY `bireporthandoffexecutionlog_action_stage_created_idx` (`actionItemId`, `stage`, `createdAt`),
  KEY `bireporthandoffexecutionlog_approval_stage_created_idx` (`approvalTaskId`, `stage`, `createdAt`),
  KEY `bireporthandoffexecutionlog_author_stage_created_idx` (`authorUserId`, `stage`, `createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
