-- Member MCP P1b: additive asynchronous prompt-response intake; relationMode=prisma.
CREATE TABLE `MemberPromptResponseInbox` (
 `id` VARCHAR(191) NOT NULL,
 `workspaceId` VARCHAR(191) NOT NULL,
 `connectionId` VARCHAR(191) NOT NULL,
 `memberRef` VARCHAR(191) NOT NULL,
 `deviceRegistrationRef` VARCHAR(191) NOT NULL,
 `clientId` VARCHAR(32) NOT NULL,
 `promptRef` VARCHAR(191) NOT NULL,
 `promptVersion` INTEGER NOT NULL,
 `kind` VARCHAR(32) NOT NULL,
 `payloadJson` LONGTEXT NOT NULL,
 `payloadHash` VARCHAR(80) NOT NULL,
 `memberChallengeRef` VARCHAR(191) NOT NULL,
 `status` VARCHAR(16) NOT NULL,
 `version` INTEGER NOT NULL DEFAULT 0,
 `attempts` INTEGER NOT NULL DEFAULT 0,
 `needsHuman` BOOLEAN NOT NULL DEFAULT false,
 `lastErrorCode` VARCHAR(64) NULL,
 `lastErrorDetail` VARCHAR(500) NULL,
 `responseReceiptRef` VARCHAR(191) NULL,
 `signalReceiptRef` VARCHAR(191) NULL,
 `candidateBundleRef` VARCHAR(191) NULL,
 `candidateCode` VARCHAR(64) NULL,
 `claimToken` VARCHAR(64) NULL,
 `claimedAt` DATETIME(3) NULL,
 `receivedAt` DATETIME(3) NOT NULL,
 `processedAt` DATETIME(3) NULL,
 `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 `updatedAt` DATETIME(3) NOT NULL,
 UNIQUE INDEX `MPRInbox_ws_challenge_key` (`workspaceId`, `memberChallengeRef`),
 INDEX `MPRInbox_status_received_idx` (`status`, `receivedAt`),
 INDEX `MPRInbox_ws_member_idx` (`workspaceId`, `memberRef`),
 PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
