-- AlterTable
ALTER TABLE `ApprovalTask` ADD COLUMN `rejectionReasonCode` ENUM('DIAGNOSIS_ERROR', 'BOUNDARY_ERROR', 'OWNER_DISAGREEMENT', 'EVIDENCE_MISSING', 'EXECUTION_UNFIT', 'OTHER') NULL;

-- AlterTable
ALTER TABLE `RecommendationFeedback` ADD COLUMN `rejectionReasonCode` ENUM('DIAGNOSIS_ERROR', 'BOUNDARY_ERROR', 'OWNER_DISAGREEMENT', 'EVIDENCE_MISSING', 'EXECUTION_UNFIT', 'OTHER') NULL;
