USE `helm2026`;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `contacttomeeting`;
DROP TABLE IF EXISTS `_contacttomeeting`;
RENAME TABLE `contacttomeeting__new` TO `contacttomeeting`;
CREATE OR REPLACE VIEW `_contacttomeeting` AS SELECT `a` AS `A`, `b` AS `B` FROM `contacttomeeting`;
DROP TABLE IF EXISTS `contacttoopportunity`;
DROP TABLE IF EXISTS `_contacttoopportunity`;
RENAME TABLE `contacttoopportunity__new` TO `contacttoopportunity`;
CREATE OR REPLACE VIEW `_contacttoopportunity` AS SELECT `a` AS `A`, `b` AS `B` FROM `contacttoopportunity`;
DROP TABLE IF EXISTS `action_item`;
DROP TABLE IF EXISTS `actionitem`;
RENAME TABLE `action_item__new` TO `action_item`;
CREATE OR REPLACE VIEW `actionitem` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `contact_id` AS `contactId`, `owner_id` AS `ownerId`, `action_type` AS `actionType`, `title` AS `title`, `description` AS `description`, `ai_reason` AS `aiReason`, `draft_content` AS `draftContent`, `metadata` AS `metadata`, `source_type` AS `sourceType`, `source_id` AS `sourceId`, `risk_level` AS `riskLevel`, `suggested_at` AS `suggestedAt`, `suggested_execution_at` AS `suggestedExecutionAt`, `due_date` AS `dueDate`, `execution_mode` AS `executionMode`, `requires_approval` AS `requiresApproval`, `status` AS `status`, `execution_status` AS `executionStatus`, `status_reason` AS `statusReason`, `policy_name` AS `policyName`, `policy_snapshot` AS `policySnapshot`, `recommendation_log_id` AS `recommendationLogId`, `executed_at` AS `executedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `action_item`;
DROP TABLE IF EXISTS `approval_request`;
DROP TABLE IF EXISTS `approvalrequest`;
RENAME TABLE `approval_request__new` TO `approval_request`;
CREATE OR REPLACE VIEW `approvalrequest` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_event_id` AS `runtimeEventId`, `worker_run_id` AS `workerRunId`, `artifact_bundle_id` AS `artifactBundleId`, `requested_action` AS `requestedAction`, `approval_tier` AS `approvalTier`, `status` AS `status`, `requested_by` AS `requestedBy`, `requested_reason` AS `requestedReason`, `resolved_by_user_id` AS `resolvedByUserId`, `resolution_notes` AS `resolutionNotes`, `resolved_at` AS `resolvedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `approval_request`;
DROP TABLE IF EXISTS `approval_task`;
DROP TABLE IF EXISTS `approvaltask`;
RENAME TABLE `approval_task__new` TO `approval_task`;
CREATE OR REPLACE VIEW `approvaltask` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `action_item_id` AS `actionItemId`, `approver_id` AS `approverId`, `reviewed_by_id` AS `reviewedById`, `status` AS `status`, `channel` AS `channel`, `is_high_risk` AS `isHighRisk`, `auto_execute` AS `autoExecute`, `context_snapshot` AS `contextSnapshot`, `reasoning` AS `reasoning`, `editable_content` AS `editableContent`, `result_preview` AS `resultPreview`, `decision_reason` AS `decisionReason`, `reviewed_at` AS `reviewedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `approval_task`;
DROP TABLE IF EXISTS `artifact_bundle`;
DROP TABLE IF EXISTS `artifactbundle`;
RENAME TABLE `artifact_bundle__new` TO `artifact_bundle`;
CREATE OR REPLACE VIEW `artifactbundle` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_event_id` AS `runtimeEventId`, `worker_run_id` AS `workerRunId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `artifact_type` AS `artifactType`, `title` AS `title`, `status` AS `status`, `approval_tier` AS `approvalTier`, `system_of_record_write` AS `systemOfRecordWrite`, `summary` AS `summary`, `artifacts_json` AS `artifactsJson`, `evidence_refs` AS `evidenceRefs`, `source_provenance` AS `sourceProvenance`, `confidence` AS `confidence`, `open_questions` AS `openQuestions`, `review_posture` AS `reviewPosture`, `reviewed_at` AS `reviewedAt`, `confirmed_at` AS `confirmedAt`, `consumed_at` AS `consumedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `artifact_bundle`;
DROP TABLE IF EXISTS `artifact_review`;
DROP TABLE IF EXISTS `artifactreview`;
RENAME TABLE `artifact_review__new` TO `artifact_review`;
CREATE OR REPLACE VIEW `artifactreview` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_event_id` AS `runtimeEventId`, `artifact_bundle_id` AS `artifactBundleId`, `approval_request_id` AS `approvalRequestId`, `status` AS `status`, `reviewed_by_user_id` AS `reviewedByUserId`, `review_notes` AS `reviewNotes`, `edited_payload` AS `editedPayload`, `decision_summary` AS `decisionSummary`, `reviewed_at` AS `reviewedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `artifact_review`;
DROP TABLE IF EXISTS `artifact_version`;
DROP TABLE IF EXISTS `artifactversion`;
RENAME TABLE `artifact_version__new` TO `artifact_version`;
CREATE OR REPLACE VIEW `artifactversion` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `artifact_bundle_id` AS `artifactBundleId`, `version_key` AS `versionKey`, `version_number` AS `versionNumber`, `artifact_type` AS `artifactType`, `review_posture` AS `reviewPosture`, `snapshot_json` AS `snapshotJson`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `artifact_version`;
DROP TABLE IF EXISTS `audit_log`;
DROP TABLE IF EXISTS `auditlog`;
RENAME TABLE `audit_log__new` TO `audit_log`;
CREATE OR REPLACE VIEW `auditlog` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `actor` AS `actor`, `actor_type` AS `actorType`, `action_type` AS `actionType`, `target_type` AS `targetType`, `target_id` AS `targetId`, `summary` AS `summary`, `payload` AS `payload`, `source_page` AS `sourcePage`, `related_object_type` AS `relatedObjectType`, `related_object_id` AS `relatedObjectId`, `create_time` AS `createdAt` FROM `audit_log`;
DROP TABLE IF EXISTS `auth_enrollment`;
DROP TABLE IF EXISTS `authenrollment`;
RENAME TABLE `auth_enrollment__new` TO `auth_enrollment`;
CREATE OR REPLACE VIEW `authenrollment` AS SELECT `legacy_id` AS `id`, `name` AS `name`, `email` AS `email`, `phone` AS `phone`, `organization_name` AS `organizationName`, `locale` AS `locale`, `password_hash` AS `passwordHash`, `email_verified_at` AS `emailVerifiedAt`, `phone_verified_at` AS `phoneVerifiedAt`, `expires_at` AS `expiresAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `auth_enrollment`;
DROP TABLE IF EXISTS `auth_session`;
DROP TABLE IF EXISTS `authsession`;
RENAME TABLE `auth_session__new` TO `auth_session`;
CREATE OR REPLACE VIEW `authsession` AS SELECT `legacy_id` AS `id`, `user_id` AS `userId`, `active_workspace_id` AS `activeWorkspaceId`, `session_key_hash` AS `sessionKeyHash`, `source_page` AS `sourcePage`, `provider_type` AS `providerType`, `user_agent` AS `userAgent`, `ip_address` AS `ipAddress`, `last_seen_at` AS `lastSeenAt`, `last_workspace_switch_at` AS `lastWorkspaceSwitchAt`, `expires_at` AS `expiresAt`, `revoked_at` AS `revokedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `auth_session`;
DROP TABLE IF EXISTS `auth_verification_code`;
DROP TABLE IF EXISTS `authverificationcode`;
RENAME TABLE `auth_verification_code__new` TO `auth_verification_code`;
CREATE OR REPLACE VIEW `authverificationcode` AS SELECT `legacy_id` AS `id`, `purpose` AS `purpose`, `channel` AS `channel`, `target` AS `target`, `code_hash` AS `codeHash`, `expires_at` AS `expiresAt`, `consumed_at` AS `consumedAt`, `attempts` AS `attempts`, `create_time` AS `createdAt`, `enrollment_id` AS `enrollmentId`, `user_id` AS `userId` FROM `auth_verification_code`;
DROP TABLE IF EXISTS `beneficiary_payout_profile`;
DROP TABLE IF EXISTS `beneficiarypayoutprofile`;
RENAME TABLE `beneficiary_payout_profile__new` TO `beneficiary_payout_profile`;
CREATE OR REPLACE VIEW `beneficiarypayoutprofile` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `beneficiary_type` AS `beneficiaryType`, `beneficiary_reference` AS `beneficiaryReference`, `display_name` AS `displayName`, `legal_name` AS `legalName`, `contact` AS `contact`, `payout_method_label` AS `payoutMethodLabel`, `payout_details_reference` AS `payoutDetailsReference`, `invoice_required` AS `invoiceRequired`, `status` AS `status`, `notes` AS `notes`, `worker_publisher_profile_id` AS `workerPublisherProfileId`, `sales_referral_id` AS `salesReferralId`, `custom_engagement_id` AS `customEngagementId`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `beneficiary_payout_profile`;
DROP TABLE IF EXISTS `billing_account`;
DROP TABLE IF EXISTS `billingaccount`;
RENAME TABLE `billing_account__new` TO `billing_account`;
CREATE OR REPLACE VIEW `billingaccount` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `current_plan` AS `currentPlan`, `currency` AS `currency`, `billing_status` AS `billingStatus`, `payment_provider` AS `paymentProvider`, `payment_customer_id` AS `paymentCustomerId`, `payment_subscription_id` AS `paymentSubscriptionId`, `payment_subscription_status` AS `paymentSubscriptionStatus`, `payment_checkout_session_id` AS `paymentCheckoutSessionId`, `payment_checkout_completed_at` AS `paymentCheckoutCompletedAt`, `billing_period_starts_at` AS `billingPeriodStartsAt`, `billing_period_ends_at` AS `billingPeriodEndsAt`, `last_payment_sync_at` AS `lastPaymentSyncAt`, `base_fee_cents` AS `baseFeeCents`, `active_seat_price_cents` AS `activeSeatPriceCents`, `included_admin_seats` AS `includedAdminSeats`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `billing_account`;
DROP TABLE IF EXISTS `bi_report_delivery`;
DROP TABLE IF EXISTS `bireportdelivery`;
RENAME TABLE `bi_report_delivery__new` TO `bi_report_delivery`;
CREATE OR REPLACE VIEW `bireportdelivery` AS SELECT `legacy_id` AS `id`, `run_id` AS `runId`, `workspace_id` AS `workspaceId`, `channel` AS `channel`, `target_type` AS `targetType`, `target_key` AS `targetKey`, `status` AS `status`, `provider_message_id` AS `providerMessageId`, `request_body` AS `requestBody`, `response_body` AS `responseBody`, `sent_at` AS `sentAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt`, `extension_key` AS `extensionKey` FROM `bi_report_delivery`;
DROP TABLE IF EXISTS `bi_report_run`;
DROP TABLE IF EXISTS `bireportrun`;
RENAME TABLE `bi_report_run__new` TO `bi_report_run`;
CREATE OR REPLACE VIEW `bireportrun` AS SELECT `legacy_id` AS `id`, `subscription_id` AS `subscriptionId`, `workspace_id` AS `workspaceId`, `scheduled_for` AS `scheduledFor`, `dedupe_key` AS `dedupeKey`, `status` AS `status`, `severity` AS `severity`, `row_count` AS `rowCount`, `query_summary_json` AS `querySummaryJson`, `metrics_json` AS `metricsJson`, `criteria_result_json` AS `criteriaResultJson`, `deterministic_summary_json` AS `deterministicSummaryJson`, `analysis_json` AS `analysisJson`, `llm_meta_json` AS `llmMetaJson`, `error_summary` AS `errorSummary`, `started_at` AS `startedAt`, `finished_at` AS `finishedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt`, `extension_key` AS `extensionKey` FROM `bi_report_run`;
DROP TABLE IF EXISTS `bi_report_subscription`;
DROP TABLE IF EXISTS `bireportsubscription`;
RENAME TABLE `bi_report_subscription__new` TO `bi_report_subscription`;
CREATE OR REPLACE VIEW `bireportsubscription` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `created_by_user_id` AS `createdByUserId`, `name` AS `name`, `skill_key` AS `skillKey`, `skill_version` AS `skillVersion`, `enabled` AS `enabled`, `schedule_cron` AS `scheduleCron`, `timezone` AS `timezone`, `sql_params_json` AS `sqlParamsJson`, `analysis_overrides_json` AS `analysisOverridesJson`, `delivery_targets_json` AS `deliveryTargetsJson`, `silence_policy_json` AS `silencePolicyJson`, `dedupe_window_minutes` AS `dedupeWindowMinutes`, `last_planned_at` AS `lastPlannedAt`, `last_succeeded_at` AS `lastSucceededAt`, `last_failed_at` AS `lastFailedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt`, `extension_key` AS `extensionKey` FROM `bi_report_subscription`;
DROP TABLE IF EXISTS `n_blocker`;
DROP TABLE IF EXISTS `blocker`;
RENAME TABLE `n_blocker__new` TO `n_blocker`;
CREATE OR REPLACE VIEW `blocker` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `title` AS `title`, `blocker_type` AS `blockerType`, `blocker_text` AS `blockerText`, `severity` AS `severity`, `source_type` AS `sourceType`, `source_id` AS `sourceId`, `related_contact_id` AS `relatedContactId`, `related_company_id` AS `relatedCompanyId`, `related_opportunity_id` AS `relatedOpportunityId`, `related_meeting_id` AS `relatedMeetingId`, `status` AS `status`, `resolution_note` AS `resolutionNote`, `first_seen_at` AS `firstSeenAt`, `resolved_at` AS `resolvedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `n_blocker`;
DROP TABLE IF EXISTS `briefing_snapshot`;
DROP TABLE IF EXISTS `briefingsnapshot`;
RENAME TABLE `briefing_snapshot__new` TO `briefing_snapshot`;
CREATE OR REPLACE VIEW `briefingsnapshot` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `object_type` AS `objectType`, `object_id` AS `objectId`, `snapshot_type` AS `snapshotType`, `content` AS `content`, `source_fact_ids` AS `sourceFactIds`, `source_commitment_ids` AS `sourceCommitmentIds`, `source_blocker_ids` AS `sourceBlockerIds`, `generated_at` AS `generatedAt`, `expires_at` AS `expiresAt`, `version` AS `version` FROM `briefing_snapshot`;
DROP TABLE IF EXISTS `budget_rule`;
DROP TABLE IF EXISTS `budgetrule`;
RENAME TABLE `budget_rule__new` TO `budget_rule`;
CREATE OR REPLACE VIEW `budgetrule` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `name` AS `name`, `scope` AS `scope`, `monthly_limit` AS `monthlyLimit`, `spent` AS `spent`, `warning_threshold` AS `warningThreshold`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `budget_rule`;
DROP TABLE IF EXISTS `capability_catalog_entry`;
DROP TABLE IF EXISTS `capabilitycatalogentry`;
RENAME TABLE `capability_catalog_entry__new` TO `capability_catalog_entry`;
CREATE OR REPLACE VIEW `capabilitycatalogentry` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `capability_key` AS `capabilityKey`, `name` AS `name`, `stage` AS `stage`, `description` AS `description`, `load_policy` AS `loadPolicy`, `review_required` AS `reviewRequired`, `boundary_note` AS `boundaryNote`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `capability_catalog_entry`;
DROP TABLE IF EXISTS `capture_session`;
DROP TABLE IF EXISTS `capturesession`;
RENAME TABLE `capture_session__new` TO `capture_session`;
CREATE OR REPLACE VIEW `capturesession` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `linked_meeting_id` AS `linkedMeetingId`, `title` AS `title`, `status` AS `status`, `source_type` AS `sourceType`, `source_id` AS `sourceId`, `object_type` AS `objectType`, `object_id` AS `objectId`, `started_at` AS `startedAt`, `ended_at` AS `endedAt`, `duration_seconds` AS `durationSeconds`, `transcript_status` AS `transcriptStatus`, `processing_status` AS `processingStatus`, `error_message` AS `errorMessage`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `capture_session`;
DROP TABLE IF EXISTS `n_commitment`;
DROP TABLE IF EXISTS `commitment`;
RENAME TABLE `n_commitment__new` TO `n_commitment`;
CREATE OR REPLACE VIEW `commitment` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `title` AS `title`, `commitment_text` AS `commitmentText`, `source_type` AS `sourceType`, `source_id` AS `sourceId`, `related_contact_id` AS `relatedContactId`, `related_company_id` AS `relatedCompanyId`, `related_opportunity_id` AS `relatedOpportunityId`, `related_meeting_id` AS `relatedMeetingId`, `owner_user_id` AS `ownerUserId`, `due_date` AS `dueDate`, `status` AS `status`, `priority` AS `priority`, `overdue_flag` AS `overdueFlag`, `fulfilled_at` AS `fulfilledAt`, `confidence` AS `confidence`, `status_note` AS `statusNote`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `n_commitment`;
DROP TABLE IF EXISTS `n_company`;
DROP TABLE IF EXISTS `company`;
RENAME TABLE `n_company__new` TO `n_company`;
CREATE OR REPLACE VIEW `company` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `name` AS `name`, `industry` AS `industry`, `website` AS `website`, `description` AS `description`, `definition_suggestion_json` AS `definitionSuggestionJson`, `definition_suggested_at` AS `definitionSuggestedAt`, `definition_accepted_json` AS `definitionAcceptedJson`, `definition_accepted_at` AS `definitionAcceptedAt`, `maturity_score` AS `maturityScore`, `cooperation_maturity` AS `cooperationMaturity`, `recommended_path` AS `recommendedPath`, `tags` AS `tags`, `external_source` AS `externalSource`, `external_object_type` AS `externalObjectType`, `external_object_id` AS `externalObjectId`, `external_owner_id` AS `externalOwnerId`, `external_synced_at` AS `externalSyncedAt`, `last_interaction_at` AS `lastInteractionAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `n_company`;
DROP TABLE IF EXISTS `composition_failure`;
DROP TABLE IF EXISTS `compositionfailure`;
RENAME TABLE `composition_failure__new` TO `composition_failure`;
CREATE OR REPLACE VIEW `compositionfailure` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `meeting_id` AS `meetingId`, `problem_space_id` AS `problemSpaceId`, `failure_key` AS `failureKey`, `failure_class` AS `failureClass`, `summary` AS `summary`, `details_json` AS `detailsJson`, `resolved` AS `resolved`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `composition_failure`;
DROP TABLE IF EXISTS `n_connector`;
DROP TABLE IF EXISTS `connector`;
RENAME TABLE `n_connector__new` TO `n_connector`;
CREATE OR REPLACE VIEW `connector` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `provider` AS `provider`, `status` AS `status`, `external_account_email` AS `externalAccountEmail`, `access_token` AS `accessToken`, `refresh_token` AS `refreshToken`, `token_expires_at` AS `tokenExpiresAt`, `imap_host` AS `imapHost`, `imap_port` AS `imapPort`, `imap_secure` AS `imapSecure`, `smtp_host` AS `smtpHost`, `smtp_port` AS `smtpPort`, `smtp_secure` AS `smtpSecure`, `smtp_username` AS `smtpUsername`, `smtp_password` AS `smtpPassword`, `manual_send_enabled` AS `manualSendEnabled`, `last_synced_at` AS `lastSyncedAt`, `last_sync_status` AS `lastSyncStatus`, `last_sync_message` AS `lastSyncMessage`, `metadata` AS `metadata`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `n_connector`;
DROP TABLE IF EXISTS `connector_ingestion_record`;
DROP TABLE IF EXISTS `connectoringestionrecord`;
RENAME TABLE `connector_ingestion_record__new` TO `connector_ingestion_record`;
CREATE OR REPLACE VIEW `connectoringestionrecord` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_event_id` AS `runtimeEventId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `source_type` AS `sourceType`, `source_id` AS `sourceId`, `source_scope` AS `sourceScope`, `trust_level` AS `trustLevel`, `trust_promotion_status` AS `trustPromotionStatus`, `sensitivity` AS `sensitivity`, `normalization_status` AS `normalizationStatus`, `promotion_eligibility` AS `promotionEligibility`, `object_refs` AS `objectRefs`, `evidence_ref` AS `evidenceRef`, `extracted_facts` AS `extractedFacts`, `draft_payload` AS `draftPayload`, `source_summary` AS `sourceSummary`, `boundary_note` AS `boundaryNote`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `connector_ingestion_record`;
DROP TABLE IF EXISTS `consolidation_job`;
DROP TABLE IF EXISTS `consolidationjob`;
RENAME TABLE `consolidation_job__new` TO `consolidation_job`;
CREATE OR REPLACE VIEW `consolidationjob` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `job_key` AS `jobKey`, `job_type` AS `jobType`, `status` AS `status`, `input_summary` AS `inputSummary`, `output_summary` AS `outputSummary`, `review_posture` AS `reviewPosture`, `started_at` AS `startedAt`, `paused_at` AS `pausedAt`, `completed_at` AS `completedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `consolidation_job`;
DROP TABLE IF EXISTS `n_contact`;
DROP TABLE IF EXISTS `contact`;
RENAME TABLE `n_contact__new` TO `n_contact`;
CREATE OR REPLACE VIEW `contact` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `company_id` AS `companyId`, `owner_id` AS `ownerId`, `name` AS `name`, `title` AS `title`, `email` AS `email`, `phone` AS `phone`, `channel` AS `channel`, `tags` AS `tags`, `notes` AS `notes`, `external_source` AS `externalSource`, `external_object_type` AS `externalObjectType`, `external_object_id` AS `externalObjectId`, `external_owner_id` AS `externalOwnerId`, `external_synced_at` AS `externalSyncedAt`, `relationship_stage` AS `relationshipStage`, `relationship_temperature` AS `relationshipTemperature`, `relationship_warmth` AS `relationshipWarmth`, `last_interaction_at` AS `lastInteractionAt`, `archived_at` AS `archivedAt`, `merged_into_id` AS `mergedIntoId`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `n_contact`;
DROP TABLE IF EXISTS `context_edit_event`;
DROP TABLE IF EXISTS `contexteditevent`;
RENAME TABLE `context_edit_event__new` TO `context_edit_event`;
CREATE OR REPLACE VIEW `contexteditevent` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `edit_key` AS `editKey`, `strategy` AS `strategy`, `before_token_count` AS `beforeTokenCount`, `after_token_count` AS `afterTokenCount`, `removed_handles` AS `removedHandles`, `removed_summary` AS `removedSummary`, `boundary_note` AS `boundaryNote`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `context_edit_event`;
DROP TABLE IF EXISTS `conversation_insight`;
DROP TABLE IF EXISTS `conversationinsight`;
RENAME TABLE `conversation_insight__new` TO `conversation_insight`;
CREATE OR REPLACE VIEW `conversationinsight` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `capture_session_id` AS `captureSessionId`, `insight_type` AS `insightType`, `title` AS `title`, `content` AS `content`, `confidence` AS `confidence`, `related_contact_id` AS `relatedContactId`, `related_company_id` AS `relatedCompanyId`, `related_opportunity_id` AS `relatedOpportunityId`, `related_meeting_id` AS `relatedMeetingId`, `source_segment_refs` AS `sourceSegmentRefs`, `create_time` AS `createdAt` FROM `conversation_insight`;
DROP TABLE IF EXISTS `conversation_transcript`;
DROP TABLE IF EXISTS `conversationtranscript`;
RENAME TABLE `conversation_transcript__new` TO `conversation_transcript`;
CREATE OR REPLACE VIEW `conversationtranscript` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `capture_session_id` AS `captureSessionId`, `full_text` AS `fullText`, `segments` AS `segments`, `speaker_separated` AS `speakerSeparated`, `language` AS `language`, `confidence` AS `confidence`, `source_type` AS `sourceType`, `provider` AS `provider`, `model` AS `model`, `create_time` AS `createdAt` FROM `conversation_transcript`;
DROP TABLE IF EXISTS `coordination_metrics_daily`;
DROP TABLE IF EXISTS `coordinationmetricsdaily`;
RENAME TABLE `coordination_metrics_daily__new` TO `coordination_metrics_daily`;
CREATE OR REPLACE VIEW `coordinationmetricsdaily` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `metric_date` AS `metricDate`, `active_sessions` AS `activeSessions`, `action_ready_count` AS `actionReadyCount`, `review_needed_count` AS `reviewNeededCount`, `waiting_on_signal_count` AS `waitingOnSignalCount`, `waiting_on_authority_count` AS `waitingOnAuthorityCount`, `capability_gap_count` AS `capabilityGapCount`, `open_problem_spaces` AS `openProblemSpaces`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `coordination_metrics_daily`;
DROP TABLE IF EXISTS `custom_engagement`;
DROP TABLE IF EXISTS `customengagement`;
RENAME TABLE `custom_engagement__new` TO `custom_engagement`;
CREATE OR REPLACE VIEW `customengagement` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `engagement_key` AS `engagementKey`, `engagement_type` AS `engagementType`, `label` AS `label`, `beneficiary_label` AS `beneficiaryLabel`, `contract_value_cents` AS `contractValueCents`, `currency` AS `currency`, `notes` AS `notes`, `status` AS `status`, `effective_from` AS `effectiveFrom`, `effective_to` AS `effectiveTo`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `custom_engagement`;
DROP TABLE IF EXISTS `daily_usage_snapshot`;
DROP TABLE IF EXISTS `dailyusagesnapshot`;
RENAME TABLE `daily_usage_snapshot__new` TO `daily_usage_snapshot`;
CREATE OR REPLACE VIEW `dailyusagesnapshot` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `date` AS `date`, `login_count` AS `loginCount`, `dashboard_view_count` AS `dashboardViewCount`, `meeting_view_count` AS `meetingViewCount`, `action_items_generated` AS `actionItemsGenerated`, `approvals_submitted` AS `approvalsSubmitted`, `approvals_approved` AS `approvalsApproved`, `approvals_rejected` AS `approvalsRejected`, `opportunity_stage_changes` AS `opportunityStageChanges`, `followup_drafts_generated` AS `followupDraftsGenerated`, `policy_changes` AS `policyChanges`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `daily_usage_snapshot`;
DROP TABLE IF EXISTS `delta_event`;
DROP TABLE IF EXISTS `deltaevent`;
RENAME TABLE `delta_event__new` TO `delta_event`;
CREATE OR REPLACE VIEW `deltaevent` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `actor_type` AS `actorType`, `actor_id` AS `actorId`, `event_type` AS `eventType`, `object_type` AS `objectType`, `object_id` AS `objectId`, `source_type` AS `sourceType`, `source_id` AS `sourceId`, `payload` AS `payload`, `importance` AS `importance`, `create_time` AS `createdAt` FROM `delta_event`;
DROP TABLE IF EXISTS `dri_assignment`;
DROP TABLE IF EXISTS `driassignment`;
RENAME TABLE `dri_assignment__new` TO `dri_assignment`;
CREATE OR REPLACE VIEW `driassignment` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `problem_space_id` AS `problemSpaceId`, `assignment_key` AS `assignmentKey`, `assigned_user_id` AS `assignedUserId`, `assigned_user_name` AS `assignedUserName`, `assigned_by_user_id` AS `assignedByUserId`, `assigned_by_name` AS `assignedByName`, `note` AS `note`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `dri_assignment`;
DROP TABLE IF EXISTS `edge_brief`;
DROP TABLE IF EXISTS `edgebrief`;
RENAME TABLE `edge_brief__new` TO `edge_brief`;
CREATE OR REPLACE VIEW `edgebrief` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `problem_space_id` AS `problemSpaceId`, `brief_key` AS `briefKey`, `audience` AS `audience`, `title` AS `title`, `summary` AS `summary`, `markdown` AS `markdown`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `edge_brief`;
DROP TABLE IF EXISTS `email_message`;
DROP TABLE IF EXISTS `emailmessage`;
RENAME TABLE `email_message__new` TO `email_message`;
CREATE OR REPLACE VIEW `emailmessage` AS SELECT `legacy_id` AS `id`, `thread_id` AS `threadId`, `sender` AS `sender`, `sender_email` AS `senderEmail`, `body` AS `body`, `snippet` AS `snippet`, `source` AS `source`, `external_message_id` AS `externalMessageId`, `is_inbound` AS `isInbound`, `sent_at` AS `sentAt`, `create_time` AS `createdAt` FROM `email_message`;
DROP TABLE IF EXISTS `email_thread`;
DROP TABLE IF EXISTS `emailthread`;
RENAME TABLE `email_thread__new` TO `email_thread`;
CREATE OR REPLACE VIEW `emailthread` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `contact_id` AS `contactId`, `company_id` AS `companyId`, `opportunity_id` AS `opportunityId`, `subject` AS `subject`, `counterpart` AS `counterpart`, `summary` AS `summary`, `participants` AS `participants`, `source` AS `source`, `external_thread_id` AS `externalThreadId`, `status` AS `status`, `waiting_on` AS `waitingOn`, `should_reply` AS `shouldReply`, `modify_time` AS `updatedAt`, `create_time` AS `createdAt` FROM `email_thread`;
DROP TABLE IF EXISTS `event_log`;
DROP TABLE IF EXISTS `eventlog`;
RENAME TABLE `event_log__new` TO `event_log`;
CREATE OR REPLACE VIEW `eventlog` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `event_name` AS `eventName`, `event_category` AS `eventCategory`, `target_type` AS `targetType`, `target_id` AS `targetId`, `metadata` AS `metadata`, `session_id` AS `sessionId`, `source_page` AS `sourcePage`, `create_time` AS `createdAt` FROM `event_log`;
DROP TABLE IF EXISTS `external_memory_record`;
DROP TABLE IF EXISTS `externalmemoryrecord`;
RENAME TABLE `external_memory_record__new` TO `external_memory_record`;
CREATE OR REPLACE VIEW `externalmemoryrecord` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `provider` AS `provider`, `external_id` AS `externalId`, `scope` AS `scope`, `category` AS `category`, `importance` AS `importance`, `occurred_at` AS `occurredAt`, `synced_at` AS `syncedAt`, `raw_metadata` AS `rawMetadata`, `text` AS `text`, `source_file` AS `sourceFile`, `source_line` AS `sourceLine`, `checksum` AS `checksum`, `memory_entry_id` AS `memoryEntryId`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `external_memory_record`;
DROP TABLE IF EXISTS `external_memory_sync_state`;
DROP TABLE IF EXISTS `externalmemorysyncstate`;
RENAME TABLE `external_memory_sync_state__new` TO `external_memory_sync_state`;
CREATE OR REPLACE VIEW `externalmemorysyncstate` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `provider` AS `provider`, `last_synced_at` AS `lastSyncedAt`, `last_cursor` AS `lastCursor`, `last_run_status` AS `lastRunStatus`, `last_error` AS `lastError`, `is_running` AS `isRunning`, `run_started_at` AS `runStartedAt`, `run_finished_at` AS `runFinishedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `external_memory_sync_state`;
DROP TABLE IF EXISTS `handoff_packet`;
DROP TABLE IF EXISTS `handoffpacket`;
RENAME TABLE `handoff_packet__new` TO `handoff_packet`;
CREATE OR REPLACE VIEW `handoffpacket` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `problem_space_id` AS `problemSpaceId`, `packet_key` AS `packetKey`, `from_agent` AS `fromAgent`, `to_agent` AS `toAgent`, `goal` AS `goal`, `constraints_json` AS `constraintsJson`, `trusted_refs` AS `trustedRefs`, `untrusted_refs` AS `untrustedRefs`, `required_outputs` AS `requiredOutputs`, `evidence_refs` AS `evidenceRefs`, `notebook_ref` AS `notebookRef`, `checkpoint_ref` AS `checkpointRef`, `approval_tier` AS `approvalTier`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `handoff_packet`;
DROP TABLE IF EXISTS `human_action_execution`;
DROP TABLE IF EXISTS `humanactionexecution`;
RENAME TABLE `human_action_execution__new` TO `human_action_execution`;
CREATE OR REPLACE VIEW `humanactionexecution` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `source_artifact_bundle_id` AS `sourceArtifactBundleId`, `source_artifact_type` AS `sourceArtifactType`, `source_artifact_title` AS `sourceArtifactTitle`, `source_artifact_summary` AS `sourceArtifactSummary`, `action_type` AS `actionType`, `audience` AS `audience`, `execution_owner_id` AS `executionOwnerId`, `execution_owner_name` AS `executionOwnerName`, `execution_intent` AS `executionIntent`, `execution_boundary` AS `executionBoundary`, `execution_prerequisite` AS `executionPrerequisite`, `execution_dependency` AS `executionDependency`, `execution_risk_level` AS `executionRiskLevel`, `approval_context` AS `approvalContext`, `risk_review_summary` AS `riskReviewSummary`, `acknowledgement_status` AS `acknowledgementStatus`, `status` AS `status`, `execution_proof_type` AS `executionProofType`, `execution_proof_payload` AS `executionProofPayload`, `proof_note` AS `proofNote`, `external_reference` AS `externalReference`, `executed_by_user_id` AS `executedByUserId`, `executed_by_name` AS `executedByName`, `executed_at` AS `executedAt`, `what_was_not_done` AS `whatWasNotDone`, `follow_through_status` AS `followThroughStatus`, `execution_writeback_target` AS `executionWritebackTarget`, `writeback_summary` AS `writebackSummary`, `audit_logged_at` AS `auditLoggedAt`, `checkpoint_written_at` AS `checkpointWrittenAt`, `summary_written_at` AS `summaryWrittenAt`, `evidence_refs` AS `evidenceRefs`, `source_provenance` AS `sourceProvenance`, `boundary_trace` AS `boundaryTrace`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `human_action_execution`;
DROP TABLE IF EXISTS `identity_match`;
DROP TABLE IF EXISTS `identitymatch`;
RENAME TABLE `identity_match__new` TO `identity_match`;
CREATE OR REPLACE VIEW `identitymatch` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `source_id` AS `sourceId`, `import_item_id` AS `importItemId`, `external_type` AS `externalType`, `external_id` AS `externalId`, `internal_object_type` AS `internalObjectType`, `internal_object_id` AS `internalObjectId`, `match_score` AS `matchScore`, `match_reason` AS `matchReason`, `status` AS `status`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `identity_match`;
DROP TABLE IF EXISTS `import_item`;
DROP TABLE IF EXISTS `importitem`;
RENAME TABLE `import_item__new` TO `import_item`;
CREATE OR REPLACE VIEW `importitem` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `import_job_id` AS `importJobId`, `external_type` AS `externalType`, `external_id` AS `externalId`, `mapped_object_type` AS `mappedObjectType`, `mapped_object_id` AS `mappedObjectId`, `match_status` AS `matchStatus`, `conflict_status` AS `conflictStatus`, `payload` AS `payload`, `normalized_payload` AS `normalizedPayload`, `error_message` AS `errorMessage`, `warning_message` AS `warningMessage`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `import_item`;
DROP TABLE IF EXISTS `import_job`;
DROP TABLE IF EXISTS `importjob`;
RENAME TABLE `import_job__new` TO `import_job`;
CREATE OR REPLACE VIEW `importjob` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `source_id` AS `sourceId`, `created_by_user_id` AS `createdByUserId`, `job_type` AS `jobType`, `status` AS `status`, `total_records` AS `totalRecords`, `success_records` AS `successRecords`, `failed_records` AS `failedRecords`, `warning_records` AS `warningRecords`, `started_at` AS `startedAt`, `finished_at` AS `finishedAt`, `error_summary` AS `errorSummary`, `summary_json` AS `summaryJson`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `import_job`;
DROP TABLE IF EXISTS `import_source`;
DROP TABLE IF EXISTS `importsource`;
RENAME TABLE `import_source__new` TO `import_source`;
CREATE OR REPLACE VIEW `importsource` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `source_type` AS `sourceType`, `source_name` AS `sourceName`, `status` AS `status`, `auth_mode` AS `authMode`, `external_account_id` AS `externalAccountId`, `external_account_label` AS `externalAccountLabel`, `access_token` AS `accessToken`, `refresh_token` AS `refreshToken`, `token_expires_at` AS `tokenExpiresAt`, `last_synced_at` AS `lastSyncedAt`, `config_json` AS `configJson`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `import_source`;
DROP TABLE IF EXISTS `initiative_run`;
DROP TABLE IF EXISTS `initiativerun`;
RENAME TABLE `initiative_run__new` TO `initiative_run`;
CREATE OR REPLACE VIEW `initiativerun` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `problem_space_id` AS `problemSpaceId`, `initiative_key` AS `initiativeKey`, `title` AS `title`, `summary` AS `summary`, `status` AS `status`, `target_outcome` AS `targetOutcome`, `next_review_at` AS `nextReviewAt`, `boundary_note` AS `boundaryNote`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `initiative_run`;
DROP TABLE IF EXISTS `limited_auto_intent`;
DROP TABLE IF EXISTS `limitedautointent`;
RENAME TABLE `limited_auto_intent__new` TO `limited_auto_intent`;
CREATE OR REPLACE VIEW `limitedautointent` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_event_id` AS `runtimeEventId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `source_write_intent_id` AS `sourceWriteIntentId`, `official_system_type` AS `officialSystemType`, `official_object_ref` AS `officialObjectRef`, `limited_auto_action_type` AS `limitedAutoActionType`, `limited_auto_eligibility_status` AS `limitedAutoEligibilityStatus`, `limited_auto_eligibility_reason` AS `limitedAutoEligibilityReason`, `limited_auto_approval_required` AS `limitedAutoApprovalRequired`, `limited_auto_approval_status` AS `limitedAutoApprovalStatus`, `limited_auto_execution_status` AS `limitedAutoExecutionStatus`, `limited_auto_ack_status` AS `limitedAutoAckStatus`, `limited_auto_failure_status` AS `limitedAutoFailureStatus`, `limited_auto_rollback_status` AS `limitedAutoRollbackStatus`, `approval_requirements` AS `approvalRequirements`, `proposed_write_payload` AS `proposedWritePayload`, `risk_review_summary` AS `riskReviewSummary`, `evidence_refs` AS `evidenceRefs`, `source_provenance` AS `sourceProvenance`, `boundary_trace` AS `boundaryTrace`, `confidence` AS `confidence`, `open_questions` AS `openQuestions`, `what_auto_path_will_do` AS `whatAutoPathWillDo`, `what_auto_path_will_not_do` AS `whatAutoPathWillNotDo`, `manual_only_reason` AS `manualOnlyReason`, `review_notes` AS `reviewNotes`, `approved_by_user_id` AS `approvedByUserId`, `approved_by_name` AS `approvedByName`, `approved_at` AS `approvedAt`, `rejected_by_user_id` AS `rejectedByUserId`, `rejected_by_name` AS `rejectedByName`, `rejected_at` AS `rejectedAt`, `attempted_by_user_id` AS `attemptedByUserId`, `attempted_by_name` AS `attemptedByName`, `attempted_at` AS `attemptedAt`, `acknowledged_by_user_id` AS `acknowledgedByUserId`, `acknowledged_by_name` AS `acknowledgedByName`, `acknowledged_at` AS `acknowledgedAt`, `limited_auto_ack_payload` AS `limitedAutoAckPayload`, `limited_auto_failure_reason` AS `limitedAutoFailureReason`, `manual_reconciliation_note` AS `manualReconciliationNote`, `deferred_retry_note` AS `deferredRetryNote`, `rollback_note` AS `rollbackNote`, `external_system_reference` AS `externalSystemReference`, `limited_auto_audit_ref` AS `limitedAutoAuditRef`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `limited_auto_intent`;
DROP TABLE IF EXISTS `llm_call_log`;
DROP TABLE IF EXISTS `llmcalllog`;
RENAME TABLE `llm_call_log__new` TO `llm_call_log`;
CREATE OR REPLACE VIEW `llmcalllog` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `provider` AS `provider`, `model` AS `model`, `model_version` AS `modelVersion`, `model_role` AS `modelRole`, `task_type` AS `taskType`, `prompt_key` AS `promptKey`, `prompt_version` AS `promptVersion`, `budget_tier` AS `budgetTier`, `output_mode` AS `outputMode`, `input_summary` AS `inputSummary`, `output_summary` AS `outputSummary`, `token_usage_prompt` AS `tokenUsagePrompt`, `token_usage_completion` AS `tokenUsageCompletion`, `latency_ms` AS `latencyMs`, `success` AS `success`, `fallback_reason` AS `fallbackReason`, `error_message` AS `errorMessage`, `create_time` AS `createdAt` FROM `llm_call_log`;
DROP TABLE IF EXISTS `n_meeting`;
DROP TABLE IF EXISTS `meeting`;
RENAME TABLE `n_meeting__new` TO `n_meeting`;
CREATE OR REPLACE VIEW `meeting` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `company_id` AS `companyId`, `opportunity_id` AS `opportunityId`, `owner_id` AS `ownerId`, `title` AS `title`, `agenda` AS `agenda`, `location` AS `location`, `external_source` AS `externalSource`, `external_object_type` AS `externalObjectType`, `external_object_id` AS `externalObjectId`, `external_owner_id` AS `externalOwnerId`, `external_synced_at` AS `externalSyncedAt`, `briefing_snapshot_id` AS `briefingSnapshotId`, `post_meeting_summary` AS `postMeetingSummary`, `status` AS `status`, `starts_at` AS `startsAt`, `ends_at` AS `endsAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `n_meeting`;
DROP TABLE IF EXISTS `meeting_note`;
DROP TABLE IF EXISTS `meetingnote`;
RENAME TABLE `meeting_note__new` TO `meeting_note`;
CREATE OR REPLACE VIEW `meetingnote` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `meeting_id` AS `meetingId`, `note_kind` AS `noteKind`, `attendees_summary` AS `attendeesSummary`, `relationship_summary` AS `relationshipSummary`, `previous_conclusion` AS `previousConclusion`, `meeting_goal` AS `meetingGoal`, `recommended_questions` AS `recommendedQuestions`, `risk_alerts` AS `riskAlerts`, `live_transcript` AS `liveTranscript`, `summary` AS `summary`, `key_decisions` AS `keyDecisions`, `confirmations` AS `confirmations`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `meeting_note`;
DROP TABLE IF EXISTS `n_membership`;
DROP TABLE IF EXISTS `membership`;
RENAME TABLE `n_membership__new` TO `n_membership`;
CREATE OR REPLACE VIEW `membership` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `role` AS `role`, `status` AS `status`, `title` AS `title`, `persona` AS `persona`, `role_preset_key` AS `rolePresetKey`, `definition_draft_json` AS `definitionDraftJson`, `definition_accepted_json` AS `definitionAcceptedJson`, `definition_accepted_at` AS `definitionAcceptedAt`, `joined_at` AS `joinedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `n_membership`;
DROP TABLE IF EXISTS `memory_candidate`;
DROP TABLE IF EXISTS `memorycandidate`;
RENAME TABLE `memory_candidate__new` TO `memory_candidate`;
CREATE OR REPLACE VIEW `memorycandidate` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `runtime_event_id` AS `runtimeEventId`, `meeting_id` AS `meetingId`, `memory_item_id` AS `memoryItemId`, `artifact_bundle_id` AS `artifactBundleId`, `candidate_key` AS `candidateKey`, `summary` AS `summary`, `source_verification` AS `sourceVerification`, `source_status` AS `sourceStatus`, `status` AS `status`, `reviewer_note` AS `reviewerNote`, `evidence_refs` AS `evidenceRefs`, `confidence` AS `confidence`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `memory_candidate`;
DROP TABLE IF EXISTS `memory_correction`;
DROP TABLE IF EXISTS `memorycorrection`;
RENAME TABLE `memory_correction__new` TO `memory_correction`;
CREATE OR REPLACE VIEW `memorycorrection` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `memory_fact_id` AS `memoryFactId`, `correction_type` AS `correctionType`, `before_value` AS `beforeValue`, `after_value` AS `afterValue`, `corrected_by_user_id` AS `correctedByUserId`, `reason` AS `reason`, `create_time` AS `createdAt` FROM `memory_correction`;
DROP TABLE IF EXISTS `memory_entry`;
DROP TABLE IF EXISTS `memoryentry`;
RENAME TABLE `memory_entry__new` TO `memory_entry`;
CREATE OR REPLACE VIEW `memoryentry` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `contact_id` AS `contactId`, `company_id` AS `companyId`, `opportunity_id` AS `opportunityId`, `meeting_id` AS `meetingId`, `entity_type` AS `entityType`, `memory_type` AS `memoryType`, `title` AS `title`, `content` AS `content`, `source` AS `source`, `corrected_at` AS `correctedAt`, `deleted_at` AS `deletedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `memory_entry`;
DROP TABLE IF EXISTS `memory_fact`;
DROP TABLE IF EXISTS `memoryfact`;
RENAME TABLE `memory_fact__new` TO `memory_fact`;
CREATE OR REPLACE VIEW `memoryfact` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `object_type` AS `objectType`, `object_id` AS `objectId`, `fact_type` AS `factType`, `title` AS `title`, `content` AS `content`, `normalized_value` AS `normalizedValue`, `source_type` AS `sourceType`, `source_id` AS `sourceId`, `confidence` AS `confidence`, `importance` AS `importance`, `freshness_score` AS `freshnessScore`, `status` AS `status`, `confirmed_by_user` AS `confirmedByUser`, `created_by_system` AS `createdBySystem`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `memory_fact`;
DROP TABLE IF EXISTS `memory_item`;
DROP TABLE IF EXISTS `memoryitem`;
RENAME TABLE `memory_item__new` TO `memory_item`;
CREATE OR REPLACE VIEW `memoryitem` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_event_id` AS `runtimeEventId`, `worker_run_id` AS `workerRunId`, `artifact_bundle_id` AS `artifactBundleId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `object_type` AS `objectType`, `object_id` AS `objectId`, `kind` AS `kind`, `scope` AS `scope`, `namespace` AS `namespace`, `status` AS `status`, `verification` AS `verification`, `sensitivity` AS `sensitivity`, `retention` AS `retention`, `promotion_rule` AS `promotionRule`, `writer` AS `writer`, `summary` AS `summary`, `payload` AS `payload`, `source_provenance` AS `sourceProvenance`, `evidence_refs` AS `evidenceRefs`, `confidence` AS `confidence`, `last_validated_at` AS `lastValidatedAt`, `confirmed_at` AS `confirmedAt`, `promoted_at` AS `promotedAt`, `deprecated_at` AS `deprecatedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `memory_item`;
DROP TABLE IF EXISTS `memory_link`;
DROP TABLE IF EXISTS `memorylink`;
RENAME TABLE `memory_link__new` TO `memory_link`;
CREATE OR REPLACE VIEW `memorylink` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `from_fact_id` AS `fromFactId`, `to_fact_id` AS `toFactId`, `relation_type` AS `relationType`, `weight` AS `weight`, `create_time` AS `createdAt` FROM `memory_link`;
DROP TABLE IF EXISTS `memory_promotion`;
DROP TABLE IF EXISTS `memorypromotion`;
RENAME TABLE `memory_promotion__new` TO `memory_promotion`;
CREATE OR REPLACE VIEW `memorypromotion` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `memory_candidate_id` AS `memoryCandidateId`, `memory_item_id` AS `memoryItemId`, `promotion_key` AS `promotionKey`, `status` AS `status`, `rationale` AS `rationale`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `memory_promotion`;
DROP TABLE IF EXISTS `n_notification`;
DROP TABLE IF EXISTS `notification`;
RENAME TABLE `n_notification__new` TO `n_notification`;
CREATE OR REPLACE VIEW `notification` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `type` AS `type`, `title` AS `title`, `body` AS `body`, `url` AS `url`, `read_at` AS `readAt`, `create_time` AS `createdAt` FROM `n_notification`;
DROP TABLE IF EXISTS `official_follow_through`;
DROP TABLE IF EXISTS `officialfollowthrough`;
RENAME TABLE `official_follow_through__new` TO `official_follow_through`;
CREATE OR REPLACE VIEW `officialfollowthrough` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_event_id` AS `runtimeEventId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `source_write_intent_id` AS `sourceWriteIntentId`, `source_limited_auto_intent_id` AS `sourceLimitedAutoIntentId`, `source_ack_id` AS `sourceAckId`, `source_action_type` AS `sourceActionType`, `official_object_ref` AS `officialObjectRef`, `follow_through_key` AS `followThroughKey`, `follow_through_type` AS `followThroughType`, `exception_class` AS `exceptionClass`, `exception_severity` AS `exceptionSeverity`, `reconciliation_status` AS `reconciliationStatus`, `follow_through_status` AS `followThroughStatus`, `follow_through_resolution_status` AS `followThroughResolutionStatus`, `follow_through_owner_id` AS `followThroughOwnerId`, `follow_through_owner_name` AS `followThroughOwnerName`, `follow_through_next_action` AS `followThroughNextAction`, `follow_through_deadline` AS `followThroughDeadline`, `follow_through_boundary` AS `followThroughBoundary`, `follow_through_evidence_refs` AS `followThroughEvidenceRefs`, `follow_through_writeback_targets` AS `followThroughWritebackTargets`, `follow_through_summary` AS `followThroughSummary`, `resolution_note` AS `resolutionNote`, `reconciliation_note` AS `reconciliationNote`, `manager_attention_required` AS `managerAttentionRequired`, `manual_fallback_required` AS `manualFallbackRequired`, `role_handoff_impact` AS `roleHandoffImpact`, `summary_writeback_impact` AS `summaryWritebackImpact`, `blocker_summary_impact` AS `blockerSummaryImpact`, `escalation_reason` AS `escalationReason`, `audit_ref` AS `auditRef`, `resolved_by_user_id` AS `resolvedByUserId`, `resolved_by_name` AS `resolvedByName`, `resolved_at` AS `resolvedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `official_follow_through`;
DROP TABLE IF EXISTS `official_write_intent`;
DROP TABLE IF EXISTS `officialwriteintent`;
RENAME TABLE `official_write_intent__new` TO `official_write_intent`;
CREATE OR REPLACE VIEW `officialwriteintent` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_event_id` AS `runtimeEventId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `source_artifact_bundle_id` AS `sourceArtifactBundleId`, `source_human_action_execution_id` AS `sourceHumanActionExecutionId`, `source_key` AS `sourceKey`, `official_system_type` AS `officialSystemType`, `official_object_ref` AS `officialObjectRef`, `source_type` AS `sourceType`, `source_title` AS `sourceTitle`, `source_summary` AS `sourceSummary`, `write_action_type` AS `writeActionType`, `write_payload_draft` AS `writePayloadDraft`, `write_boundary` AS `writeBoundary`, `write_approval_tier` AS `writeApprovalTier`, `write_approval_status` AS `writeApprovalStatus`, `write_execution_status` AS `writeExecutionStatus`, `write_acknowledgement_status` AS `writeAcknowledgementStatus`, `source_shadow_ref` AS `sourceShadowRef`, `source_execution_proof_ref` AS `sourceExecutionProofRef`, `approval_requirements` AS `approvalRequirements`, `risk_review_summary` AS `riskReviewSummary`, `evidence_refs` AS `evidenceRefs`, `source_provenance` AS `sourceProvenance`, `boundary_trace` AS `boundaryTrace`, `confidence` AS `confidence`, `open_questions` AS `openQuestions`, `what_this_changes` AS `whatThisChanges`, `what_this_does_not_mean` AS `whatThisDoesNotMean`, `review_notes` AS `reviewNotes`, `approved_by_user_id` AS `approvedByUserId`, `approved_by_name` AS `approvedByName`, `approved_at` AS `approvedAt`, `rejected_by_user_id` AS `rejectedByUserId`, `rejected_by_name` AS `rejectedByName`, `rejected_at` AS `rejectedAt`, `attempted_by_user_id` AS `attemptedByUserId`, `attempted_by_name` AS `attemptedByName`, `attempted_at` AS `attemptedAt`, `acknowledged_by_user_id` AS `acknowledgedByUserId`, `acknowledged_by_name` AS `acknowledgedByName`, `acknowledged_at` AS `acknowledgedAt`, `write_acknowledgement_payload` AS `writeAcknowledgementPayload`, `write_failure_reason` AS `writeFailureReason`, `manual_reconciliation_note` AS `manualReconciliationNote`, `deferred_retry_note` AS `deferredRetryNote`, `external_system_reference` AS `externalSystemReference`, `write_audit_ref` AS `writeAuditRef`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `official_write_intent`;
DROP TABLE IF EXISTS `n_opportunity`;
DROP TABLE IF EXISTS `opportunity`;
RENAME TABLE `n_opportunity__new` TO `n_opportunity`;
CREATE OR REPLACE VIEW `opportunity` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `company_id` AS `companyId`, `owner_id` AS `ownerId`, `title` AS `title`, `description` AS `description`, `type` AS `type`, `stage` AS `stage`, `risk_level` AS `riskLevel`, `next_action` AS `nextAction`, `shadow_stage` AS `shadowStage`, `shadow_risk_level` AS `shadowRiskLevel`, `shadow_next_action` AS `shadowNextAction`, `shadow_blockers_summary` AS `shadowBlockersSummary`, `shadow_manager_attention_flag` AS `shadowManagerAttentionFlag`, `shadow_stage_confidence` AS `shadowStageConfidence`, `shadow_updated_at` AS `shadowUpdatedAt`, `external_source` AS `externalSource`, `external_object_type` AS `externalObjectType`, `external_object_id` AS `externalObjectId`, `external_owner_id` AS `externalOwnerId`, `external_synced_at` AS `externalSyncedAt`, `due_date` AS `dueDate`, `priority_score` AS `priorityScore`, `loss_reason` AS `lossReason`, `last_progress_at` AS `lastProgressAt`, `next_step_summary` AS `nextStepSummary`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `n_opportunity`;
DROP TABLE IF EXISTS `participant_portal_access`;
DROP TABLE IF EXISTS `participantportalaccess`;
RENAME TABLE `participant_portal_access__new` TO `participant_portal_access`;
CREATE OR REPLACE VIEW `participantportalaccess` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `beneficiary_type` AS `beneficiaryType`, `beneficiary_reference` AS `beneficiaryReference`, `invite_email` AS `inviteEmail`, `display_name` AS `displayName`, `contact` AS `contact`, `invite_token_hash` AS `inviteTokenHash`, `terms_accepted_at` AS `termsAcceptedAt`, `status` AS `status`, `last_invite_issued_at` AS `lastInviteIssuedAt`, `activated_at` AS `activatedAt`, `suspended_at` AS `suspendedAt`, `archived_at` AS `archivedAt`, `notes` AS `notes`, `worker_publisher_profile_id` AS `workerPublisherProfileId`, `sales_referral_id` AS `salesReferralId`, `custom_engagement_id` AS `customEngagementId`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `participant_portal_access`;
DROP TABLE IF EXISTS `partner_program`;
DROP TABLE IF EXISTS `partnerprogram`;
RENAME TABLE `partner_program__new` TO `partner_program`;
CREATE OR REPLACE VIEW `partnerprogram` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `program_key` AS `programKey`, `slug` AS `slug`, `title` AS `title`, `summary` AS `summary`, `program_type` AS `programType`, `beneficiary_type` AS `beneficiaryType`, `status` AS `status`, `audience_summary` AS `audienceSummary`, `contribution_summary` AS `contributionSummary`, `revenue_summary` AS `revenueSummary`, `settlement_summary` AS `settlementSummary`, `boundary_summary` AS `boundarySummary`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `partner_program`;
DROP TABLE IF EXISTS `pattern_fact`;
DROP TABLE IF EXISTS `patternfact`;
RENAME TABLE `pattern_fact__new` TO `pattern_fact`;
CREATE OR REPLACE VIEW `patternfact` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `fingerprint` AS `fingerprint`, `scope_type` AS `scopeType`, `scope_id` AS `scopeId`, `pattern_type` AS `patternType`, `pattern_key` AS `patternKey`, `pattern_value` AS `patternValue`, `confidence` AS `confidence`, `evidence_count` AS `evidenceCount`, `status` AS `status`, `title` AS `title`, `summary` AS `summary`, `evidence_snapshot` AS `evidenceSnapshot`, `first_detected_at` AS `firstDetectedAt`, `last_detected_at` AS `lastDetectedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `pattern_fact`;
DROP TABLE IF EXISTS `payment_webhook_callback_event`;
DROP TABLE IF EXISTS `paymentwebhookcallbackevent`;
RENAME TABLE `payment_webhook_callback_event__new` TO `payment_webhook_callback_event`;
CREATE OR REPLACE VIEW `paymentwebhookcallbackevent` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `provider` AS `provider`, `callback_mode` AS `callbackMode`, `external_event_id` AS `externalEventId`, `callback_fingerprint` AS `callbackFingerprint`, `governance_status` AS `governanceStatus`, `action_type` AS `actionType`, `resolution_source` AS `resolutionSource`, `failure_reason` AS `failureReason`, `authoritative_source` AS `authoritativeSource`, `hint_source` AS `hintSource`, `hint_workspace_id` AS `hintWorkspaceId`, `summary` AS `summary`, `payload_json` AS `payloadJson`, `duplicate_reception_count` AS `duplicateReceptionCount`, `first_received_at` AS `firstReceivedAt`, `last_received_at` AS `lastReceivedAt`, `last_duplicate_at` AS `lastDuplicateAt`, `processed_at` AS `processedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `payment_webhook_callback_event`;
DROP TABLE IF EXISTS `payout_ledger`;
DROP TABLE IF EXISTS `payoutledger`;
RENAME TABLE `payout_ledger__new` TO `payout_ledger`;
CREATE OR REPLACE VIEW `payoutledger` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `revenue_attribution_ledger_id` AS `revenueAttributionLedgerId`, `beneficiary_type` AS `beneficiaryType`, `beneficiary_label` AS `beneficiaryLabel`, `payable_amount_cents` AS `payableAmountCents`, `currency` AS `currency`, `status` AS `status`, `payable_after` AS `payableAfter`, `approved_at` AS `approvedAt`, `paid_at` AS `paidAt`, `reversed_at` AS `reversedAt`, `notes` AS `notes`, `worker_publisher_profile_id` AS `workerPublisherProfileId`, `sales_referral_id` AS `salesReferralId`, `custom_engagement_id` AS `customEngagementId`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `payout_ledger`;
DROP TABLE IF EXISTS `persisted_payload`;
DROP TABLE IF EXISTS `persistedpayload`;
RENAME TABLE `persisted_payload__new` TO `persisted_payload`;
CREATE OR REPLACE VIEW `persistedpayload` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `runtime_event_id` AS `runtimeEventId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `payload_key` AS `payloadKey`, `source_type` AS `sourceType`, `source_id` AS `sourceId`, `load_policy` AS `loadPolicy`, `label` AS `label`, `handle` AS `handle`, `preview` AS `preview`, `summary` AS `summary`, `payload_text` AS `payloadText`, `byte_size` AS `byteSize`, `estimated_tokens` AS `estimatedTokens`, `loaded_by_default` AS `loadedByDefault`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `persisted_payload`;
DROP TABLE IF EXISTS `policy_rule`;
DROP TABLE IF EXISTS `policyrule`;
RENAME TABLE `policy_rule__new` TO `policy_rule`;
CREATE OR REPLACE VIEW `policyrule` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `name` AS `name`, `action_type` AS `actionType`, `mode` AS `mode`, `risk_threshold` AS `riskThreshold`, `applies_to` AS `appliesTo`, `description` AS `description`, `enabled` AS `enabled`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `policy_rule`;
DROP TABLE IF EXISTS `preference_signal`;
DROP TABLE IF EXISTS `preferencesignal`;
RENAME TABLE `preference_signal__new` TO `preference_signal`;
CREATE OR REPLACE VIEW `preferencesignal` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `signal_type` AS `signalType`, `signal_key` AS `signalKey`, `signal_value` AS `signalValue`, `source_action_id` AS `sourceActionId`, `source_recommendation_id` AS `sourceRecommendationId`, `weight` AS `weight`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `preference_signal`;
DROP TABLE IF EXISTS `problem_space`;
DROP TABLE IF EXISTS `problemspace`;
RENAME TABLE `problem_space__new` TO `problem_space`;
CREATE OR REPLACE VIEW `problemspace` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `source_world_model_key` AS `sourceWorldModelKey`, `problem_key` AS `problemKey`, `title` AS `title`, `summary` AS `summary`, `next_step` AS `nextStep`, `status` AS `status`, `evidence_refs` AS `evidenceRefs`, `owner_hint` AS `ownerHint`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `problem_space`;
DROP TABLE IF EXISTS `program_application`;
DROP TABLE IF EXISTS `programapplication`;
RENAME TABLE `program_application__new` TO `program_application`;
CREATE OR REPLACE VIEW `programapplication` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `partner_program_id` AS `partnerProgramId`, `program_terms_version_id` AS `programTermsVersionId`, `applicant_name` AS `applicantName`, `applicant_email` AS `applicantEmail`, `applicant_organization` AS `applicantOrganization`, `role_title` AS `roleTitle`, `website` AS `website`, `region_label` AS `regionLabel`, `background` AS `background`, `contribution_plan` AS `contributionPlan`, `terms_accepted_at` AS `termsAcceptedAt`, `status` AS `status`, `internal_notes` AS `internalNotes`, `recommended_beneficiary_type` AS `recommendedBeneficiaryType`, `worker_publisher_profile_id` AS `workerPublisherProfileId`, `sales_referral_id` AS `salesReferralId`, `custom_engagement_id` AS `customEngagementId`, `participant_portal_access_id` AS `participantPortalAccessId`, `reviewed_at` AS `reviewedAt`, `invited_at` AS `invitedAt`, `reviewed_by_user_id` AS `reviewedByUserId`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `program_application`;
DROP TABLE IF EXISTS `program_terms_version`;
DROP TABLE IF EXISTS `programtermsversion`;
RENAME TABLE `program_terms_version__new` TO `program_terms_version`;
CREATE OR REPLACE VIEW `programtermsversion` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `partner_program_id` AS `partnerProgramId`, `version_key` AS `versionKey`, `title` AS `title`, `summary` AS `summary`, `revenue_definition` AS `revenueDefinition`, `split_logic_summary` AS `splitLogicSummary`, `reversal_rule_summary` AS `reversalRuleSummary`, `review_boundary_summary` AS `reviewBoundarySummary`, `payout_boundary_summary` AS `payoutBoundarySummary`, `platform_rights_summary` AS `platformRightsSummary`, `status` AS `status`, `effective_from` AS `effectiveFrom`, `published_at` AS `publishedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `program_terms_version`;
DROP TABLE IF EXISTS `prompt_cache_telemetry`;
DROP TABLE IF EXISTS `promptcachetelemetry`;
RENAME TABLE `prompt_cache_telemetry__new` TO `prompt_cache_telemetry`;
CREATE OR REPLACE VIEW `promptcachetelemetry` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `cache_key` AS `cacheKey`, `prompt_label` AS `promptLabel`, `cache_status` AS `cacheStatus`, `tokens_before` AS `tokensBefore`, `tokens_after` AS `tokensAfter`, `tokens_saved` AS `tokensSaved`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `prompt_cache_telemetry`;
DROP TABLE IF EXISTS `recommendation_feedback`;
DROP TABLE IF EXISTS `recommendationfeedback`;
RENAME TABLE `recommendation_feedback__new` TO `recommendation_feedback`;
CREATE OR REPLACE VIEW `recommendationfeedback` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `recommendation_log_id` AS `recommendationLogId`, `user_id` AS `userId`, `feedback_type` AS `feedbackType`, `edited` AS `edited`, `result_note` AS `resultNote`, `action_item_id` AS `actionItemId`, `approval_task_id` AS `approvalTaskId`, `create_time` AS `createdAt` FROM `recommendation_feedback`;
DROP TABLE IF EXISTS `recommendation_log`;
DROP TABLE IF EXISTS `recommendationlog`;
RENAME TABLE `recommendation_log__new` TO `recommendation_log`;
CREATE OR REPLACE VIEW `recommendationlog` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `object_type` AS `objectType`, `object_id` AS `objectId`, `action_type` AS `actionType`, `title` AS `title`, `description` AS `description`, `recommendation_payload` AS `recommendationPayload`, `score` AS `score`, `urgency_score` AS `urgencyScore`, `impact_score` AS `impactScore`, `confidence_score` AS `confidenceScore`, `personalization_score` AS `personalizationScore`, `policy_fit_score` AS `policyFitScore`, `risk_score` AS `riskScore`, `policy_result` AS `policyResult`, `supporting_fact_ids` AS `supportingFactIds`, `blocker_ids` AS `blockerIds`, `commitment_ids` AS `commitmentIds`, `explanation` AS `explanation`, `status` AS `status`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `recommendation_log`;
DROP TABLE IF EXISTS `retrieval_trace`;
DROP TABLE IF EXISTS `retrievaltrace`;
RENAME TABLE `retrieval_trace__new` TO `retrieval_trace`;
CREATE OR REPLACE VIEW `retrievaltrace` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_event_id` AS `runtimeEventId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `runtime_label` AS `runtimeLabel`, `worker_id` AS `workerId`, `trigger_mode` AS `triggerMode`, `trigger_key` AS `triggerKey`, `bucket` AS `bucket`, `rationale` AS `rationale`, `loaded_refs` AS `loadedRefs`, `skipped_refs` AS `skippedRefs`, `evidence_refs` AS `evidenceRefs`, `source_provenance` AS `sourceProvenance`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `retrieval_trace`;
DROP TABLE IF EXISTS `revenue_attribution_ledger`;
DROP TABLE IF EXISTS `revenueattributionledger`;
RENAME TABLE `revenue_attribution_ledger__new` TO `revenue_attribution_ledger`;
CREATE OR REPLACE VIEW `revenueattributionledger` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `revenue_rule_id` AS `revenueRuleId`, `source_type` AS `sourceType`, `beneficiary_type` AS `beneficiaryType`, `source_label` AS `sourceLabel`, `source_reference` AS `sourceReference`, `beneficiary_label` AS `beneficiaryLabel`, `gross_amount_cents` AS `grossAmountCents`, `attributed_amount_cents` AS `attributedAmountCents`, `currency` AS `currency`, `status` AS `status`, `recognized_at` AS `recognizedAt`, `reversal_of_id` AS `reversalOfId`, `reversal_reason` AS `reversalReason`, `metadata` AS `metadata`, `worker_publisher_profile_id` AS `workerPublisherProfileId`, `sales_referral_id` AS `salesReferralId`, `custom_engagement_id` AS `customEngagementId`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `revenue_attribution_ledger`;
DROP TABLE IF EXISTS `revenue_rule`;
DROP TABLE IF EXISTS `revenuerule`;
RENAME TABLE `revenue_rule__new` TO `revenue_rule`;
CREATE OR REPLACE VIEW `revenuerule` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `rule_key` AS `ruleKey`, `name` AS `name`, `source_type` AS `sourceType`, `beneficiary_type` AS `beneficiaryType`, `beneficiary_label` AS `beneficiaryLabel`, `cadence` AS `cadence`, `value_type` AS `valueType`, `percent_bps` AS `percentBps`, `fixed_amount_cents` AS `fixedAmountCents`, `currency` AS `currency`, `reverse_on_cancel` AS `reverseOnCancel`, `worker_key` AS `workerKey`, `notes` AS `notes`, `status` AS `status`, `effective_from` AS `effectiveFrom`, `effective_to` AS `effectiveTo`, `worker_publisher_profile_id` AS `workerPublisherProfileId`, `sales_referral_id` AS `salesReferralId`, `custom_engagement_id` AS `customEngagementId`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `revenue_rule`;
DROP TABLE IF EXISTS `runtime_event`;
DROP TABLE IF EXISTS `runtimeevent`;
RENAME TABLE `runtime_event__new` TO `runtime_event`;
CREATE OR REPLACE VIEW `runtimeevent` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `related_object_type` AS `relatedObjectType`, `related_object_id` AS `relatedObjectId`, `event_type` AS `eventType`, `status` AS `status`, `trusted_context` AS `trustedContext`, `untrusted_context` AS `untrustedContext`, `payload` AS `payload`, `source_provenance` AS `sourceProvenance`, `triggered_by` AS `triggeredBy`, `error_message` AS `errorMessage`, `queued_at` AS `queuedAt`, `started_at` AS `startedAt`, `completed_at` AS `completedAt`, `failed_at` AS `failedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `runtime_event`;
DROP TABLE IF EXISTS `runtime_session`;
DROP TABLE IF EXISTS `runtimesession`;
RENAME TABLE `runtime_session__new` TO `runtime_session`;
CREATE OR REPLACE VIEW `runtimesession` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_event_id` AS `runtimeEventId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `session_key` AS `sessionKey`, `label` AS `label`, `status` AS `status`, `current_stage` AS `currentStage`, `source_page` AS `sourcePage`, `boundary_note` AS `boundaryNote`, `budget_token_limit` AS `budgetTokenLimit`, `budget_token_used` AS `budgetTokenUsed`, `loaded_token_count` AS `loadedTokenCount`, `pruned_token_count` AS `prunedTokenCount`, `replayable_event_log` AS `replayableEventLog`, `control_plane_lifecycle_json` AS `controlPlaneLifecycleJson`, `control_plane_lifecycle_updated` AS `controlPlaneLifecycleUpdatedAt`, `resumed_from_key` AS `resumedFromKey`, `closed_at` AS `closedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `runtime_session`;
DROP TABLE IF EXISTS `sales_referral`;
DROP TABLE IF EXISTS `salesreferral`;
RENAME TABLE `sales_referral__new` TO `sales_referral`;
CREATE OR REPLACE VIEW `salesreferral` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `referral_key` AS `referralKey`, `beneficiary_label` AS `beneficiaryLabel`, `beneficiary_contact` AS `beneficiaryContact`, `notes` AS `notes`, `status` AS `status`, `effective_from` AS `effectiveFrom`, `effective_to` AS `effectiveTo`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `sales_referral`;
DROP TABLE IF EXISTS `seat_profile_job_run`;
DROP TABLE IF EXISTS `seatprofilejobrun`;
RENAME TABLE `seat_profile_job_run__new` TO `seat_profile_job_run`;
CREATE OR REPLACE VIEW `seatprofilejobrun` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `profile_date` AS `profileDate`, `status` AS `status`, `start_time` AS `startTime`, `end_time` AS `endTime`, `duration_ms` AS `durationMs`, `source_as_of_time` AS `sourceAsOfTime`, `error_message` AS `errorMessage`, `create_time` AS `createdAt` FROM `seat_profile_job_run`;
DROP TABLE IF EXISTS `seat_profile_result`;
DROP TABLE IF EXISTS `seatprofileresult`;
RENAME TABLE `seat_profile_result__new` TO `seat_profile_result`;
CREATE OR REPLACE VIEW `seatprofileresult` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `profile_date` AS `profileDate`, `org_id` AS `orgId`, `org_name` AS `orgName`, `emp_id` AS `empId`, `emp_name` AS `empName`, `seat_profile_score` AS `seatProfileScore`, `score_execution_efficiency` AS `scoreExecutionEfficiency`, `score_repayment_performance` AS `scoreRepaymentPerformance`, `score_compliance_risk` AS `scoreComplianceRisk`, `score_call_quality` AS `scoreCallQuality`, `metrics_json` AS `metricsJson`, `source_as_of_time` AS `sourceAsOfTime`, `formula_version` AS `formulaVersion`, `data_quality_flag` AS `dataQualityFlag`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `seat_profile_result`;
DROP TABLE IF EXISTS `session_checkpoint`;
DROP TABLE IF EXISTS `sessioncheckpoint`;
RENAME TABLE `session_checkpoint__new` TO `session_checkpoint`;
CREATE OR REPLACE VIEW `sessioncheckpoint` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `checkpoint_key` AS `checkpointKey`, `label` AS `label`, `status` AS `status`, `summary` AS `summary`, `snapshot_json` AS `snapshotJson`, `token_count` AS `tokenCount`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `session_checkpoint`;
DROP TABLE IF EXISTS `session_notebook`;
DROP TABLE IF EXISTS `sessionnotebook`;
RENAME TABLE `session_notebook__new` TO `session_notebook`;
CREATE OR REPLACE VIEW `sessionnotebook` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `session_summary` AS `sessionSummary`, `decision_summary` AS `decisionSummary`, `blocker_summary` AS `blockerSummary`, `pending_questions` AS `pendingQuestions`, `open_loop_summary` AS `openLoopSummary`, `boundary_note` AS `boundaryNote`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `session_notebook`;
DROP TABLE IF EXISTS `settlement_batch`;
DROP TABLE IF EXISTS `settlementbatch`;
RENAME TABLE `settlement_batch__new` TO `settlement_batch`;
CREATE OR REPLACE VIEW `settlementbatch` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `batch_key` AS `batchKey`, `period_label` AS `periodLabel`, `period_start` AS `periodStart`, `period_end` AS `periodEnd`, `currency` AS `currency`, `status` AS `status`, `notes` AS `notes`, `approved_at` AS `approvedAt`, `exported_at` AS `exportedAt`, `closed_at` AS `closedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `settlement_batch`;
DROP TABLE IF EXISTS `settlement_batch_line`;
DROP TABLE IF EXISTS `settlementbatchline`;
RENAME TABLE `settlement_batch_line__new` TO `settlement_batch_line`;
CREATE OR REPLACE VIEW `settlementbatchline` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `settlement_batch_id` AS `settlementBatchId`, `payout_ledger_id` AS `payoutLedgerId`, `beneficiary_payout_profile_id` AS `beneficiaryPayoutProfileId`, `beneficiary_type` AS `beneficiaryType`, `beneficiary_label` AS `beneficiaryLabel`, `source_type` AS `sourceType`, `amount_cents` AS `amountCents`, `currency` AS `currency`, `status` AS `status`, `notes` AS `notes`, `reference` AS `reference`, `approved_at` AS `approvedAt`, `exported_at` AS `exportedAt`, `paid_at` AS `paidAt`, `reversed_at` AS `reversedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `settlement_batch_line`;
DROP TABLE IF EXISTS `signal_event`;
DROP TABLE IF EXISTS `signalevent`;
RENAME TABLE `signal_event__new` TO `signal_event`;
CREATE OR REPLACE VIEW `signalevent` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `signal_key` AS `signalKey`, `signal_type` AS `signalType`, `source_type` AS `sourceType`, `signal_summary` AS `signalSummary`, `normalized_payload` AS `normalizedPayload`, `truth_weight` AS `truthWeight`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `signal_event`;
DROP TABLE IF EXISTS `skill_suggestion`;
DROP TABLE IF EXISTS `skillsuggestion`;
RENAME TABLE `skill_suggestion__new` TO `skill_suggestion`;
CREATE OR REPLACE VIEW `skillsuggestion` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `fingerprint` AS `fingerprint`, `suggestion_type` AS `suggestionType`, `status` AS `status`, `candidate_skill_key` AS `candidateSkillKey`, `candidate_skill_name` AS `candidateSkillName`, `candidate_category` AS `candidateCategory`, `candidate_boundary` AS `candidateBoundary`, `candidate_effect_mode` AS `candidateEffectMode`, `candidate_default_surface` AS `candidateDefaultSurface`, `title` AS `title`, `reason` AS `reason`, `confidence` AS `confidence`, `candidate_spec_json` AS `candidateSpecJson`, `evidence_snapshot` AS `evidenceSnapshot`, `source_pattern_fact_ids` AS `sourcePatternFactIds`, `source_recommendation_ids` AS `sourceRecommendationIds`, `non_commitment_note` AS `nonCommitmentNote`, `confirmed_by_user_id` AS `confirmedByUserId`, `confirmed_at` AS `confirmedAt`, `applied_target_type` AS `appliedTargetType`, `applied_target_id` AS `appliedTargetId`, `applied_effect_summary` AS `appliedEffectSummary`, `applied_at` AS `appliedAt`, `formal_review_status` AS `formalReviewStatus`, `formal_review_queued_by_user_id` AS `formalReviewQueuedByUserId`, `formal_review_queued_at` AS `formalReviewQueuedAt`, `formal_review_summary` AS `formalReviewSummary`, `formal_review_decision` AS `formalReviewDecision`, `formal_review_decision_by_user_i` AS `formalReviewDecisionByUserId`, `formal_review_decision_by_name` AS `formalReviewDecisionByName`, `formal_review_decision_at` AS `formalReviewDecisionAt`, `formal_review_decision_note` AS `formalReviewDecisionNote`, `formal_review_checklist_json` AS `formalReviewChecklistJson`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `skill_suggestion`;
DROP TABLE IF EXISTS `strategy_suggestion`;
DROP TABLE IF EXISTS `strategysuggestion`;
RENAME TABLE `strategy_suggestion__new` TO `strategy_suggestion`;
CREATE OR REPLACE VIEW `strategysuggestion` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `fingerprint` AS `fingerprint`, `suggestion_type` AS `suggestionType`, `target_policy_key` AS `targetPolicyKey`, `current_value` AS `currentValue`, `suggested_value` AS `suggestedValue`, `title` AS `title`, `reason` AS `reason`, `confidence` AS `confidence`, `status` AS `status`, `evidence_snapshot` AS `evidenceSnapshot`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt`, `confirmed_by_user_id` AS `confirmedByUserId`, `confirmed_at` AS `confirmedAt`, `applied_target_type` AS `appliedTargetType`, `applied_target_id` AS `appliedTargetId`, `applied_effect_summary` AS `appliedEffectSummary`, `applied_at` AS `appliedAt` FROM `strategy_suggestion`;
DROP TABLE IF EXISTS `trial_state`;
DROP TABLE IF EXISTS `trialstate`;
RENAME TABLE `trial_state__new` TO `trial_state`;
CREATE OR REPLACE VIEW `trialstate` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `trial_started_at` AS `trialStartedAt`, `trial_ends_at` AS `trialEndsAt`, `grace_ends_at` AS `graceEndsAt`, `status` AS `status`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `trial_state`;
DROP TABLE IF EXISTS `truth_conflict`;
DROP TABLE IF EXISTS `truthconflict`;
RENAME TABLE `truth_conflict__new` TO `truth_conflict`;
CREATE OR REPLACE VIEW `truthconflict` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `conflict_key` AS `conflictKey`, `subject_key` AS `subjectKey`, `preferred_source` AS `preferredSource`, `conflicting_source` AS `conflictingSource`, `summary` AS `summary`, `status` AS `status`, `resolution_note` AS `resolutionNote`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `truth_conflict`;
DROP TABLE IF EXISTS `usage_ledger`;
DROP TABLE IF EXISTS `usageledger`;
RENAME TABLE `usage_ledger__new` TO `usage_ledger`;
CREATE OR REPLACE VIEW `usageledger` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `user_id` AS `userId`, `usage_type` AS `usageType`, `quantity` AS `quantity`, `metadata` AS `metadata`, `source_page` AS `sourcePage`, `recorded_at` AS `recordedAt`, `create_time` AS `createdAt` FROM `usage_ledger`;
DROP TABLE IF EXISTS `n_user`;
DROP TABLE IF EXISTS `user`;
RENAME TABLE `n_user__new` TO `n_user`;
CREATE OR REPLACE VIEW `user` AS SELECT `legacy_id` AS `id`, `email` AS `email`, `phone` AS `phone`, `name` AS `name`, `title` AS `title`, `avatar` AS `avatar`, `email_verified_at` AS `emailVerifiedAt`, `phone_verified_at` AS `phoneVerifiedAt`, `password_hash` AS `passwordHash`, `password_set_at` AS `passwordSetAt`, `last_login_at` AS `lastLoginAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `n_user`;
DROP TABLE IF EXISTS `verification_report`;
DROP TABLE IF EXISTS `verificationreport`;
RENAME TABLE `verification_report__new` TO `verification_report`;
CREATE OR REPLACE VIEW `verificationreport` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `runtime_event_id` AS `runtimeEventId`, `artifact_bundle_id` AS `artifactBundleId`, `report_key` AS `reportKey`, `report_type` AS `reportType`, `status` AS `status`, `truth_score` AS `truthScore`, `summary` AS `summary`, `blocked_reasons` AS `blockedReasons`, `boundary_notes` AS `boundaryNotes`, `evidence_refs` AS `evidenceRefs`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `verification_report`;
DROP TABLE IF EXISTS `weekly_report`;
DROP TABLE IF EXISTS `weeklyreport`;
RENAME TABLE `weekly_report__new` TO `weekly_report`;
CREATE OR REPLACE VIEW `weeklyreport` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `week_start` AS `weekStart`, `week_end` AS `weekEnd`, `summary_text` AS `summaryText`, `opportunities_advanced_count` AS `opportunitiesAdvancedCount`, `overdue_followups_count` AS `overdueFollowupsCount`, `ai_suggestions_count` AS `aiSuggestionsCount`, `approvals_approved_count` AS `approvalsApprovedCount`, `open_high_risk_count` AS `openHighRiskCount`, `payload` AS `payload`, `create_time` AS `createdAt` FROM `weekly_report`;
DROP TABLE IF EXISTS `worker_entitlement`;
DROP TABLE IF EXISTS `workerentitlement`;
RENAME TABLE `worker_entitlement__new` TO `worker_entitlement`;
CREATE OR REPLACE VIEW `workerentitlement` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `worker_key` AS `workerKey`, `entitlement_type` AS `entitlementType`, `status` AS `status`, `effective_from` AS `effectiveFrom`, `effective_to` AS `effectiveTo`, `internal_limit` AS `internalLimit`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `worker_entitlement`;
DROP TABLE IF EXISTS `worker_publisher_profile`;
DROP TABLE IF EXISTS `workerpublisherprofile`;
RENAME TABLE `worker_publisher_profile__new` TO `worker_publisher_profile`;
CREATE OR REPLACE VIEW `workerpublisherprofile` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `publisher_key` AS `publisherKey`, `display_name` AS `displayName`, `contact_email` AS `contactEmail`, `status` AS `status`, `notes` AS `notes`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `worker_publisher_profile`;
DROP TABLE IF EXISTS `worker_run`;
DROP TABLE IF EXISTS `workerrun`;
RENAME TABLE `worker_run__new` TO `worker_run`;
CREATE OR REPLACE VIEW `workerrun` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_event_id` AS `runtimeEventId`, `agent_id` AS `agentId`, `status` AS `status`, `input_summary` AS `inputSummary`, `output_summary` AS `outputSummary`, `evidence_refs` AS `evidenceRefs`, `source_provenance` AS `sourceProvenance`, `confidence` AS `confidence`, `open_questions` AS `openQuestions`, `error_message` AS `errorMessage`, `started_at` AS `startedAt`, `completed_at` AS `completedAt`, `failed_at` AS `failedAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt`, `company_id` AS `companyId`, `opportunity_id` AS `opportunityId`, `meeting_id` AS `meetingId` FROM `worker_run`;
DROP TABLE IF EXISTS `n_workspace`;
DROP TABLE IF EXISTS `workspace`;
RENAME TABLE `n_workspace__new` TO `n_workspace`;
CREATE OR REPLACE VIEW `workspace` AS SELECT `legacy_id` AS `id`, `name` AS `name`, `slug` AS `slug`, `status` AS `status`, `workspace_class` AS `workspaceClass`, `system_key` AS `systemKey`, `description` AS `description`, `profile_type` AS `profileType`, `connected_sources` AS `connectedSources`, `focus_areas` AS `focusAreas`, `default_strategies` AS `defaultStrategies`, `configuration` AS `configuration`, `default_locale` AS `defaultLocale`, `pilot_mode` AS `pilotMode`, `feature_flags_json` AS `featureFlagsJson`, `data_retention_days` AS `dataRetentionDays`, `capture_consent_required` AS `captureConsentRequired`, `default_llm_provider` AS `defaultLLMProvider`, `default_llm_model` AS `defaultLLMModel`, `extraction_model` AS `extractionModel`, `briefing_model` AS `briefingModel`, `reasoning_model` AS `reasoningModel`, `llm_budget_tier` AS `llmBudgetTier`, `llm_enabled` AS `llmEnabled`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `n_workspace`;
DROP TABLE IF EXISTS `workspace_solution_extension`;
DROP TABLE IF EXISTS `workspacesolutionextension`;
RENAME TABLE `workspace_solution_extension__new` TO `workspace_solution_extension`;
CREATE OR REPLACE VIEW `workspacesolutionextension` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `extension_key` AS `extensionKey`, `kind` AS `kind`, `status` AS `status`, `version` AS `version`, `config_json` AS `configJson`, `enabled_at` AS `enabledAt`, `disabled_at` AS `disabledAt`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `workspace_solution_extension`;
DROP TABLE IF EXISTS `world_model_snapshot`;
DROP TABLE IF EXISTS `worldmodelsnapshot`;
RENAME TABLE `world_model_snapshot__new` TO `world_model_snapshot`;
CREATE OR REPLACE VIEW `worldmodelsnapshot` AS SELECT `legacy_id` AS `id`, `workspace_id` AS `workspaceId`, `runtime_session_id` AS `runtimeSessionId`, `meeting_id` AS `meetingId`, `opportunity_id` AS `opportunityId`, `company_id` AS `companyId`, `snapshot_key` AS `snapshotKey`, `summary` AS `summary`, `snapshot_json` AS `snapshotJson`, `create_time` AS `createdAt`, `modify_time` AS `updatedAt` FROM `world_model_snapshot`;
SET FOREIGN_KEY_CHECKS = 1;
