-- Member MCP P0: additive member AI-client access requests and supervisor grants; relationMode=prisma.
CREATE TABLE `MemberAgentConnection` (
 `id` VARCHAR(191) NOT NULL,
 `workspaceId` VARCHAR(191) NOT NULL,
 `userId` VARCHAR(191) NOT NULL,
 `membershipId` VARCHAR(191) NOT NULL,
 `clientType` VARCHAR(32) NOT NULL,
 `deviceLabel` VARCHAR(80) NOT NULL,
 `deviceRef` VARCHAR(191) NOT NULL,
 `scopesJson` TEXT NOT NULL,
 `status` VARCHAR(16) NOT NULL,
 `version` INTEGER NOT NULL DEFAULT 0,
 `requestedAt` DATETIME(3) NOT NULL,
 `decidedAt` DATETIME(3) NULL,
 `decidedByUserId` VARCHAR(191) NULL,
 `decisionReason` VARCHAR(200) NULL,
 `claimDeadlineAt` DATETIME(3) NULL,
 `tokenHash` CHAR(64) NULL,
 `tokenPrefix` VARCHAR(16) NULL,
 `issuedAt` DATETIME(3) NULL,
 `expiresAt` DATETIME(3) NULL,
 `revokedAt` DATETIME(3) NULL,
 `revokedByUserId` VARCHAR(191) NULL,
 `lastUsedAt` DATETIME(3) NULL,
 `lastClientName` VARCHAR(80) NULL,
 `lastClientVersion` VARCHAR(80) NULL,
 `lastFailureCode` VARCHAR(32) NULL,
 `rateWindowStartedAt` DATETIME(3) NULL,
 `rateWindowRequestCount` INTEGER NOT NULL DEFAULT 0,
 `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 `updatedAt` DATETIME(3) NOT NULL,
 UNIQUE INDEX `MemberAgentConnection_tokenHash_key` (`tokenHash`),
 UNIQUE INDEX `MemberAgentConnection_deviceRef_key` (`deviceRef`),
 INDEX `MemberAgentConnection_workspaceId_status_idx` (`workspaceId`, `status`),
 INDEX `MemberAgentConnection_workspaceId_userId_idx` (`workspaceId`, `userId`),
 PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `MemberAgentApproverGrant` (
 `id` VARCHAR(191) NOT NULL,
 `workspaceId` VARCHAR(191) NOT NULL,
 `approverUserId` VARCHAR(191) NOT NULL,
 `groupTag` VARCHAR(60) NOT NULL,
 `grantedByUserId` VARCHAR(191) NOT NULL,
 `grantedAt` DATETIME(3) NOT NULL,
 `revokedAt` DATETIME(3) NULL,
 `revokedByUserId` VARCHAR(191) NULL,
 `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 INDEX `MAApproverGrant_ws_approver_revoked_idx` (`workspaceId`, `approverUserId`, `revokedAt`),
 INDEX `MAApproverGrant_ws_group_revoked_idx` (`workspaceId`, `groupTag`, `revokedAt`),
 PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
