import type { PageReportingProtocol } from "@/lib/presentation/reporting-protocol";
import { formatSeededBusinessCopy } from "@/lib/presentation/seeded-business-copy";

const ROLE_DETAIL_ZH_REPLACEMENTS: Array<[RegExp, string]> = [
  [/阻碍/g, "阻塞"],
  [/first-loop/gi, "首轮闭环"],
  [/first loop/gi, "首轮闭环"],
  [/live signal/gi, "真实信号"],
  [/setup handoff/gi, "初始化交接"],
  [/review-before-commitment/gi, "承诺前复核"],
  [/\bWAITING_THEM\b/g, "等待对方"],
  [/\bADVANCING\b/g, "推进中"],
  [/\bINTERNAL_SYNC\b/g, "需内部协同"],
  [/\bNEW\b/g, "新机会"],
  [/\bCONTACTED\b/g, "已接触"],
  [/\bDONE\b/g, "已完成"],
  [/\bLOST\b/g, "已结束"],
  [/\bLOW\b/g, "低风险"],
  [/\bMEDIUM\b/g, "中风险"],
  [/\bHIGH\b/g, "高风险"],
  [/\bCRITICAL\b/g, "关键风险"],
  [/meeting chain detail/gi, "会议链路详情"],
  [/meeting chain/gi, "会议链路"],
  [/meeting follow-through/gi, "会议后续推进"],
  [/meeting review/gi, "会议复核"],
  [/meeting evidence/gi, "会议依据"],
  [/meeting memory/gi, "会议记忆"],
  [/meeting detail/gi, "会议详情"],
  [/delivery review detail/gi, "交付复核详情"],
  [/delivery review/gi, "交付复核"],
  [/delivery walkthrough detail/gi, "交付走查详情"],
  [/delivery walkthrough/gi, "交付走查"],
  [/review route/gi, "复核路径"],
  [/walkthrough route/gi, "走查路径"],
  [/contact detail/gi, "联系人详情"],
  [/company detail/gi, "公司详情"],
  [/conversation detail/gi, "沟通详情"],
  [/account-routing/gi, "账户路由"],
  [/account routing/gi, "账户路由"],
  [/account route/gi, "账户路由"],
  [/account memory/gi, "账户记忆"],
  [/contact handoff/gi, "联系人交接"],
  [/contact owner/gi, "联系人负责人"],
  [/contact path/gi, "联系人路径"],
  [/commercial follow-through/gi, "商业后续推进"],
  [/commercial motion/gi, "商业推进"],
  [/live opportunity/gi, "活跃机会"],
  [/live commercial thread/gi, "活跃商业线程"],
  [/preparation mode/gi, "准备态"],
  [/generic notes/gi, "泛化记录"],
  [/internal preparation/gi, "内部准备"],
  [/customer-facing momentum/gi, "面向客户的推进"],
  [/customer-facing certainty/gi, "面向客户的确定性"],
  [/inbox detail/gi, "收件箱详情"],
  [/thread judgement/gi, "线程判断"],
  [/thread summary/gi, "线程摘要"],
  [/thread pressure/gi, "线程压力"],
  [/counterpart context/gi, "对方上下文"],
  [/package clarification/gi, "方案包澄清"],
  [/proposal boundary clarification/gi, "方案边界澄清"],
  [/boundary clarification/gi, "边界澄清"],
  [/conversation handoff/gi, "沟通交接"],
  [/reply pressure/gi, "回复压力"],
  [/reply-safe wording/gi, "可回复措辞"],
  [/sales worker output/gi, "销售协作者产出"],
  [/delivery worker output/gi, "交付协作者产出"],
  [/founder worker output/gi, "创始人协作者产出"],
  [/worker output/gi, "协作产出"],
  [/boundary trace/gi, "边界记录"],
  [/sendability trace/gi, "发送边界记录"],
  [/handoff trace/gi, "交接记录"],
  [/historical changes/gi, "历史变化"],
  [/conversation layer/gi, "沟通层"],
  [/role-safe/gi, "角色安全"],
  [/proposal shaping review/gi, "方案成形复核"],
  [/raw messages/gi, "原始消息"],
  [/raw message/gi, "原始消息"],
  [/raw mail history/gi, "原始邮件历史"],
  [/founder framing/gi, "创始人口径"],
  [/delivery clarification/gi, "交付澄清"],
  [/shared review/gi, "共同复核"],
  [/primary owner/gi, "主要负责人"],
  [/suggested owner/gi, "建议接手人"],
  [/commitment reinforcement/gi, "承诺强化"],
  [/reinforcement variants/gi, "强化版本"],
  [/reinforcement variant/gi, "强化版本"],
  [/reinforcement level/gi, "强化级别"],
  [/reinforcement trace/gi, "强化记录"],
  [/customer-visible strengthening/gi, "客户可见强化"],
  [/customer-visible reinforcement/gi, "客户可见强化"],
  [/boundary-only reinforcement/gi, "仅带边界强化"],
  [/internal-reinforcement-only/gi, "仅内部强化"],
  [/internal reinforcement only/gi, "仅内部强化"],
  [/reinforcement-after-review/gi, "复核后再强化"],
  [/reinforcement after review/gi, "复核后再强化"],
  [/reinforcement-after-risk-reduction/gi, "降风险后再强化"],
  [/reinforcement after risk reduction/gi, "降风险后再强化"],
  [/reinforcement-blocked/gi, "强化被阻断"],
  [/reinforcement blocked/gi, "强化被阻断"],
  [/reinforcement-deferred/gi, "强化延后"],
  [/reinforcement deferred/gi, "强化延后"],
  [/no-reinforcement/gi, "暂不强化"],
  [/no reinforcement/gi, "暂不强化"],
  [/internal-only wording/gi, "仅内部措辞"],
  [/promise line/gi, "承诺线"],
  [/promise-bearing language/gi, "带承诺意味的语言"],
  [/boundary note/gi, "边界说明"],
  [/dependency note/gi, "依赖说明"],
  [/risk note/gi, "风险说明"],
  [/trust pressure/gi, "信任压力"],
  [/safe-with-risk-note/gi, "带风险说明后外发"],
  [/safe with risk note/gi, "带风险说明后外发"],
  [
    /Helm v2 ingested ([^.。]+) into the meeting-to-action runtime\./gi,
    "会议推进链路已接入：$1。",
  ],
  [/NEXT ACTION/g, "下一步动作"],
  [/AUDIENCE/g, "受众"],
  [/ATTENTION/g, "注意事项"],
  [/Customer success handoff/gi, "客户成功接手"],
  [/customer success handoff/gi, "客户成功接手"],
  [/\bDRAFT_EXTERNAL_EMAIL\b/g, "起草外发邮件"],
  [/\bDRAFT_INTERNAL_NOTE\b/g, "起草内部纪要"],
  [/\bCREATE_MEETING\b/g, "创建会议"],
  [/\bUPDATE_OPPORTUNITY_STAGE\b/g, "更新机会阶段"],
  [/\bCREATE_TASK\b/g, "创建待办"],
  [/\bASSIGN_OWNER\b/g, "指派负责人"],
  [/\bCHANGE_DUE_DATE\b/g, "修改截止时间"],
  [/\bSEND_MEETING_SUMMARY\b/g, "归档会议纪要"],
  [/\bGENERATE_REPLY_DRAFT\b/g, "生成回复草稿"],
  [/\bSCHEDULE_INTERVIEW\b/g, "安排面试"],
  [/customer-facing with internal review/gi, "对外表达 + 内部复核"],
  [/customer-facing-with-boundary/gi, "面向客户但必须带边界"],
  [/customer-visible-with-boundary/gi, "客户可见但必须带边界"],
  [/customer-facing offer/gi, "面向客户报价"],
  [/customer-facing/gi, "面向客户"],
  [/customer-visible/gi, "客户可见"],
  [/Customer success/gi, "客户成功"],
  [/customer success/gi, "客户成功"],
  [/Review request detail/gi, "复核请求详情"],
  [/review request detail/gi, "复核请求详情"],
  [/Review request/gi, "复核请求"],
  [/review request/gi, "复核请求"],
  [/Expansion review/gi, "扩展复盘"],
  [/expansion review/gi, "扩展复盘"],
  [/Commercial review/gi, "商业复核"],
  [/commercial review/gi, "商业复核"],
  [/Success check/gi, "成功复盘"],
  [/success check/gi, "成功复盘"],
  [/follow-up drafting/gi, "跟进草稿整理"],
  [/follow-up detail/gi, "跟进详情"],
  [/follow-up copy pressure/gi, "跟进措辞压力"],
  [/draft pressure/gi, "草稿压力"],
  [/draft-only/gi, "仅草稿"],
  [/discussion-only/gi, "仅讨论"],
  [/recommendation-only/gi, "仅建议"],
  [/package boundary/gi, "方案包边界"],
  [/contract promise/gi, "合同承诺"],
  [/send-ready review surface/gi, "可发送复核面"],
  [/review-sensitive/gi, "复核敏感"],
  [/Review-limited/gi, "复核受限"],
  [/review-limited/gi, "复核受限"],
  [/review-before-send/gi, "发送前复核"],
  [/review before send/gi, "发送前复核"],
  [/review-needed/gi, "需要复核"],
  [/review gate/gi, "复核关口"],
  [/send gate/gi, "发送关口"],
  [/Review posture/gi, "复核状态"],
  [/review posture/gi, "复核状态"],
  [/Review outcome/gi, "复核结果"],
  [/review outcome/gi, "复核结果"],
  [/review pressure/gi, "复核压力"],
  [/review trace/gi, "复核记录"],
  [/review line/gi, "复核线"],
  [/approval-sensitive/gi, "审批敏感"],
  [/approval request/gi, "审批请求"],
  [/approval evidence/gi, "审批依据"],
  [/approver context/gi, "审批人上下文"],
  [/approval history/gi, "审批历史"],
  [/approval/gi, "审批"],
  [/approver/gi, "审批人"],
  [/reviewer provenance/gi, "复核来源"],
  [/human reviewer/gi, "人工复核人"],
  [/reviewer/gi, "复核人"],
  [/revision request/gi, "修订请求"],
  [/result preview/gi, "结果预览"],
  [/raw request payloads/gi, "原始请求资料"],
  [/raw payloads/gi, "原始资料"],
  [/raw payload/gi, "原始资料"],
  [/request payload/gi, "请求资料"],
  [/payload/gi, "资料"],
  [/boundary-first/gi, "边界优先"],
  [/editable draft note/gi, "可编辑草稿说明"],
  [/blocked review rationale/gi, "被拦截复核理由"],
  [/safe send/gi, "安全发送"],
  [/safe-with-boundary/gi, "带边界可外发"],
  [/safe_to_send/gi, "可安全外发"],
  [/safe_with_boundary/gi, "带边界可外发"],
  [/safe_with_prerequisite/gi, "补前置条件后外发"],
  [/safe_with_dependency/gi, "带依赖后外发"],
  [/not_safe_to_send/gi, "当前不能外发"],
  [/safe-to-send/gi, "可安全外发"],
  [/not-safe-to-send/gi, "当前不能外发"],
  [/human-review-required/gi, "需要人工复核"],
  [/external draft/gi, "对外草稿"],
  [/external-safe proposal/gi, "对外安全方案"],
  [/external proposal/gi, "对外方案"],
  [/external narrative/gi, "对外叙事"],
  [/external-safe/gi, "对外安全"],
  [/sendability/gi, "发送边界"],
  [/safe to send/gi, "可安全外发"],
  [/not safe to send/gi, "当前不能外发"],
  [/non-commitment/gi, "非承诺"],
  [/internal-only/gi, "仅内部"],
  [/internal review/gi, "内部复核"],
  [/internal note/gi, "内部说明"],
  [/internal prep/gi, "内部准备"],
  [/boundary-limited/gi, "边界受限"],
  [/recommendation facts/gi, "建议事实"],
  [/recommendation fact/gi, "建议事实"],
  [/\brecommendations\b/gi, "建议"],
  [/\brecommendation\b/gi, "建议"],
  [/next actions/gi, "下一步动作"],
  [/next action/gi, "下一步动作"],
  [/action items/gi, "动作项"],
  [/action item/gi, "动作项"],
  [/recommended next move/gi, "建议下一步"],
  [/next-step/gi, "下一步"],
  [/\bnext move\b/gi, "下一步动作"],
  [/\bmove\b/gi, "动作"],
  [/follow-through/gi, "推进"],
  [/follow-up/gi, "跟进"],
  [/\bmaterials?\b/gi, "材料"],
  [/readiness/gi, "就绪判断"],
  [/blocker pressure/gi, "阻塞压力"],
  [/\bblockers\b/gi, "阻塞"],
  [/\bblocker\b/gi, "阻塞"],
  [/当前\s*阻塞/g, "当前卡点"],
  [/\bcommitments\b/gi, "承诺"],
  [/\bcommitment\b/gi, "承诺"],
  [/memory facts/gi, "记忆事实"],
  [/memory fact/gi, "记忆事实"],
  [/\bmemory\b/gi, "记忆"],
  [/\bbriefing\b/gi, "简报"],
  [/\bbrief\b/gi, "简报"],
  [/\breplay\b/gi, "回放"],
  [/\baudit\b/gi, "审计"],
  [/\btrace\b/gi, "记录"],
  [/\btraces\b/gi, "记录"],
  [/\breview\b/gi, "复核"],
  [/\bboundary\b/gi, "边界"],
  [/\bdependency\b/gi, "依赖"],
  [/\bdependencies\b/gi, "依赖"],
  [/\bprerequisite\b/gi, "前置条件"],
  [/\bqueue\b/gi, "队列"],
  [/\binbox\b/gi, "收件箱"],
  [/\bhandoff\b/gi, "交接"],
  [/\bdetail\b/gi, "详情"],
  [/\bsurface\b/gi, "页面"],
  [/\bbundle\b/gi, "依据包"],
  [/\bpackage\b/gi, "方案包"],
  [/package variants/gi, "方案包版本"],
  [/package variant/gi, "方案包版本"],
  [/package stage/gi, "方案包阶段"],
  [/\bproposal\b/gi, "方案"],
  [/\boffer\b/gi, "报价"],
  [/\bdraft\b/gi, "草稿"],
  [/\bissue\b/gi, "问题"],
  [/\bescalation\b/gi, "升级处理"],
  [/\bpolicy\b/gi, "治理边界"],
  [/\bauthority\b/gi, "授权边界"],
  [/\bplaybook\b/gi, "处理方式"],
  [/\bposture\b/gi, "状态"],
  [/\bpressure\b/gi, "压力"],
  [/\bartifact\b/gi, "记录产物"],
  [/\bcanonical\b/gi, "正式"],
  [/\bworkflow\b/gi, "流程"],
  [/\bconnector\b/gi, "连接器"],
  [/\bwarmup\b/gi, "预热"],
  [/sales worker/gi, "销售协作者"],
  [/delivery worker/gi, "交付协作者"],
  [/founder worker/gi, "创始人协作者"],
  [/\bworker\b/gi, "协作者"],
  [/\bpack\b/gi, "依据包"],
  [/\bscenario\b/gi, "场景"],
  [/\bscene\b/gi, "场景"],
  [/\bmode\b/gi, "模式"],
  [/\blevel\b/gi, "级别"],
  [/\bintent\b/gi, "意图"],
  [/\bstage\b/gi, "阶段"],
  [/\bjudgement\b/gi, "判断"],
  [/\bvariant\b/gi, "版本"],
  [/\bvariants\b/gi, "版本"],
  [/\bcue\b/gi, "提示"],
  [/\bframing\b/gi, "表达框架"],
  [/\bwording\b/gi, "措辞"],
  [/\bnarrative\b/gi, "叙事"],
  [/\bshaping\b/gi, "成形判断"],
  [/\breinforcement\b/gi, "强化表达"],
  [/\bstrengthening\b/gi, "强化表达"],
  [/\bfallback\b/gi, "回退口径"],
  [/\boutward\b/gi, "对外"],
  [/\bexternal\b/gi, "对外"],
  [/\binternal\b/gi, "内部"],
  [/\bsendable\b/gi, "可发送"],
  [/\bsend-ready\b/gi, "可发送"],
  [/\bpromise\b/gi, "承诺"],
  [/\bcertainty\b/gi, "确定性"],
  [/\bpricing\b/gi, "价格"],
  [/\bprice\b/gi, "价格"],
  [/\bscope\b/gi, "范围"],
  [/\btiming\b/gi, "时点"],
  [/\btrust\b/gi, "信任"],
  [/\bstory\b/gi, "叙事"],
  [/talk track/gi, "沟通口径"],
  [/live conversation/gi, "现场对话"],
  [/\bcopy\b/gi, "文案"],
  [/\bguidance\b/gi, "指引"],
  [/\bdiscussion\b/gi, "讨论"],
  [/\bexploratory\b/gi, "探索"],
  [/\bpilot\b/gi, "试点"],
  [/\blight\b/gi, "轻量"],
  [/\bstructured\b/gi, "结构化"],
  [/\bwalkthrough\b/gi, "讲解"],
  [/\bobjection\b/gi, "异议"],
  [/\bdemo\b/gi, "演示"],
  [/\bsuccess\b/gi, "客户成功"],
  [/first-contact/gi, "首次接触"],
  [/post-demo/gi, "演示后"],
  [/\bask\b/gi, "请求"],
  [/\bgate\b/gi, "关口"],
  [/\bnote\b/gi, "说明"],
  [/\bowner\b/gi, "负责人"],
  [/\bfounder\b/gi, "创始人"],
  [/\bsales\b/gi, "销售"],
  [/\bdelivery\b/gi, "交付"],
  [/\boperator\b/gi, "操作人"],
  [/\btoday focus\b/gi, "今日焦点"],
  [/\bbacking\b/gi, "支持"],
  [/\bactive\b/gi, "活跃"],
  [/跟进 邮件/g, "跟进邮件"],
  [/跟进 材料/g, "跟进材料"],
];

export function formatRoleDetailDisplayText(
  value: string | null | undefined,
  english: boolean,
) {
  if (!value) return "";
  if (english) return value;

  const source = extractReadableSummary(value);
  const seededSource = formatSeededBusinessCopy(source, english);

  const formatted = ROLE_DETAIL_ZH_REPLACEMENTS.reduce(
    (current, [pattern, replacement]) => current.replace(pattern, replacement),
    seededSource,
  );

  return formatSeededBusinessCopy(formatted, english).trim();
}

function extractReadableSummary(value: string) {
  const trimmed = value.trim();
  if (!trimmed.startsWith("{")) return value;
  const summaryMatch = trimmed.match(/"summary"\s*:\s*"([^"]+)/);
  if (summaryMatch?.[1]?.trim()) {
    return summaryMatch[1];
  }

  try {
    const parsed = JSON.parse(trimmed) as {
      summary?: unknown;
      recommendedNextSteps?: unknown;
    };
    if (typeof parsed.summary === "string" && parsed.summary.trim()) {
      return parsed.summary;
    }

    if (Array.isArray(parsed.recommendedNextSteps)) {
      const firstStep = parsed.recommendedNextSteps.find(
        (item): item is string =>
          typeof item === "string" && item.trim().length > 0,
      );
      if (firstStep) return firstStep;
    }
  } catch {
    return value;
  }

  return value;
}

export function formatRoleDetailDisplayItems(
  values: string[],
  english: boolean,
) {
  return values.map((value) => formatRoleDetailDisplayText(value, english));
}

export function formatRoleDetailPageProtocol(
  protocol: PageReportingProtocol,
  english: boolean,
): PageReportingProtocol {
  if (english) return protocol;

  return {
    ...protocol,
    pageJudgement: formatRoleDetailDisplayText(protocol.pageJudgement, english),
    pageJudgementReason: formatRoleDetailDisplayText(
      protocol.pageJudgementReason,
      english,
    ),
    pageWhyItMatters: formatRoleDetailDisplayItems(
      protocol.pageWhyItMatters,
      english,
    ),
    pageActionSummary: formatRoleDetailDisplayItems(
      protocol.pageActionSummary,
      english,
    ),
    pageDecisionRequest: formatRoleDetailDisplayItems(
      protocol.pageDecisionRequest,
      english,
    ),
    pageNextAction: protocol.pageNextAction.map((action) => ({
      ...action,
      label: formatRoleDetailDisplayText(action.label, english),
    })),
    pageBoundarySummary: formatRoleDetailDisplayItems(
      protocol.pageBoundarySummary,
      english,
    ),
    pageEvidenceSummary: formatRoleDetailDisplayItems(
      protocol.pageEvidenceSummary,
      english,
    ),
    pageWorkerSummary: formatRoleDetailDisplayItems(
      protocol.pageWorkerSummary,
      english,
    ),
    pageWorkerAssignments: protocol.pageWorkerAssignments?.map(
      (assignment) => ({
        ...assignment,
        title: formatRoleDetailDisplayText(assignment.title, english),
        summary: formatRoleDetailDisplayText(assignment.summary, english),
        items: formatRoleDetailDisplayItems(assignment.items, english),
        chips: assignment.chips
          ? formatRoleDetailDisplayItems(assignment.chips, english)
          : assignment.chips,
      }),
    ),
    pageEscalationHint: protocol.pageEscalationHint
      ? formatRoleDetailDisplayText(protocol.pageEscalationHint, english)
      : protocol.pageEscalationHint,
    pagePrioritySignal: protocol.pagePrioritySignal
      ? formatRoleDetailDisplayText(protocol.pagePrioritySignal, english)
      : protocol.pagePrioritySignal,
    pageEvidenceLinks: protocol.pageEvidenceLinks?.map((link) => ({
      ...link,
      label: formatRoleDetailDisplayText(link.label, english),
    })),
    pageEvidenceGroups: protocol.pageEvidenceGroups?.map((group) => ({
      ...group,
      label: formatRoleDetailDisplayText(group.label, english),
      items: group.items.map((item) =>
        typeof item === "string"
          ? formatRoleDetailDisplayText(item, english)
          : {
              ...item,
              label: formatRoleDetailDisplayText(item.label, english),
              summary: item.summary
                ? formatRoleDetailDisplayText(item.summary, english)
                : item.summary,
            },
      ),
    })),
  };
}

export function formatRoleDetailEvidenceGroups<
  Group extends { label: string; items: string[] },
>(groups: Group[], english: boolean): Group[] {
  if (english) return groups;

  return groups.map((group) => ({
    ...group,
    label: formatRoleDetailDisplayText(group.label, english),
    items: formatRoleDetailDisplayItems(group.items, english),
  }));
}
