/**
 * Source Profiler — overlay draft builder.
 *
 * Builds a user-private deployment-code draft for the helm-overlays repo from a
 * ReviewPacket. The draft is a set of skeletons/scaffolds + candidate mappings +
 * a review doc. It NEVER contains secrets, connection strings, production URLs,
 * raw payloads, or auto-writeback, and it never enables a connector
 * (ConnectorDraft.activated is always false). Generation is defensively
 * sanitized: any secret-looking content throws.
 */

import type { ReviewPacket } from "../contract/review-packet";
import type {
  OverlayFileDraft,
  OverlayPatchDraft,
  ConnectorDraft,
} from "../contract/overlay";
import { overlayPatchDraftSchema } from "../contract/overlay";
import { scanContentForSecrets } from "../profiler/secret-preflight";

export type BuildOverlayDraftInput = {
  packet: ReviewPacket;
  tenantKey: string;
  extensionSlug: string;
  overlayRoot: string;
};

export function buildOverlayDraft(input: BuildOverlayDraftInput): OverlayPatchDraft {
  const { packet, tenantKey, extensionSlug, overlayRoot } = input;
  const baseDir = `tenants/${tenantKey}/extensions/${extensionSlug}`;

  const candidates = packet.candidates;
  const files: OverlayFileDraft[] = [
    {
      path: `${baseDir}/extension.manifest.json`,
      intent: "extension_manifest_patch",
      content: manifestPatch(extensionSlug, candidates.length),
    },
    {
      path: `${baseDir}/adapter.readonly.ts`,
      intent: "readonly_adapter_skeleton",
      content: adapterSkeleton(extensionSlug),
    },
    {
      path: `${baseDir}/mapping-candidates.json`,
      intent: "mapping_candidates",
      content: `${JSON.stringify(candidates, null, 2)}\n`,
    },
    {
      path: `${baseDir}/REVIEW_PACKET.md`,
      intent: "review_packet_doc",
      content: reviewDoc(packet),
    },
    {
      path: `${baseDir}/adapter.readonly.test.ts`,
      intent: "synthetic_test",
      content: syntheticTest(extensionSlug),
    },
  ];

  for (const file of files) {
    const findings = scanContentForSecrets(file.content);
    if (findings.length > 0) {
      throw new Error(
        `overlay draft content failed sanitization (${file.path}): ${findings
          .map((f) => f.rule)
          .join(", ")}`,
      );
    }
  }

  const connectorDraft: ConnectorDraft = {
    extensionSlug,
    posture: "read_only",
    candidates,
    activated: false,
  };

  return overlayPatchDraftSchema.parse({
    schemaVersion: "helm.source-profiler.overlay-draft.v1",
    tenantKey,
    extensionSlug,
    overlayRoot,
    files,
    connectorDraft,
    materialized: false,
  });
}

function manifestPatch(slug: string, candidateCount: number): string {
  return `${JSON.stringify(
    {
      slug,
      posture: "read_only",
      status: "draft",
      generatedBy: "source-profiler",
      candidateCount,
      activated: false,
      notes: "Draft only. Review candidates, then a human builds the real adapter.",
    },
    null,
    2,
  )}\n`;
}

function adapterSkeleton(slug: string): string {
  return `/**
 * Read-only adapter skeleton for "${slug}" (DRAFT — generated by source-profiler).
 *
 * This is a scaffold, not a working connector. Fill in the mapping using the
 * reviewed candidates in mapping-candidates.json. Hard rules:
 *   - read-only: no external writes, no auto-send, no auto-approve
 *   - no secrets / connection strings / production URLs in this file
 *   - credentials come from the deployment's secret store, never inline
 */

export type ReadonlyAdapter = {
  readonly slug: string;
  /** TODO: implement read-only extraction against reviewed mappings. */
  describe(): { slug: string; posture: "read_only" };
};

export const adapter: ReadonlyAdapter = {
  slug: ${JSON.stringify(slug)},
  describe() {
    return { slug: ${JSON.stringify(slug)}, posture: "read_only" };
  },
};
`;
}

function syntheticTest(slug: string): string {
  return `import { describe, it, expect } from "vitest";
import { adapter } from "./adapter.readonly";

// Synthetic test scaffold for "${slug}" (DRAFT). Replace with real coverage.
describe("${slug} read-only adapter (draft)", () => {
  it("declares a read-only posture", () => {
    expect(adapter.describe().posture).toBe("read_only");
  });
});
`;
}

function reviewDoc(packet: ReviewPacket): string {
  const lines: string[] = [
    `# Review Packet — overlay draft`,
    ``,
    `> Sensitivity: ${packet.sensitivity}. User-private; do not share without redaction.`,
    ``,
    `- Objects discovered: ${packet.codeScan.objects.length}`,
    `- Mapping candidates: ${packet.candidates.length}`,
    ``,
    `## Candidates (review & decide)`,
    ``,
    `| source object | → entity | signal family | confidence | state |`,
    `| --- | --- | --- | --- | --- |`,
  ];
  for (const c of [...packet.candidates].sort((a, b) => b.confidence - a.confidence)) {
    lines.push(
      `| ${c.sourceObjectId} | ${c.targetEntity} | ${c.signalFamily} | ${c.confidence} | ${c.state} |`,
    );
  }
  lines.push(
    ``,
    `All candidates start as \`candidate\`. A human must accept/reject each before`,
    `any of them informs a real connector. This draft activates nothing.`,
    ``,
  );
  return lines.join("\n");
}
