import { formatSeededBusinessCopy } from "@/lib/presentation/seeded-business-copy";

const CHINESE_FRONTSTAGE_REPLACEMENTS: Array<[RegExp, string]> = [
  [
    /Helm v2 ingested ([^.。]+) into the meeting-to-action runtime\./gi,
    "会议推进链路已接入：$1。",
  ],
  [/HELM V2 MEETING RUNTIME INGESTED/gi, "会议运行记录已接入"],
  [/结构化方案/g, "清晰方案"],
  [/结构化 跟进/g, "清晰跟进"],
  [/结构化跟进/g, "清晰跟进"],
  [/结构化记忆/g, "可复用记忆"],
  [/结构化事实/g, "可复用事实"],
  [/结构化/g, "可复用"],
  [/review-before-send/gi, "发送前复核"],
  [/Created auth session for ([^\s]+)/gi, "已创建演示会话：$1"],
  [/AUTH_SESSION_CREATED/g, "会话已创建"],
  [/AUTH SESSION/gi, "认证会话"],
  [/SYSTEM INFERENCE/gi, "系统推断"],
  [/Adaptive Evolution/gi, "自适应演进"],
  [/SkillSuggestion/g, "能力建议"],
  [/PreferenceSignal/g, "偏好信号"],
  [/PREFERENCE SIGNAL/g, "偏好信号"],
  [/FROM PATTERN/g, "来自模式沉淀"],
  [/\bSUGGESTION\b/g, "建议"],
  [/\bSTRATEGY\b/g, "策略"],
  [/\bPREFERENCE\b/g, "偏好"],
  [/\bSIGNAL\b/g, "信号"],
  [/\bPATTERN\b/g, "模式"],
  [/\bby\b/gi, "由"],
  [/\bACTIVE\b/g, "有效"],
  [/AuthSession/g, "认证会话"],
  [/formal review/gi, "正式复核"],
  [/review-safe/gi, "复核后可复用"],
  [/review-only/gi, "仅复核"],
  [/review posture/gi, "复核姿态"],
  [/review boundary/gi, "复核边界"],
  [/behind review/gi, "复核后面"],
  [/trusted runtime state/gi, "已确认运行状态"],
  [/runtime context/gi, "运行上下文"],
  [/runtime state/gi, "运行状态"],
  [/runtime/gi, "运行层"],
  [/operating context/gi, "运营上下文"],
  [/operating state/gi, "运营状态"],
  [/operating memory/gi, "运营记忆"],
  [/reflection carry-forward candidates?/gi, "复盘延续候选"],
  [/carry-forward candidates?/gi, "延续候选"],
  [/reflection 延续 candidates?/gi, "复盘延续候选"],
  [/延续 candidates?/gi, "延续候选"],
  [/延续(?!候选)/gi, "延续复用"],
  [/canonical truth/gi, "正式记忆"],
  [/customer-facing/gi, "面向客户"],
  [/customer-visible/gi, "客户可见"],
  [/customer success/gi, "客户成功"],
  [/\bfollow-up\b/gi, "跟进"],
  [/follow-through/gi, "后续动作"],
  [/resource conflict/gi, "资源冲突"],
  [/\baction items\b/gi, "动作项"],
  [/\baction item\b/gi, "动作项"],
  [/source-use/gi, "来源使用"],
  [/object-state/gi, "对象状态"],
  [/non-commitment/gi, "非承诺边界"],
  [/\brecommendations\b/gi, "判断建议"],
  [/\brecommendation\b/gi, "判断建议"],
  [/\bblockers\b/gi, "阻塞"],
  [/\bblocker\b/gi, "阻塞"],
  [/\bcommitments\b/gi, "承诺"],
  [/\bcommitment\b/gi, "承诺"],
  [/\bworkflow\b/gi, "工作回路"],
  [/\bworker\b/gi, "协作者"],
  [/\bskill\b/gi, "能力"],
  [/\boperator\b/gi, "操作人"],
  [/\bqueue\b/gi, "待处理队列"],
  [/\bhandoff\b/gi, "交接"],
  [/\bactionability\b/gi, "可行动性"],
  [/\btelemetry\b/gi, "使用信号"],
  [/\bprompt\b/gi, "提示词"],
  [/\bflow\b/gi, "流转"],
  [/\breplay\b/gi, "回放"],
  [/\breview\b/gi, "复核"],
  [/\bproposal\b/gi, "方案"],
  [/\bpackage\b/gi, "打包方案"],
  [/\bpipeline\b/gi, "推进管线"],
  [/\bwording\b/gi, "措辞"],
  [/\bgrounded\b/gi, "依据明确"],
  [/\bgenerated\b/gi, "已生成"],
  [/\bcreated\b/gi, "已创建"],
  [/\bupdated\b/gi, "已更新"],
  [/\bprocessed\b/gi, "已处理"],
  [/\bcompleted\b/gi, "已完成"],
  [/\bfailed\b/gi, "失败"],
  [/\bstarted\b/gi, "已开始"],
  [/\bstopped\b/gi, "已停止"],
  [/\bapproved\b/gi, "已批准"],
  [/\brejected\b/gi, "已拒绝"],
  [/\bconverted\b/gi, "已转换"],
  [/\bmanual\b/gi, "人工处理"],
];

const CHINESE_EXACT_FRONTSTAGE_LABELS: Record<string, string> = {
  ACTION_EXECUTED: "动作已执行",
  AI_GENERATED_ACTION: "生成动作建议",
  AI_GENERATED_COMPANY_BRIEF: "生成公司简报",
  AI_SUGGESTED_ACTIONS: "生成下一步建议",
  APPROVAL_APPROVED: "复核已批准",
  APPROVAL_CONVERTED_TO_MANUAL: "已转人工处理",
  APPROVAL_REJECTED: "复核已拒绝",
  AUTO_EXECUTED_ACTION: "自动处理动作",
  BLOCKER_CREATED: "新增阻塞",
  BRIEFING_SNAPSHOT_GENERATED: "生成简报快照",
  CAPTURE_STARTED: "开始记录",
  CAPTURE_STOPPED: "停止记录",
  COMPANY: "公司",
  CONTACT: "联系人",
  CONVERSATION_CAPTURE_FAILED: "会话记录处理失败",
  CONVERSATION_CAPTURE_PROCESSED: "会话记录已处理",
  CRM_IMPORT_COMPLETED: "客户关系系统导入已完成",
  IMPORT_CONFLICT_RESOLVED: "导入冲突已解决",
  IMPORT_SOURCE_CONNECTED: "导入来源已连接",
  IMPORT_SOURCE_DISCONNECTED: "导入来源已断开",
  IMPORT_WARMUP_COMPLETED: "导入预热已完成",
  HELM_V2_MEETING_RUNTIME_INGESTED: "会议运行记录已接入",
  MEETING: "会议",
  MEETING_ACTION_ITEMS_GENERATED: "生成会议后续动作",
  MEMORY_CORRECTED: "记忆已修正",
  MEMORY_DELETED: "记忆已删除",
  MEMORY_FACT_CONFIRMED: "记忆事实已确认",
  MEMORY_FACT_CORRECTED: "记忆事实已修正",
  MEMORY_FACT_CREATED: "新增记忆事实",
  MEMORY_FACT_DELETED: "记忆事实已删除",
  MEMORY_FACT_INVALIDATED: "记忆事实已失效",
  CONTENT_UPDATE: "内容更新",
  OBJECT_REBIND: "对象重新关联",
  SOURCE_REBIND: "来源重新关联",
  CONFIRM: "已确认",
  INVALIDATE: "已失效",
  DELETE: "已删除",
  MEMORY_SUMMARY_EXPORTED: "记忆摘要已导出",
  OPPORTUNITY: "机会",
  OPPORTUNITY_DUE_DATE_CHANGED: "机会日期已调整",
  OPPORTUNITY_NEXT_ACTION_UPDATED: "机会下一步已更新",
  OPPORTUNITY_STAGE_CHANGED: "机会阶段已更新",
  POLICY_AUTO_EXECUTE_ENABLED: "后续同类动作可自动处理",
  RECOMMENDATION_ACTION_CREATED: "生成待复核动作",
  RECOMMENDATION_FEEDBACK_SUBMITTED: "提交判断反馈",
  RECOMMENDATION_GENERATED: "生成判断建议",
  THREAD_LINKED_TO_OPPORTUNITY: "会话已关联机会",
  WEEKLY_REPORT_GENERATED: "生成周报",
  SUGGESTION: "建议",
  STRATEGY: "策略",
  PREFERENCE: "偏好",
  SIGNAL: "信号",
  FROM: "来自",
  PATTERN: "模式",
};

const CHINESE_STATUS_REPLACEMENTS: Record<string, string> = {
  VERIFIED: "待复核",
  PROMOTED: "已提升",
  REJECTED: "已忽略",
  ACTIVE: "有效",
  OPEN: "未完成",
  IN_PROGRESS: "推进中",
  FULFILLED: "已兑现",
  CANCELED: "已取消",
  RESOLVED: "已解决",
  MONITORING: "观察中",
  IGNORED: "暂不处理",
  INVALID: "已失效",
};

export function formatMemoryVisibleText(
  value: string | null | undefined,
  english: boolean,
) {
  if (!value) return "";
  if (english) return value;
  const exactLabel = CHINESE_EXACT_FRONTSTAGE_LABELS[value.trim()];
  if (exactLabel) return exactLabel;

  const formatted = CHINESE_FRONTSTAGE_REPLACEMENTS.reduce(
    (current, [pattern, replacement]) => current.replace(pattern, replacement),
    value.replace(/_/g, " "),
  );

  return formatSeededBusinessCopy(formatted, english);
}

export function formatMemoryVisibleStatus(
  value: string | null | undefined,
  english: boolean,
) {
  if (!value) return "";
  if (english) return value;

  return (
    CHINESE_STATUS_REPLACEMENTS[value] ??
    formatMemoryVisibleText(value, english)
  );
}
