import {afterEach,describe,expect,it,vi} from "vitest";
import {createServerBootstrapInitializer} from "./server-bootstrap";
const binding=(mode="required")=>({schema:"helm.server-bootstrap-binding/v1",mode,bootstrapVersion:"helm.server-bootstrap/v1"});
const contribution=()=>undefined;
const bootstrapNamespace=(mode="required",run=async()=>undefined)=>({registerAllPacks:contribution,serverBootstrapVersion:"helm.server-bootstrap/v1",serverBootstrapMode:mode,registerServerBootstrap:run});
afterEach(()=>vi.useRealTimers());
describe("versioned server startup admission, not payment authority",()=>{
 it("awaits and initializes the same bound source once",async()=>{let count=0;let release!:()=>void;const load=async()=>bootstrapNamespace("required",()=>new Promise<void>(r=>{count++;release=r;}));const start=createServerBootstrapInitializer(binding(),load);const one=start(),two=start();expect(one).toBe(two);await Promise.resolve();expect(count).toBe(1);release();expect(await one).toEqual({mode:"required",status:"initialized"});await start();expect(count).toBe(1);});
 it("keeps absent legacy aggregator compatible",async()=>{expect(await createServerBootstrapInitializer(binding("legacy-optional"),async()=>{throw new Error("reserved absence")})()).toEqual({mode:"legacy-optional",status:"legacy-core-only"});});
 it("keeps old synchronous registration and observes a new versioned optional export",async()=>{let registered=0,installed=0;const legacy=createServerBootstrapInitializer(binding("legacy-optional"),async()=>({registerAllPacks:()=>{registered++;}}));expect((await legacy()).status).toBe("legacy-registered");const versioned=createServerBootstrapInitializer(binding("legacy-optional"),async()=>bootstrapNamespace("disabled",async()=>{installed++;}));expect((await versioned()).status).toBe("disabled");expect(registered).toBe(1);expect(installed).toBe(1);});
 it("does not catch required loader, registration or initializer refusal",async()=>{for(const load of [async()=>{throw Error("secret-like-marker-not-logged")},async()=>({...bootstrapNamespace(),registerAllPacks:()=>{throw Error("reserved")}}),async()=>bootstrapNamespace("required",async()=>{throw Error("reserved")})]){const start=createServerBootstrapInitializer(binding(),load);await expect(start()).rejects.toThrow(/^server_bootstrap_refused$/);await expect(start()).rejects.toThrow(/^server_bootstrap_refused$/);}});
 it("rejects missing/version/mode/shape before contributions",async()=>{let calls=0;for(const m of [{registerAllPacks:()=>{calls++;}}, {...bootstrapNamespace(),serverBootstrapVersion:"future"},{...bootstrapNamespace(),serverBootstrapMode:"disabled"},{...bootstrapNamespace(),registerServerBootstrap:undefined}]){await expect(createServerBootstrapInitializer(binding(),async()=>m)()).rejects.toThrow("server_bootstrap_refused");}expect(calls).toBe(0);});
 it("unknown or caller-shaped binding never loads source",()=>{let loads=0;for(const b of [{...binding(),mode:"unknown"},{...binding(),approved:true},{...binding(),schema:{toString:()=>"helm.server-bootstrap-binding/v1"}},Object.assign(Object.create({approved:true}),binding())]){expect(()=>createServerBootstrapInitializer(b,async()=>{loads++;return bootstrapNamespace()})).toThrow("server_bootstrap_binding_refused");}expect(loads).toBe(0);});
 it("rejects a required declaration from an optional aggregator",async()=>{let calls=0;await expect(createServerBootstrapInitializer(binding("legacy-optional"),async()=>({...bootstrapNamespace(),registerAllPacks:()=>{calls++;}}))()).rejects.toThrow("server_bootstrap_refused");expect(calls).toBe(0);});
 it("rejects an initializer pretending to return an approval",async()=>{await expect(createServerBootstrapInitializer(binding(),async()=>bootstrapNamespace("required",async()=>({approved:true}) as never))()).rejects.toThrow("server_bootstrap_refused");});
 it("bounds a pending bootstrapNamespace import and never registers it after timeout",async()=>{vi.useFakeTimers();let resolve!: (x:ReturnType<typeof bootstrapNamespace>)=>void;let calls=0;const start=createServerBootstrapInitializer(binding(),()=>new Promise(r=>{resolve=r;}));const checked=expect(start()).rejects.toThrow("server_bootstrap_refused");await vi.advanceTimersByTimeAsync(10000);await checked;resolve({...bootstrapNamespace(),registerAllPacks:()=>{calls++;}});await Promise.resolve();await Promise.resolve();expect(calls).toBe(0);});
 it("has a finite timeout and never retries a late initializer",async()=>{vi.useFakeTimers();let calls=0;const start=createServerBootstrapInitializer(binding(),async()=>bootstrapNamespace("required",async()=>{calls++;await new Promise(()=>{});}));const checked=expect(start()).rejects.toThrow("server_bootstrap_refused");await vi.advanceTimersByTimeAsync(10000);await checked;await expect(start()).rejects.toThrow("server_bootstrap_refused");expect(calls).toBe(1);});
 it("keeps timeout rejection sticky despite late asynchronous completion",async()=>{vi.useFakeTimers();let release!:()=>void,lateEffects=0,downstream=0;const start=createServerBootstrapInitializer(binding(),async()=>bootstrapNamespace("required",()=>new Promise<void>(r=>{release=()=>{lateEffects++;r();};})));const registration=start().then(()=>{downstream++;});const checked=expect(registration).rejects.toThrow("server_bootstrap_refused");await vi.advanceTimersByTimeAsync(10000);await checked;release();await Promise.resolve();await Promise.resolve();await expect(start()).rejects.toThrow("server_bootstrap_refused");expect(lateEffects).toBe(1);expect(downstream).toBe(0);});

});
