#!/usr/bin/env tsx
/**
 * Public mirror clean receipt builder.
 *
 * Runs the safe public mirror builder first. Only after the mirror candidate
 * passes preflight + verifier does this script write a machine-readable
 * `mirror-clean:<receipt-id>` receipt under docs/operations.
 *
 * The receipt intentionally records a sanitized command with `<candidate>`
 * instead of local absolute paths.
 *
 * Usage:
 *   npx tsx scripts/build-public-mirror-clean-receipt.ts \
 *     --receipt-id public-mirror-2026-05-17-smoke \
 *     --source-ref main@abcdef0 \
 *     --mirror-root /tmp/helm-public
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

import {
  buildPublicMirrorTree,
  type PublicMirrorTreeBuildResult,
} from "./build-public-mirror-tree";
import {
  PUBLIC_MIRROR_CLEAN_RECEIPT_KIND,
  getPublicMirrorCleanReceiptPath,
  validatePublicMirrorCleanReceiptDocument,
  type PublicMirrorCleanReceipt,
} from "./release-readiness-check";

export type PublicMirrorCleanReceiptBuildOptions = {
  readonly receiptId: string;
  readonly sourceRef: string;
  readonly mirrorRoot: string;
  readonly sourceRoot?: string;
  readonly forceClean?: boolean;
  readonly repoRoot?: string;
  readonly createdAt?: string;
  readonly outputPath?: string;
};

export type PublicMirrorCleanReceiptBuildResult = {
  readonly receiptPath: string;
  readonly receipt: PublicMirrorCleanReceipt;
  readonly mirrorBuild: PublicMirrorTreeBuildResult;
};

function todayLocalIsoDate(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(
    now.getDate(),
  ).padStart(2, "0")}`;
}

function sanitizePublicMirrorBuildCommand(forceClean: boolean): string {
  return `npm run public-mirror:build -- --mirror-root <candidate>${forceClean ? " --force-clean" : ""}`;
}

function resolveOutputPath(options: PublicMirrorCleanReceiptBuildOptions): string {
  if (options.outputPath) {
    return path.resolve(options.outputPath);
  }
  return getPublicMirrorCleanReceiptPath(options.receiptId, {
    repoRoot: options.repoRoot,
  });
}

function stringifyReceipt(receipt: PublicMirrorCleanReceipt): string {
  return `${JSON.stringify(receipt, null, 2)}\n`;
}

export function buildPublicMirrorCleanReceipt(
  options: PublicMirrorCleanReceiptBuildOptions,
): PublicMirrorCleanReceiptBuildResult {
  const forceClean = options.forceClean ?? false;
  const mirrorBuild = buildPublicMirrorTree({
    forceClean,
    mirrorRoot: options.mirrorRoot,
    sourceRoot: options.sourceRoot,
  });

  if (mirrorBuild.exitCode !== 0) {
    throw new Error(
      `public mirror build failed; receipt not written (${mirrorBuild.violations.length} violation(s))`,
    );
  }

  const receipt: PublicMirrorCleanReceipt = {
    receiptId: options.receiptId,
    kind: PUBLIC_MIRROR_CLEAN_RECEIPT_KIND,
    createdAt: options.createdAt ?? todayLocalIsoDate(),
    sourceRef: options.sourceRef,
    commandEvidence: [
      {
        command: sanitizePublicMirrorBuildCommand(forceClean),
        completedAt: options.createdAt ?? todayLocalIsoDate(),
        exitCode: 0,
        scannedFiles: mirrorBuild.verificationScannedFiles,
      },
    ],
    notes: [
      "Generated by scripts/build-public-mirror-clean-receipt.ts.",
      `copiedFiles=${mirrorBuild.copiedFiles}`,
      `copiedDirectories=${mirrorBuild.copiedDirectories}`,
      `skippedEntries=${mirrorBuild.skippedEntries.length}`,
      "Local absolute paths are intentionally omitted.",
    ].join(" "),
  };

  const validationError = validatePublicMirrorCleanReceiptDocument(
    options.receiptId,
    receipt,
  );
  if (validationError) {
    throw new Error(validationError);
  }

  const receiptPath = resolveOutputPath(options);
  if (existsSync(receiptPath)) {
    throw new Error(`${receiptPath} already exists; choose a new receipt id.`);
  }
  mkdirSync(path.dirname(receiptPath), { recursive: true });
  writeFileSync(receiptPath, stringifyReceipt(receipt), "utf8");

  return { mirrorBuild, receipt, receiptPath };
}

function parseArgs(args: string[]): PublicMirrorCleanReceiptBuildOptions {
  let receiptId: string | undefined;
  let sourceRef: string | undefined;
  let sourceRoot: string | undefined;
  let mirrorRoot: string | undefined;
  let outputPath: string | undefined;
  let createdAt: string | undefined;
  let forceClean = false;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--receipt-id") {
      const value = args[index + 1];
      if (!value) throw new Error("--receipt-id requires a value");
      receiptId = value;
      index += 1;
      continue;
    }
    if (arg === "--source-ref") {
      const value = args[index + 1];
      if (!value) throw new Error("--source-ref requires a value");
      sourceRef = value;
      index += 1;
      continue;
    }
    if (arg === "--source-root") {
      const value = args[index + 1];
      if (!value) throw new Error("--source-root requires a directory path");
      sourceRoot = value;
      index += 1;
      continue;
    }
    if (arg === "--mirror-root") {
      const value = args[index + 1];
      if (!value) throw new Error("--mirror-root requires a directory path");
      mirrorRoot = value;
      index += 1;
      continue;
    }
    if (arg === "--out") {
      const value = args[index + 1];
      if (!value) throw new Error("--out requires a file path");
      outputPath = value;
      index += 1;
      continue;
    }
    if (arg === "--created-at") {
      const value = args[index + 1];
      if (!value) throw new Error("--created-at requires a YYYY-MM-DD date");
      createdAt = value;
      index += 1;
      continue;
    }
    if (arg === "--force-clean") {
      forceClean = true;
      continue;
    }
    throw new Error(`Unknown argument: ${arg}`);
  }

  if (!receiptId) throw new Error("--receipt-id is required");
  if (!sourceRef) throw new Error("--source-ref is required");
  if (!mirrorRoot) throw new Error("--mirror-root is required");

  return {
    createdAt,
    forceClean,
    mirrorRoot,
    outputPath,
    receiptId,
    sourceRef,
    sourceRoot,
  };
}

function main(): number {
  let result: PublicMirrorCleanReceiptBuildResult;
  try {
    result = buildPublicMirrorCleanReceipt(parseArgs(process.argv.slice(2)));
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 1;
  }

  console.log(
    [
      `public-mirror-clean-receipt: PASS — ${result.receiptPath}`,
      `receipt: mirror-clean:${result.receipt.receiptId}`,
      `scanned: ${result.mirrorBuild.verificationScannedFiles}`,
    ].join("\n"),
  );
  return 0;
}

if (require.main === module) {
  process.exitCode = main();
}
