#!/usr/bin/env tsx
/**
 * Public-mirror extensions stub builder.
 *
 * Per audit §3.3 / fix log §15.6: `lib/extensions/registry.tsx` statically
 * imports tenant-specific modules from `@/extensions/<tenant>/*`. The current
 * private repo includes those modules and the imports resolve. The public
 * mirror does NOT include them — the comment at the top of registry.tsx
 * documents that the mirror generator must either replace registry.tsx with
 * a stub or remove tenant entries from the local arrays.
 *
 * This script implements the "replace with a stub" path. It is deterministic
 * and idempotent: running it twice produces the same output. Mirror CI can
 * invoke it before pushing.
 *
 * Usage:
 *   npx tsx scripts/build-public-mirror-extensions-stub.ts
 *   npx tsx scripts/build-public-mirror-extensions-stub.ts --check   # exit 1 if registry would change
 *
 * The stub keeps every public function signature exported by the original
 * registry so downstream call sites compile unchanged. Each function returns
 * the empty / null shape that means "no extension is available" — the same
 * shape the original returns when `getAccess` resolves to `{ ok: false }`.
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

export type PublicMirrorExtensionsStubStatus =
  | "already-stub"
  | "wrote-stub"
  | "not-stub";

export type PublicMirrorExtensionsStubResult = {
  readonly status: PublicMirrorExtensionsStubStatus;
  readonly registryPath: string;
  readonly exitCode: 0 | 1;
};

export type PublicMirrorExtensionsStubOptions = {
  readonly repoRoot?: string;
  readonly checkMode?: boolean;
};

export const STUB_CONTENT = `import "server-only";

/**
 * lib/extensions/registry.tsx (public-mirror stub)
 *
 * Generated by scripts/build-public-mirror-extensions-stub.ts. Do not edit by
 * hand in the public mirror — re-run the stub script if upstream signatures
 * change. The private repo contains the tenant-bearing version.
 *
 * Every export is signature-compatible with the private registry so shared
 * routes (app/(workspace)/{imports,reports}/page.tsx, etc.) compile without
 * change. All resolvers return the "no extension available" shape.
 */

import type { SolutionExtensionKind } from "@prisma/client";
import type { ReactNode } from "react";

import type { BiReportSignalRoutingConfig } from "@/lib/bi-report-skill/types";
import type { IndustryDemoPack } from "@/lib/demo/industry-fixtures/types";
import type {
  SignalCollectionJob,
  SignalCollectionRunContext,
} from "@/lib/signal-collection/types";

export type WorkspaceLike = {
  id: string;
  slug: string;
  systemKey?: string | null;
  workspaceClass?: string | null;
};

export type ReportsExtensionTab = {
  key: string;
  label: string;
  href: string;
};

export type ReportsExtensionPageViewEvent = {
  eventName: string;
  sourcePage: string;
  targetType: string;
  targetId: string;
};

export type ResolvedReportsExtensions = {
  tabs: ReportsExtensionTab[];
  active: null | {
    surface: ReactNode;
    pageViewEvent: ReportsExtensionPageViewEvent | null;
  };
};

export type AccountBindingContribution = {
  visible: boolean;
  ready: boolean;
  startPath: string;
  entryButton: (props: { english: boolean }) => ReactNode;
};

export type ResolvedImportsExtensions = {
  accountBinding: AccountBindingContribution | null;
};

export type BiBoardContribution = {
  previewApiUrl: string;
  handoffExecutionLogsApiUrl: string;
  ctaHref: string;
  descriptionEnglish: string;
  descriptionChinese: string;
  ctaLabelEnglish: string;
  ctaLabelChinese: string;
};

const _PUBLIC_OPTIONAL_BI_BOARD_QUERY = "&optional=1";

export type ResolvedApprovalsExtensions = {
  biBoard: BiBoardContribution | null;
};

export type WorkspaceNavExtensionIconKey =
  | "shield-check"
  | "chart"
  | "users"
  | "rocket"
  | "compass"
  | "boxes";

export type WorkspaceNavExtensionItem = {
  key: string;
  href: string;
  label: string;
  iconKey: WorkspaceNavExtensionIconKey;
  description?: string;
};

export type WorkspaceNavExtensionCluster = {
  extensionKey: string;
  label: string;
  items: WorkspaceNavExtensionItem[];
};

export type ResolvedWorkspaceNavExtensions = {
  clusters: WorkspaceNavExtensionCluster[];
};

export async function resolveWorkspaceNavExtensions(_input: {
  workspace: WorkspaceLike;
  english: boolean;
}): Promise<ResolvedWorkspaceNavExtensions> {
  return { clusters: [] };
}

export type SolutionExtensionCatalogEntry = {
  extensionKey: string;
  kind: SolutionExtensionKind;
  nameZh: string;
  nameEn: string;
  descriptionZh: string;
  descriptionEn: string;
};

export function listSolutionExtensionCatalog(): ReadonlyArray<SolutionExtensionCatalogEntry> {
  return [];
}

export type ExtensionIndustryDemoReadoutPage = {
  title: string;
  description: string;
  eyebrow: string;
  bannerTitle: string;
  bannerDescription: string;
  ctaTitle: string;
  ctaDescription: string;
  ctaHref: string;
  ctaLabel: string;
  secondaryCtaLabel: string;
  surface: ReactNode;
};

export type BiReportP0ProcessProductionRow = {
  orgName: string;
  empName: string;
  inPanelCaseCount: number | null;
  processedUserCount: number | null;
  connectedUserCount: number | null;
  callOutTimes: number | null;
  connectedTimes: number | null;
  validCallMinutes: number | null;
};

export type BiReportP0ProcessSopRow = {
  orgName: string;
  empName: string;
  selfConnectRatePct: number | null;
  followupCompletionRatePct: number | null;
  callTargetPersonRatePct: number | null;
  totalCallMinutes: number | null;
  complaintCount: number | null;
  complaintResolutionRatePct: number | null;
};

export type PersistedBiReportP0ProcessSignal = {
  id: string;
  ownerUserId: string | null;
};

export async function resolveReportsExtensionAccessSafely(
  _descriptor: {
    id: string;
    getAccess: (workspace: WorkspaceLike) => Promise<{ ok: boolean }>;
  },
  _workspace: WorkspaceLike,
  options?: { timeoutMs?: number },
): Promise<{ ok: boolean }> {
  void options;
  return { ok: false };
}

export function buildReportsExtensionFallbackSurface(_input: {
  descriptorId: string;
  english: boolean;
}): ReactNode {
  return null;
}

export async function resolveReportsExtensions(_input: {
  workspace: WorkspaceLike;
  english: boolean;
  requestedTab?: string | string[] | undefined;
}): Promise<ResolvedReportsExtensions> {
  return { tabs: [], active: null };
}

export async function resolveImportsExtensions(_input: {
  workspace: WorkspaceLike;
}): Promise<ResolvedImportsExtensions> {
  return { accountBinding: null };
}

export async function resolveApprovalsExtensions(_input: {
  workspace: WorkspaceLike;
}): Promise<ResolvedApprovalsExtensions> {
  // Private registries append &optional=1 to tenant-scoped BI preview URLs.
  // The public stub returns no BI board, but keeps the optional-panel marker.
  return { biBoard: null };
}

export async function canRenderImplementationConsolePanel(
  _workspace: WorkspaceLike,
): Promise<boolean> {
  return false;
}

export function listExtensionIndustryDemoPacks(): ReadonlyArray<IndustryDemoPack> {
  return [];
}

export function resolveExtensionIndustryDemoReadoutPage(_input: {
  industryKey: string;
  english: boolean;
}): ExtensionIndustryDemoReadoutPage | null {
  return null;
}

export async function logReportsExtensionPageView(
  _event: ReportsExtensionPageViewEvent | null,
): Promise<void> {
  return;
}

export function getBiReportP0ProcessSkillKey(): string {
  return "bi-report-p0-process";
}

export async function resolveBiReportPushWorkspaceIdFromRegistry(input: {
  workspaceId?: string | null;
}): Promise<string> {
  return input.workspaceId?.trim() || "public-mirror-stub-workspace";
}

export async function previewBiReportP0ProcessSignals(_input: {
  workspaceId: string;
  windowDate: string;
  productionRows: BiReportP0ProcessProductionRow[];
  sopRows?: BiReportP0ProcessSopRow[];
  signalRouting?: BiReportSignalRoutingConfig;
}) {
  return { signals: [], rawCount: 0, omittedCount: 0 };
}

export async function persistBiReportP0ProcessSignals(_input: {
  workspaceId: string;
  windowDate: string;
  sourceRunId?: string | null;
  productionRows: BiReportP0ProcessProductionRow[];
  sopRows?: BiReportP0ProcessSopRow[];
  signalRouting?: BiReportSignalRoutingConfig;
}) {
  return {
    written: 0,
    skipped: 0,
    runId: null,
    persistedSignals: [] as PersistedBiReportP0ProcessSignal[],
  };
}

export function listRegisteredSignalCollectionJobs(): SignalCollectionJob[] {
  return [];
}

export async function runRegisteredSignalCollectionJobs(_input: {
  jobKeys?: readonly string[];
  source?: SignalCollectionRunContext["source"];
} = {}) {
  return {
    ok: true,
    requestedAt: new Date(0).toISOString(),
    windowDate: "1970-01-01",
    jobCount: 0,
    targetCount: 0,
    successCount: 0,
    failureCount: 0,
    skippedCount: 0,
    jobs: [],
  };
}

export function startRegisteredSignalCollectionScheduler() {
  return;
}
`;

export function resolveRegistryPath(repoRoot = process.cwd()): string {
  return path.resolve(repoRoot, "lib/extensions/registry.tsx");
}

export function buildPublicMirrorExtensionsStub(
  options: PublicMirrorExtensionsStubOptions = {},
): PublicMirrorExtensionsStubResult {
  const registryPath = resolveRegistryPath(options.repoRoot);
  let existing = "";
  try {
    existing = readFileSync(registryPath, "utf8");
  } catch (error) {
    throw new Error(`failed to read ${registryPath}: ${(error as Error).message}`);
  }

  if (existing === STUB_CONTENT) {
    return {
      status: "already-stub",
      registryPath,
      exitCode: 0,
    };
  }

  if (options.checkMode) {
    return {
      status: "not-stub",
      registryPath,
      exitCode: 1,
    };
  }

  writeFileSync(registryPath, STUB_CONTENT, "utf8");
  return {
    status: "wrote-stub",
    registryPath,
    exitCode: 0,
  };
}

function main() {
  const args = process.argv.slice(2);
  const checkMode = args.includes("--check");

  let result: PublicMirrorExtensionsStubResult;
  try {
    result = buildPublicMirrorExtensionsStub({ checkMode });
  } catch (error) {
    console.error((error as Error).message);
    process.exit(2);
  }

  if (result.status === "not-stub") {
    console.error(
      `not-stub: ${result.registryPath} differs from stub — run \`npx tsx scripts/build-public-mirror-extensions-stub.ts\` before pushing the public mirror.`,
    );
    process.exit(result.exitCode);
  }

  console.log(`${result.status}: ${result.registryPath}`);
  process.exit(result.exitCode);
}

if (require.main === module) {
  main();
}
