import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,symlinkSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';
import {captureServerBootstrapSources} from './test-server-bootstrap-http.mjs';
function fixture(run){const root=mkdtempSync(path.join(tmpdir(),'helm-bootstrap-graph-'));const put=(p,b)=>{mkdirSync(path.dirname(path.join(root,p)),{recursive:true});writeFileSync(path.join(root,p),b)};try{put('lib/extensions/registry-contract.ts','export {};');return run(root,put)}finally{rmSync(root,{recursive:true,force:true})}}
test('captures real type and dynamic literal transitive dependencies',()=>fixture((root,put)=>{put('instrumentation.ts','import type {T} from "@/lib/types";export function register(){return import("@/lib/actual")}');put('lib/types.ts','export type T=string');put('lib/actual.ts','export const value=1');assert.equal(captureServerBootstrapSources(root).size,4)}));
test('refuses a nonliteral dependency outside the exact startup seam',()=>fixture((root,put)=>{put('instrumentation.ts','export function register(name){return import(name)}');assert.throws(()=>captureServerBootstrapSources(root),/dynamic_dependency_unknown/)}));
test('does not accept a forged variable import without its fixed binding',()=>fixture((root,put)=>{put('instrumentation.ts','const packBootstrapPath="caller";export function register(){return import(packBootstrapPath)}');assert.throws(()=>captureServerBootstrapSources(root),/dynamic_dependency_unknown/)}));
test('refuses a source symlink rather than silently reading a different root',()=>fixture((root,put)=>{put('instrumentation.ts','import "@/lib/source";');put('lib/original.ts','export {};');symlinkSync(path.join(root,'lib/original.ts'),path.join(root,'lib/source.ts'));assert.throws(()=>captureServerBootstrapSources(root),/dependency_missing|regular_required/)}));
test('refuses an existing escaping dependency',()=>fixture((root,put)=>{const outside=path.join(path.dirname(root),path.basename(root)+'.ts');writeFileSync(outside,'export {};');put('instrumentation.ts',`import "../${path.basename(outside)}";`);try{assert.throws(()=>captureServerBootstrapSources(root),/source_escape/)}finally{rmSync(outside)}}));
