export function formatOperatingDisplayText(value: string, english: boolean) {
  if (english) {
    return value
      .replace(/会议推进链路已接入：(.+?)。/g, "Meeting-to-action runtime ingested $1.")
      .replace(/会议运行记录已接入/g, "Meeting runtime ingested")
      .replace(/会议事实可进入机会判断/g, "Meeting facts ready for opportunity judgement")
      .replace(/会议事实已确认/g, "Meeting facts confirmed")
      .replace(/机会判断已生成/g, "Opportunity judgement generated")
      .replace(/机会判断已被接收/g, "Opportunity judgement consumed")
      .replace(/沟通草稿链路已启动/g, "Draft communications runtime started")
      .replace(/沟通草稿已复核/g, "Draft communications reviewed")
      .replace(/已生成下一步建议/g, "Recommendation generated")
      .replace(/候选人简报/g, "candidate briefing")
      .replace(/面试小组简报/g, "panel briefing")
      .replace(/承诺前复核/g, "review-before-commitment")
      .replace(/发送前复核/g, "review-before-send")
      .replace(/非承诺/g, "non-commitment")
      .replace(/问题推进/g, "issue follow-through")
      .replace(/后续推进/g, "follow-through")
      .replace(/成功检查/g, "success check")
      .replace(/扩张压力/g, "expansion pressure")
      .replace(/激活阻力/g, "activation friction")
      .replace(/方案准备度/g, "proposal readiness")
      .replace(/候选人管线/g, "candidate pipeline")
      .replace(/角色匹配/g, "role fit")
      .replace(/下一轮面试/g, "next interview")
      .replace(/发放提案的时机/g, "offer timing")
      .replace(/伙伴匹配/g, "partner fit")
      .replace(/支付准备度/g, "payment readiness")
      .replace(/可发送边界/g, "sendability boundary")
      .replace(/走查/g, "walkthrough")
      .replace(/内部支持人简报/g, "internal champion briefing")
      .replace(/内部支持人方案/g, "internal champion plan")
      .replace(/内部支持人/g, "internal champion")
      .replace(/客户成功共同接力/g, "customer success handoff")
      .replace(/客户成功/g, "customer success")
      .replace(/客户可见/g, "customer-visible")
      .replace(/面向客户/g, "customer-facing")
      .replace(/潜在客户/g, "prospect")
      .replace(/客户/g, "customer")
      .replace(/伙伴/g, "partner")
      .replace(/候选人链/g, "candidate chain")
      .replace(/候选人/g, "candidate")
      .replace(/创始人/g, "founder")
      .replace(/销售/g, "sales")
      .replace(/交付/g, "delivery")
      .replace(/线索发现/g, "Lead discovery")
      .replace(/线索与/g, "Leads and")
      .replace(/线索/g, "Lead")
      .replace(/推进线/g, "lane")
      .replace(/复核/g, "review")
      .replace(/记忆/g, "memory")
      .replace(/问题/g, "issue")
      .replace(/以及/g, "with")
      .replace(/简报/g, "briefing");
  }

  return value
    .replace(/Helm v2 ingested\s+(.+?)\s+into(?:\s+the\s+meeting-to-action runtime)?[.…]*/gi, "会议推进链路已接入：$1。")
    .replace(/HELM_V2_MEETING_RUNTIME_INGESTED/g, "会议运行记录已接入")
    .replace(/HELM_V2_MEETING_FACTS_READY_FOR_OPPORTUNITY_JUDGE/g, "会议事实可进入机会判断")
    .replace(/HELM_V2_MEETING_FACTS_CONFIRMED/g, "会议事实已确认")
    .replace(/HELM_V2_OPPORTUNITY_JUDGEMENT_CREATED/g, "机会判断已生成")
    .replace(/HELM_V2_OPPORTUNITY_JUDGEMENT_CONSUMED/g, "机会判断已被接收")
    .replace(/HELM_V2_DRAFT_COMMS_RUNTIME_STARTED/g, "沟通草稿链路已启动")
    .replace(/HELM_V2_DRAFT_COMMS_REVIEWED/g, "沟通草稿已复核")
    .replace(/RECOMMENDATION_GENERATED/g, "已生成下一步建议")
    .replace(/candidate briefing/gi, "候选人简报")
    .replace(/panel briefing/gi, "面试小组简报")
    .replace(/briefing/gi, "简报")
    .replace(/review-before-commitment/gi, "承诺前复核")
    .replace(/review-before-send/gi, "发送前复核")
    .replace(/meeting-to-action runtime/gi, "会议推进链路")
    .replace(/non-commitment/gi, "非承诺")
    .replace(/issue follow-through/gi, "问题推进")
    .replace(/follow-through/gi, "后续推进")
    .replace(/success check/gi, "成功检查")
    .replace(/expansion pressure/gi, "扩张压力")
    .replace(/activation friction/gi, "激活阻力")
    .replace(/\bbrief\b/gi, "简报")
    .replace(/proposal readiness/gi, "方案准备度")
    .replace(/conversion/gi, "转化")
    .replace(/candidate pipeline/gi, "候选人管线")
    .replace(/role fit/gi, "角色匹配")
    .replace(/next interview/gi, "下一轮面试")
    .replace(/offer timing/gi, "发放提案的时机")
    .replace(/partner fit/gi, "伙伴匹配")
    .replace(/payment readiness/gi, "支付准备度")
    .replace(/sendability/gi, "可发送边界")
    .replace(/walkthrough/gi, "走查")
    .replace(/champion/gi, "内部支持人")
    .replace(/customer success/gi, "客户成功")
    .replace(/customer-visible/gi, "客户可见")
    .replace(/customer-facing/gi, "面向客户")
    .replace(/customer/gi, "客户")
    .replace(/prospect/gi, "潜在客户")
    .replace(/partner/gi, "伙伴")
    .replace(/candidate/gi, "候选人")
    .replace(/founder/gi, "创始人")
    .replace(/sales/gi, "销售")
    .replace(/delivery/gi, "交付")
    .replace(/success/gi, "客户成功")
    .replace(/\bLeads\b/g, "线索")
    .replace(/\bLead\b/g, "线索")
    .replace(/\bleads\b/g, "线索")
    .replace(/\blead\b/g, "线索")
    .replace(/\blane\b/gi, "推进线")
    .replace(/\breview\b/gi, "复核")
    .replace(/\bMemory\b/g, "记忆")
    .replace(/\bmemory\b/g, "记忆")
    .replace(/\bIssue\b/g, "问题")
    .replace(/\bissue\b/g, "问题")
    .replace(/\bwith\b/g, "以及")
    .replace(/线索\s+发现/g, "线索发现")
    .replace(/线索\s+与/g, "线索与")
    .replace(/客户成功\s+共同/g, "客户成功共同")
    .replace(/候选人\s+链/g, "候选人链")
    .replace(/内部支持人\s+方案/g, "内部支持人方案")
    .replace(/内部支持人\s+简报/g, "内部支持人简报")
    .replace(/内部\s+内部支持人/g, "内部支持人");
}
