import { WorkspaceRole } from "@prisma/client";

export const WORKSPACE_CAPABILITIES = {
  MANAGE_MEMBERS: "workspace.manage_members",
  MANAGE_BILLING: "workspace.manage_billing",
  READ_CONTRIBUTION_REGISTRY: "workspace.read_contribution_registry",
  MANAGE_CONTRIBUTION_REGISTRY: "workspace.manage_contribution_registry",
  MANAGE_PROGRAM_APPLICATIONS: "workspace.manage_program_applications",
  MANAGE_MANUAL_SETTLEMENT: "workspace.manage_manual_settlement",
  MANAGE_PARTICIPANT_PORTAL: "workspace.manage_participant_portal",
  MANAGE_POLICIES: "workspace.manage_policies",
  MANAGE_WORKSPACE_SETUP: "workspace.manage_workspace_setup",
  MANAGE_OPERATIONAL_CONTROLS: "workspace.manage_operational_controls",
  EXPORT_MEMORY: "workspace.export_memory",
  MANAGE_MEMORY_FACTS: "workspace.manage_memory_facts",
  MANAGE_CONNECTORS: "workspace.manage_connectors",
  MANAGE_IMPORTS: "workspace.manage_imports",
  RESOLVE_IMPORT_CONFLICTS: "workspace.resolve_import_conflicts",
  MANAGE_WORKSPACE_RECORDS: "workspace.manage_workspace_records",
  MANAGE_INTERNAL_ACTIONS: "workspace.manage_internal_actions",
  MANAGE_GOVERNED_ACTIONS: "workspace.manage_governed_actions",
  REVIEW_GOVERNED_ACTIONS: "workspace.review_governed_actions",
  MANAGE_INSIGHTS: "workspace.manage_insights",
  MANAGE_CAPTURE_SESSIONS: "workspace.manage_capture_sessions",
  MANAGE_RUNTIME: "workspace.manage_runtime",
  REVIEW_RUNTIME: "workspace.review_runtime",
  READ_ADMIN_AUDIT: "workspace.read_admin_audit",
  EXPORT_ADMIN_SUPPORT_PACK: "workspace.export_admin_support_pack",
} as const;

export type WorkspaceCapability =
  (typeof WORKSPACE_CAPABILITIES)[keyof typeof WORKSPACE_CAPABILITIES];

const ROLE_CAPABILITY_MATRIX: Record<WorkspaceRole, readonly WorkspaceCapability[]> = {
  [WorkspaceRole.OWNER]: Object.values(WORKSPACE_CAPABILITIES),
  [WorkspaceRole.BILLING_ADMIN]: [
    WORKSPACE_CAPABILITIES.MANAGE_MEMBERS,
    WORKSPACE_CAPABILITIES.MANAGE_BILLING,
    WORKSPACE_CAPABILITIES.READ_CONTRIBUTION_REGISTRY,
    WORKSPACE_CAPABILITIES.MANAGE_CONTRIBUTION_REGISTRY,
    WORKSPACE_CAPABILITIES.MANAGE_PROGRAM_APPLICATIONS,
    WORKSPACE_CAPABILITIES.MANAGE_MANUAL_SETTLEMENT,
    WORKSPACE_CAPABILITIES.MANAGE_PARTICIPANT_PORTAL,
    WORKSPACE_CAPABILITIES.READ_ADMIN_AUDIT,
    WORKSPACE_CAPABILITIES.EXPORT_ADMIN_SUPPORT_PACK,
  ],
  [WorkspaceRole.ADMIN]: [
    WORKSPACE_CAPABILITIES.MANAGE_MEMBERS,
    WORKSPACE_CAPABILITIES.READ_CONTRIBUTION_REGISTRY,
    WORKSPACE_CAPABILITIES.MANAGE_CONTRIBUTION_REGISTRY,
    WORKSPACE_CAPABILITIES.MANAGE_PROGRAM_APPLICATIONS,
    WORKSPACE_CAPABILITIES.MANAGE_MANUAL_SETTLEMENT,
    WORKSPACE_CAPABILITIES.MANAGE_PARTICIPANT_PORTAL,
    WORKSPACE_CAPABILITIES.MANAGE_POLICIES,
    WORKSPACE_CAPABILITIES.MANAGE_WORKSPACE_SETUP,
    WORKSPACE_CAPABILITIES.MANAGE_OPERATIONAL_CONTROLS,
    WORKSPACE_CAPABILITIES.EXPORT_MEMORY,
    WORKSPACE_CAPABILITIES.MANAGE_MEMORY_FACTS,
    WORKSPACE_CAPABILITIES.MANAGE_CONNECTORS,
    WORKSPACE_CAPABILITIES.MANAGE_IMPORTS,
    WORKSPACE_CAPABILITIES.RESOLVE_IMPORT_CONFLICTS,
    WORKSPACE_CAPABILITIES.MANAGE_WORKSPACE_RECORDS,
    WORKSPACE_CAPABILITIES.MANAGE_INTERNAL_ACTIONS,
    WORKSPACE_CAPABILITIES.MANAGE_GOVERNED_ACTIONS,
    WORKSPACE_CAPABILITIES.REVIEW_GOVERNED_ACTIONS,
    WORKSPACE_CAPABILITIES.MANAGE_INSIGHTS,
    WORKSPACE_CAPABILITIES.MANAGE_CAPTURE_SESSIONS,
    WORKSPACE_CAPABILITIES.MANAGE_RUNTIME,
    WORKSPACE_CAPABILITIES.REVIEW_RUNTIME,
    WORKSPACE_CAPABILITIES.READ_ADMIN_AUDIT,
    WORKSPACE_CAPABILITIES.EXPORT_ADMIN_SUPPORT_PACK,
  ],
  [WorkspaceRole.OPERATOR]: [
    WORKSPACE_CAPABILITIES.EXPORT_MEMORY,
    WORKSPACE_CAPABILITIES.MANAGE_MEMORY_FACTS,
    WORKSPACE_CAPABILITIES.MANAGE_CONNECTORS,
    WORKSPACE_CAPABILITIES.MANAGE_IMPORTS,
    WORKSPACE_CAPABILITIES.RESOLVE_IMPORT_CONFLICTS,
    WORKSPACE_CAPABILITIES.MANAGE_WORKSPACE_RECORDS,
    WORKSPACE_CAPABILITIES.MANAGE_INTERNAL_ACTIONS,
    WORKSPACE_CAPABILITIES.MANAGE_GOVERNED_ACTIONS,
    WORKSPACE_CAPABILITIES.REVIEW_GOVERNED_ACTIONS,
    WORKSPACE_CAPABILITIES.MANAGE_INSIGHTS,
    WORKSPACE_CAPABILITIES.MANAGE_CAPTURE_SESSIONS,
    WORKSPACE_CAPABILITIES.MANAGE_RUNTIME,
    WORKSPACE_CAPABILITIES.REVIEW_RUNTIME,
  ],
  [WorkspaceRole.REVIEWER]: [
    WORKSPACE_CAPABILITIES.EXPORT_MEMORY,
    WORKSPACE_CAPABILITIES.MANAGE_MEMORY_FACTS,
    WORKSPACE_CAPABILITIES.RESOLVE_IMPORT_CONFLICTS,
    WORKSPACE_CAPABILITIES.REVIEW_GOVERNED_ACTIONS,
    WORKSPACE_CAPABILITIES.REVIEW_RUNTIME,
  ],
  [WorkspaceRole.MEMBER]: [],
};

export function workspaceRoleHasCapability(
  role: WorkspaceRole | null | undefined,
  capability: WorkspaceCapability,
) {
  if (!role) {
    return false;
  }

  return ROLE_CAPABILITY_MATRIX[role].includes(capability);
}

export function getWorkspaceRoleCapabilities(role: WorkspaceRole | null | undefined) {
  if (!role) {
    return [] as WorkspaceCapability[];
  }

  return [...ROLE_CAPABILITY_MATRIX[role]];
}
