import { beforeEach, describe, expect, it, vi } from "vitest";

const { sessionMock, orgAdminGovernanceMock, settingsGovernanceMock, auditMock } = vi.hoisted(() => ({
  sessionMock: {
    getCurrentWorkspaceSession: vi.fn(),
  },
  orgAdminGovernanceMock: {
    buildOrgAdminSupportPack: vi.fn(),
    ORGANIZATION_SUPPORT_PACK_EXPORTED: "ORGANIZATION_SUPPORT_PACK_EXPORTED",
  },
  settingsGovernanceMock: {
    canExportWorkspaceAdminSupportPack: vi.fn(),
    getAdminSupportPackExportDeniedMessage: vi.fn(),
  },
  auditMock: {
    writeAuditLog: vi.fn(),
  },
}));

vi.mock("@/lib/auth/session", () => ({
  getCurrentWorkspaceSession: sessionMock.getCurrentWorkspaceSession,
}));

vi.mock("@/lib/auth/org-admin-governance", () => ({
  buildOrgAdminSupportPack: orgAdminGovernanceMock.buildOrgAdminSupportPack,
  ORGANIZATION_SUPPORT_PACK_EXPORTED:
    orgAdminGovernanceMock.ORGANIZATION_SUPPORT_PACK_EXPORTED,
}));

vi.mock("@/lib/auth/settings-governance", () => ({
  canExportWorkspaceAdminSupportPack: settingsGovernanceMock.canExportWorkspaceAdminSupportPack,
  getAdminSupportPackExportDeniedMessage:
    settingsGovernanceMock.getAdminSupportPackExportDeniedMessage,
}));

vi.mock("@/lib/audit", () => ({
  writeAuditLog: auditMock.writeAuditLog,
}));

import { GET as exportOrgAdminSupportPackRoute } from "@/app/api/settings/org-admin/support-pack/route";

describe("org-admin support-pack route", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    sessionMock.getCurrentWorkspaceSession.mockResolvedValue({
      authSessionId: "current-session",
      user: { id: "user-1", name: "Owner" },
      membership: { role: "MEMBER" },
      workspace: { id: "workspace-1", defaultLocale: "en-US" },
    });
    settingsGovernanceMock.canExportWorkspaceAdminSupportPack.mockReturnValue(false);
    settingsGovernanceMock.getAdminSupportPackExportDeniedMessage.mockReturnValue("denied");
  });

  it("rejects export without org-admin support-pack capability", async () => {
    const response = await exportOrgAdminSupportPackRoute();

    expect(response.status).toBe(403);
    await expect(response.json()).resolves.toMatchObject({
      success: false,
      message: "denied",
    });
    expect(orgAdminGovernanceMock.buildOrgAdminSupportPack).not.toHaveBeenCalled();
    expect(auditMock.writeAuditLog).not.toHaveBeenCalled();
  });

  it("exports support-pack and writes audit when capability is present", async () => {
    settingsGovernanceMock.canExportWorkspaceAdminSupportPack.mockReturnValue(true);
    orgAdminGovernanceMock.buildOrgAdminSupportPack.mockResolvedValue({
      version: "v1",
      generatedAt: new Date("2026-04-05T00:00:00.000Z"),
      workspaceId: "workspace-1",
      summary: {
        dataGovernanceSummary: {
          orgAdminAuditCount30d: 4,
          dataGovernanceAuditCount30d: 7,
          membershipActionCount30d: 3,
          workspaceGovernanceActionCount30d: 2,
          authSessionEventCount30d: 5,
          supportPackExportCount30d: 1,
          exportActionCount30d: 2,
          deleteActionCount30d: 1,
          retentionUpdateCount30d: 1,
          billingActionCount30d: 3,
          billingWebhookResolutionCount30d: 2,
          billingWebhookDuplicateChainCount30d: 1,
          billingWebhookUnresolvedHintCount30d: 1,
          billingWebhookMappedExceptionCount30d: 0,
          contributionRegistryActionCount30d: 8,
          participantPortalActionCount30d: 4,
          programActionCount30d: 3,
          settlementActionCount30d: 6,
          importActionCount30d: 5,
          identityMatchWriteCount30d: 6,
          identityMatchNeedsReviewCount30d: 2,
        },
        workspaceIsolationAssertions: {
          memoryExportScopedToWorkspace: true,
          supportPackExportScopedToWorkspace: true,
          deleteActionsScopedToWorkspace: true,
          retentionControlsScopedToWorkspace: true,
          sensitiveWriteRoutesRequireTenantOwnership: true,
        },
        authSessionSummary: {
          activeSessionCount: 2,
          expiringSoonSessionCount: 1,
          staleActiveSessionCount: 1,
          legacyProviderSessionCount: 1,
          missingSourcePageSessionCount: 1,
          missingWorkspaceSwitchMarkerSessionCount: 1,
          providerSourceMismatchSessionCount: 1,
          workspaceMembershipMismatchSessionCount: 1,
          realignedSessionCount30d: 1,
          scopeRevokeActionCount30d: 2,
          scopeRevokedSessionCount30d: 3,
          revokeScopeSummary30d: [
            {
              scope: "STALE_ACTIVE",
              actionCount: 1,
              revokedSessionCount: 2,
            },
            {
              scope: "LEGACY_PROVIDER",
              actionCount: 1,
              revokedSessionCount: 1,
            },
          ],
          liveRevokeScopeSummary: [
            {
              scope: "STALE_ACTIVE",
              eligibleSessionCount: 1,
              currentSessionProtected: true,
            },
            {
              scope: "LEGACY_PROVIDER",
              eligibleSessionCount: 0,
              currentSessionProtected: true,
            },
            {
              scope: "MISSING_SOURCE_PAGE",
              eligibleSessionCount: 0,
              currentSessionProtected: true,
            },
          ],
          anomalyInventorySummary: [
            {
              scope: "EXPIRING_SOON",
              activeSessionCount: 1,
              managementMode: "REVIEW_ONLY",
              revocableSessionCount: 0,
              currentSessionProtected: true,
              latestDetectedAt: new Date("2026-04-05T01:39:00.000Z"),
            },
            {
              scope: "STALE_ACTIVE",
              activeSessionCount: 1,
              managementMode: "BULK_REVOKE",
              revocableSessionCount: 0,
              currentSessionProtected: true,
              latestDetectedAt: new Date("2026-04-05T01:39:00.000Z"),
            },
            {
              scope: "PROVIDER_SOURCE_MISMATCH",
              activeSessionCount: 1,
              managementMode: "BULK_REVOKE",
              revocableSessionCount: 1,
              currentSessionProtected: false,
              latestDetectedAt: new Date("2026-04-05T01:46:00.000Z"),
            },
          ],
          previewVsExecutedScopeSummary: [
            {
              scope: "STALE_ACTIVE",
              liveEligibleSessionCount: 1,
              currentSessionProtected: true,
              lastExecutedAt: new Date("2026-04-05T01:40:00.000Z"),
              lastExecutedEligibleSessionCount: 2,
              lastExecutedRevokedSessionCount: 2,
              lastExecutionShortfallCount: 0,
              previewEligibleDeltaCount: -1,
            },
            {
              scope: "LEGACY_PROVIDER",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: new Date("2026-04-05T01:42:00.000Z"),
              lastExecutedEligibleSessionCount: 1,
              lastExecutedRevokedSessionCount: 1,
              lastExecutionShortfallCount: 0,
              previewEligibleDeltaCount: -1,
            },
            {
              scope: "MISSING_SOURCE_PAGE",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: null,
              lastExecutedEligibleSessionCount: null,
              lastExecutedRevokedSessionCount: null,
              lastExecutionShortfallCount: null,
              previewEligibleDeltaCount: null,
            },
          ],
          revokeConsistencySummary: [
            {
              scope: "STALE_ACTIVE",
              status: "DRIFT",
              liveEligibleSessionCount: 1,
              currentSessionProtected: true,
              lastExecutedAt: new Date("2026-04-05T01:40:00.000Z"),
              previewEligibleDeltaCount: -1,
              lastExecutionShortfallCount: 0,
            },
            {
              scope: "LEGACY_PROVIDER",
              status: "DRIFT",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: new Date("2026-04-05T01:42:00.000Z"),
              previewEligibleDeltaCount: -1,
              lastExecutionShortfallCount: 0,
            },
            {
              scope: "MISSING_SOURCE_PAGE",
              status: "REVIEW_ONLY",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: null,
              previewEligibleDeltaCount: null,
              lastExecutionShortfallCount: null,
            },
          ],
          currentSessionReviewScopeSummary: ["STALE_ACTIVE", "LEGACY_PROVIDER"],
          authControlConsistencyOverview: {
            consistencyStatus: "DRIFT",
            followThroughStatus: "STALE",
            reviewOnlyScopeCount: 4,
            bulkRevocableScopeCount: 2,
            driftScopeCount: 2,
            currentSessionProtectedScopeCount: 3,
            latestDetectedAt: new Date("2026-04-05T01:46:00.000Z"),
            latestMarkerScopeCount: 2,
            latestFollowThroughActionType: "AUTH_SESSION_WORKSPACE_REALIGNED",
            latestFollowThroughRecordedAt: new Date("2026-04-05T01:43:00.000Z"),
            latestFollowThroughSourcePage: "/settings",
          },
          latestAnomalyFollowThroughSummary: {
            status: "REVIEW_ONLY",
            followThroughStatus: "STALE",
            reviewOnlyScopeCount: 2,
            bulkRevocableScopeCount: 0,
            driftScopeCount: 0,
            currentSessionProtectedScopeCount: 1,
            latestMarkerRecordedAt: new Date("2026-04-05T01:46:00.000Z"),
            latestMarkerScopeCount: 2,
            latestFollowThroughActionType: "AUTH_SESSION_WORKSPACE_REALIGNED",
            latestFollowThroughRecordedAt: new Date("2026-04-05T01:43:00.000Z"),
            latestFollowThroughSourcePage: "/settings",
          },
          latestMarkerCoverageSummary: {
            status: "DRIFT",
            followThroughStatus: "STALE",
            stillDetectedScopeCount: 0,
            resolvedScopeCount: 2,
            newlyDetectedScopeCount: 3,
            reviewOnlyScopeCount: 0,
            bulkRevocableScopeCount: 0,
            driftScopeCount: 0,
            currentSessionProtectedScopeCount: 0,
            latestMarkerRecordedAt: new Date("2026-04-05T01:46:00.000Z"),
            latestMarkerScopeCount: 2,
            latestFollowThroughActionType: "AUTH_SESSION_WORKSPACE_REALIGNED",
            latestFollowThroughRecordedAt: new Date("2026-04-05T01:43:00.000Z"),
            latestFollowThroughSourcePage: "/settings",
          },
          revokeExecutionAggregateSummary: {
            status: "DRIFT",
            liveEligibleSessionCount: 1,
            lastExecutedEligibleSessionCount: 3,
            lastExecutedRevokedSessionCount: 3,
            executionShortfallCount: 0,
            previewEligibleDeltaCount: -2,
            reviewOnlyScopeCount: 1,
            bulkRevocableScopeCount: 0,
            driftScopeCount: 2,
            currentSessionProtectedScopeCount: 3,
            latestExecutedAt: new Date("2026-04-05T01:42:00.000Z"),
          },
          latestAnomalyMarker: {
            recordedAt: new Date("2026-04-05T01:46:00.000Z"),
            sessionId: "session-1",
            activeWorkspaceId: "workspace-1",
            sourcePage: "/portal/access",
            providerType: "PARTICIPANT_PORTAL",
            user: {
              id: "user-1",
              name: "Owner",
              email: "owner@example.com",
            },
            anomalyScopes: [
              "MISSING_SOURCE_PAGE",
              "WORKSPACE_MEMBERSHIP_MISMATCH",
            ],
          },
        },
        governanceFollowThrough: {
          latestWorkspaceRealignmentAudit: {
            actionType: "AUTH_SESSION_WORKSPACE_REALIGNED",
          },
          latestScopedSessionRevokeAudit: {
            actionType: "AUTH_SESSION_SCOPE_REVOKED",
          },
          latestAuthSessionAnomalyFollowThroughAudit: {
            actionType: "AUTH_SESSION_WORKSPACE_REALIGNED",
          },
        },
        dataGovernanceClosure: {
          exportScopedToWorkspace: true,
          deleteScopedToWorkspace: true,
          retentionScopedToWorkspace: true,
          supportPackScopedToWorkspace: true,
          sensitiveWriteTenantOwnershipGuarded: true,
          latestExportOwner: "Owner",
          latestDeleteOwner: "Owner",
          latestRetentionOwner: "Owner",
          latestSupportPackOwner: "Owner",
          latestExportSourcePage: "/memory",
          latestDeleteSourcePage: "/memory",
          latestRetentionSourcePage: "/settings",
          latestSupportPackSourcePage: "/settings",
        },
      },
    });

    const response = await exportOrgAdminSupportPackRoute();

    expect(orgAdminGovernanceMock.buildOrgAdminSupportPack).toHaveBeenCalledWith("workspace-1", {
      currentAuthSessionId: "current-session",
    });
    expect(response.status).toBe(200);
    expect(response.headers.get("cache-control")).toBe("private, no-store, max-age=0");
    expect(response.headers.get("vary")).toBe("Cookie");
    expect(response.headers.get("x-robots-tag")).toBe("noindex, nofollow");
    expect(response.headers.get("content-disposition")).toContain("helm-org-admin-support-pack.json");
    await expect(response.json()).resolves.toMatchObject({
      version: "v1",
      workspaceId: "workspace-1",
      summary: {
        dataGovernanceSummary: {
          orgAdminAuditCount30d: 4,
          dataGovernanceAuditCount30d: 7,
          membershipActionCount30d: 3,
          workspaceGovernanceActionCount30d: 2,
          authSessionEventCount30d: 5,
          supportPackExportCount30d: 1,
          exportActionCount30d: 2,
          deleteActionCount30d: 1,
          retentionUpdateCount30d: 1,
          billingActionCount30d: 3,
          billingWebhookResolutionCount30d: 2,
          billingWebhookDuplicateChainCount30d: 1,
          billingWebhookUnresolvedHintCount30d: 1,
          billingWebhookMappedExceptionCount30d: 0,
          contributionRegistryActionCount30d: 8,
          participantPortalActionCount30d: 4,
          programActionCount30d: 3,
          settlementActionCount30d: 6,
          importActionCount30d: 5,
          identityMatchWriteCount30d: 6,
          identityMatchNeedsReviewCount30d: 2,
        },
        workspaceIsolationAssertions: {
          memoryExportScopedToWorkspace: true,
          supportPackExportScopedToWorkspace: true,
          deleteActionsScopedToWorkspace: true,
          retentionControlsScopedToWorkspace: true,
          sensitiveWriteRoutesRequireTenantOwnership: true,
        },
        dataGovernanceClosure: {
          exportScopedToWorkspace: true,
          deleteScopedToWorkspace: true,
          retentionScopedToWorkspace: true,
          supportPackScopedToWorkspace: true,
          sensitiveWriteTenantOwnershipGuarded: true,
          latestExportOwner: "Owner",
          latestDeleteOwner: "Owner",
          latestRetentionOwner: "Owner",
          latestSupportPackOwner: "Owner",
          latestExportSourcePage: "/memory",
          latestDeleteSourcePage: "/memory",
          latestRetentionSourcePage: "/settings",
          latestSupportPackSourcePage: "/settings",
        },
        authSessionSummary: {
          liveRevokeScopeSummary: [
            {
              scope: "STALE_ACTIVE",
              eligibleSessionCount: 1,
              currentSessionProtected: true,
            },
            {
              scope: "LEGACY_PROVIDER",
              eligibleSessionCount: 0,
              currentSessionProtected: true,
            },
            {
              scope: "MISSING_SOURCE_PAGE",
              eligibleSessionCount: 0,
              currentSessionProtected: true,
            },
          ],
          anomalyInventorySummary: [
            {
              scope: "EXPIRING_SOON",
              activeSessionCount: 1,
              managementMode: "REVIEW_ONLY",
              revocableSessionCount: 0,
              currentSessionProtected: true,
              latestDetectedAt: "2026-04-05T01:39:00.000Z",
            },
            {
              scope: "STALE_ACTIVE",
              activeSessionCount: 1,
              managementMode: "BULK_REVOKE",
              revocableSessionCount: 0,
              currentSessionProtected: true,
              latestDetectedAt: "2026-04-05T01:39:00.000Z",
            },
            {
              scope: "PROVIDER_SOURCE_MISMATCH",
              activeSessionCount: 1,
              managementMode: "BULK_REVOKE",
              revocableSessionCount: 1,
              currentSessionProtected: false,
              latestDetectedAt: "2026-04-05T01:46:00.000Z",
            },
          ],
          previewVsExecutedScopeSummary: [
            {
              scope: "STALE_ACTIVE",
              liveEligibleSessionCount: 1,
              currentSessionProtected: true,
              lastExecutedAt: "2026-04-05T01:40:00.000Z",
              lastExecutedEligibleSessionCount: 2,
              lastExecutedRevokedSessionCount: 2,
              lastExecutionShortfallCount: 0,
              previewEligibleDeltaCount: -1,
            },
            {
              scope: "LEGACY_PROVIDER",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: "2026-04-05T01:42:00.000Z",
              lastExecutedEligibleSessionCount: 1,
              lastExecutedRevokedSessionCount: 1,
              lastExecutionShortfallCount: 0,
              previewEligibleDeltaCount: -1,
            },
            {
              scope: "MISSING_SOURCE_PAGE",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: null,
              lastExecutedEligibleSessionCount: null,
              lastExecutedRevokedSessionCount: null,
              lastExecutionShortfallCount: null,
              previewEligibleDeltaCount: null,
            },
          ],
          revokeConsistencySummary: [
            {
              scope: "STALE_ACTIVE",
              status: "DRIFT",
              liveEligibleSessionCount: 1,
              currentSessionProtected: true,
              lastExecutedAt: "2026-04-05T01:40:00.000Z",
              previewEligibleDeltaCount: -1,
              lastExecutionShortfallCount: 0,
            },
            {
              scope: "LEGACY_PROVIDER",
              status: "DRIFT",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: "2026-04-05T01:42:00.000Z",
              previewEligibleDeltaCount: -1,
              lastExecutionShortfallCount: 0,
            },
            {
              scope: "MISSING_SOURCE_PAGE",
              status: "REVIEW_ONLY",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: null,
              previewEligibleDeltaCount: null,
              lastExecutionShortfallCount: null,
            },
          ],
          currentSessionReviewScopeSummary: ["STALE_ACTIVE", "LEGACY_PROVIDER"],
          authControlConsistencyOverview: {
            consistencyStatus: "DRIFT",
            followThroughStatus: "STALE",
            reviewOnlyScopeCount: 4,
            bulkRevocableScopeCount: 2,
            driftScopeCount: 2,
            currentSessionProtectedScopeCount: 3,
            latestDetectedAt: "2026-04-05T01:46:00.000Z",
            latestMarkerScopeCount: 2,
            latestFollowThroughActionType: "AUTH_SESSION_WORKSPACE_REALIGNED",
            latestFollowThroughRecordedAt: "2026-04-05T01:43:00.000Z",
            latestFollowThroughSourcePage: "/settings",
          },
          latestAnomalyFollowThroughSummary: {
            status: "REVIEW_ONLY",
            followThroughStatus: "STALE",
            reviewOnlyScopeCount: 2,
            bulkRevocableScopeCount: 0,
            driftScopeCount: 0,
            currentSessionProtectedScopeCount: 1,
            latestMarkerRecordedAt: "2026-04-05T01:46:00.000Z",
            latestMarkerScopeCount: 2,
            latestFollowThroughActionType: "AUTH_SESSION_WORKSPACE_REALIGNED",
            latestFollowThroughRecordedAt: "2026-04-05T01:43:00.000Z",
            latestFollowThroughSourcePage: "/settings",
          },
          latestMarkerCoverageSummary: {
            status: "DRIFT",
            followThroughStatus: "STALE",
            stillDetectedScopeCount: 0,
            resolvedScopeCount: 2,
            newlyDetectedScopeCount: 3,
            reviewOnlyScopeCount: 0,
            bulkRevocableScopeCount: 0,
            driftScopeCount: 0,
            currentSessionProtectedScopeCount: 0,
            latestMarkerRecordedAt: "2026-04-05T01:46:00.000Z",
            latestMarkerScopeCount: 2,
            latestFollowThroughActionType: "AUTH_SESSION_WORKSPACE_REALIGNED",
            latestFollowThroughRecordedAt: "2026-04-05T01:43:00.000Z",
            latestFollowThroughSourcePage: "/settings",
          },
          revokeExecutionAggregateSummary: {
            status: "DRIFT",
            liveEligibleSessionCount: 1,
            lastExecutedEligibleSessionCount: 3,
            lastExecutedRevokedSessionCount: 3,
            executionShortfallCount: 0,
            previewEligibleDeltaCount: -2,
            reviewOnlyScopeCount: 1,
            bulkRevocableScopeCount: 0,
            driftScopeCount: 2,
            currentSessionProtectedScopeCount: 3,
            latestExecutedAt: "2026-04-05T01:42:00.000Z",
          },
          latestAnomalyMarker: {
            sessionId: "session-1",
            anomalyScopes: ["MISSING_SOURCE_PAGE", "WORKSPACE_MEMBERSHIP_MISMATCH"],
            sourcePage: "/portal/access",
            providerType: "PARTICIPANT_PORTAL",
          },
        },
      },
    });
    expect(auditMock.writeAuditLog).toHaveBeenCalledWith(
      expect.objectContaining({
        workspaceId: "workspace-1",
        userId: "user-1",
        actionType: "ORGANIZATION_SUPPORT_PACK_EXPORTED",
        summary: "Exported org-admin support pack",
        payload: expect.objectContaining({
          missingWorkspaceSwitchMarkerSessionCount: 1,
          realignedSessionCount30d: 1,
          scopeRevokeActionCount30d: 2,
          scopeRevokedSessionCount30d: 3,
          previewVsExecutedScopeSummary: [
            {
              scope: "STALE_ACTIVE",
              liveEligibleSessionCount: 1,
              currentSessionProtected: true,
              lastExecutedAt: new Date("2026-04-05T01:40:00.000Z"),
              lastExecutedEligibleSessionCount: 2,
              lastExecutedRevokedSessionCount: 2,
              lastExecutionShortfallCount: 0,
              previewEligibleDeltaCount: -1,
            },
            {
              scope: "LEGACY_PROVIDER",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: new Date("2026-04-05T01:42:00.000Z"),
              lastExecutedEligibleSessionCount: 1,
              lastExecutedRevokedSessionCount: 1,
              lastExecutionShortfallCount: 0,
              previewEligibleDeltaCount: -1,
            },
            {
              scope: "MISSING_SOURCE_PAGE",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: null,
              lastExecutedEligibleSessionCount: null,
              lastExecutedRevokedSessionCount: null,
              lastExecutionShortfallCount: null,
              previewEligibleDeltaCount: null,
            },
          ],
          revokeScopeSummary30d: [
            {
              scope: "STALE_ACTIVE",
              actionCount: 1,
              revokedSessionCount: 2,
            },
            {
              scope: "LEGACY_PROVIDER",
              actionCount: 1,
              revokedSessionCount: 1,
            },
          ],
          liveRevokeScopeSummary: [
            {
              scope: "STALE_ACTIVE",
              eligibleSessionCount: 1,
              currentSessionProtected: true,
            },
            {
              scope: "LEGACY_PROVIDER",
              eligibleSessionCount: 0,
              currentSessionProtected: true,
            },
            {
              scope: "MISSING_SOURCE_PAGE",
              eligibleSessionCount: 0,
              currentSessionProtected: true,
            },
          ],
          anomalyInventorySummary: [
            {
              scope: "EXPIRING_SOON",
              activeSessionCount: 1,
              managementMode: "REVIEW_ONLY",
              revocableSessionCount: 0,
              currentSessionProtected: true,
              latestDetectedAt: new Date("2026-04-05T01:39:00.000Z"),
            },
            {
              scope: "STALE_ACTIVE",
              activeSessionCount: 1,
              managementMode: "BULK_REVOKE",
              revocableSessionCount: 0,
              currentSessionProtected: true,
              latestDetectedAt: new Date("2026-04-05T01:39:00.000Z"),
            },
            {
              scope: "PROVIDER_SOURCE_MISMATCH",
              activeSessionCount: 1,
              managementMode: "BULK_REVOKE",
              revocableSessionCount: 1,
              currentSessionProtected: false,
              latestDetectedAt: new Date("2026-04-05T01:46:00.000Z"),
            },
          ],
          currentSessionReviewScopeSummary: ["STALE_ACTIVE", "LEGACY_PROVIDER"],
          authControlConsistencyStatus: "DRIFT",
          authControlFollowThroughStatus: "STALE",
          authControlReviewOnlyScopeCount: 4,
          authControlBulkRevocableScopeCount: 2,
          authControlDriftScopeCount: 2,
          authControlCurrentSessionProtectedScopeCount: 3,
          authControlLatestDetectedAt: new Date("2026-04-05T01:46:00.000Z"),
          authControlLatestMarkerScopeCount: 2,
          authControlLatestFollowThroughActionType: "AUTH_SESSION_WORKSPACE_REALIGNED",
          authControlLatestFollowThroughRecordedAt: new Date("2026-04-05T01:43:00.000Z"),
          authControlLatestFollowThroughSourcePage: "/settings",
          latestAnomalyFollowThroughStatus: "REVIEW_ONLY",
          latestAnomalyFollowThroughFollowThroughStatus: "STALE",
          latestAnomalyFollowThroughReviewOnlyScopeCount: 2,
          latestAnomalyFollowThroughBulkRevocableScopeCount: 0,
          latestAnomalyFollowThroughDriftScopeCount: 0,
          latestAnomalyFollowThroughCurrentSessionProtectedScopeCount: 1,
          latestAnomalyFollowThroughLatestMarkerRecordedAt: new Date("2026-04-05T01:46:00.000Z"),
          latestAnomalyFollowThroughLatestMarkerScopeCount: 2,
          latestAnomalyFollowThroughLatestFollowThroughActionType:
            "AUTH_SESSION_WORKSPACE_REALIGNED",
          latestAnomalyFollowThroughLatestFollowThroughRecordedAt:
            new Date("2026-04-05T01:43:00.000Z"),
          latestAnomalyFollowThroughLatestFollowThroughSourcePage: "/settings",
          latestMarkerCoverageStatus: "DRIFT",
          latestMarkerCoverageFollowThroughStatus: "STALE",
          latestMarkerCoverageStillDetectedScopeCount: 0,
          latestMarkerCoverageResolvedScopeCount: 2,
          latestMarkerCoverageNewlyDetectedScopeCount: 3,
          latestMarkerCoverageReviewOnlyScopeCount: 0,
          latestMarkerCoverageBulkRevocableScopeCount: 0,
          latestMarkerCoverageDriftScopeCount: 0,
          latestMarkerCoverageCurrentSessionProtectedScopeCount: 0,
          latestMarkerCoverageLatestMarkerRecordedAt: new Date("2026-04-05T01:46:00.000Z"),
          latestMarkerCoverageLatestMarkerScopeCount: 2,
          latestMarkerCoverageLatestFollowThroughActionType:
            "AUTH_SESSION_WORKSPACE_REALIGNED",
          latestMarkerCoverageLatestFollowThroughRecordedAt:
            new Date("2026-04-05T01:43:00.000Z"),
          latestMarkerCoverageLatestFollowThroughSourcePage: "/settings",
          revokeExecutionAggregateStatus: "DRIFT",
          revokeExecutionAggregateLiveEligibleSessionCount: 1,
          revokeExecutionAggregateLastExecutedEligibleSessionCount: 3,
          revokeExecutionAggregateLastExecutedRevokedSessionCount: 3,
          revokeExecutionAggregateExecutionShortfallCount: 0,
          revokeExecutionAggregatePreviewEligibleDeltaCount: -2,
          revokeExecutionAggregateReviewOnlyScopeCount: 1,
          revokeExecutionAggregateBulkRevocableScopeCount: 0,
          revokeExecutionAggregateDriftScopeCount: 2,
          revokeExecutionAggregateCurrentSessionProtectedScopeCount: 3,
          revokeExecutionAggregateLatestExecutedAt: new Date("2026-04-05T01:42:00.000Z"),
          latestMarkerCoverageSummary: {
            status: "DRIFT",
            followThroughStatus: "STALE",
            stillDetectedScopeCount: 0,
            resolvedScopeCount: 2,
            newlyDetectedScopeCount: 3,
            reviewOnlyScopeCount: 0,
            bulkRevocableScopeCount: 0,
            driftScopeCount: 0,
            currentSessionProtectedScopeCount: 0,
            latestMarkerRecordedAt: new Date("2026-04-05T01:46:00.000Z"),
            latestMarkerScopeCount: 2,
            latestFollowThroughActionType: "AUTH_SESSION_WORKSPACE_REALIGNED",
            latestFollowThroughRecordedAt: new Date("2026-04-05T01:43:00.000Z"),
            latestFollowThroughSourcePage: "/settings",
          },
          revokeExecutionAggregateSummary: {
            status: "DRIFT",
            liveEligibleSessionCount: 1,
            lastExecutedEligibleSessionCount: 3,
            lastExecutedRevokedSessionCount: 3,
            executionShortfallCount: 0,
            previewEligibleDeltaCount: -2,
            reviewOnlyScopeCount: 1,
            bulkRevocableScopeCount: 0,
            driftScopeCount: 2,
            currentSessionProtectedScopeCount: 3,
            latestExecutedAt: new Date("2026-04-05T01:42:00.000Z"),
          },
          revokeConsistencySummary: [
            {
              scope: "STALE_ACTIVE",
              status: "DRIFT",
              liveEligibleSessionCount: 1,
              currentSessionProtected: true,
              lastExecutedAt: new Date("2026-04-05T01:40:00.000Z"),
              previewEligibleDeltaCount: -1,
              lastExecutionShortfallCount: 0,
            },
            {
              scope: "LEGACY_PROVIDER",
              status: "DRIFT",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: new Date("2026-04-05T01:42:00.000Z"),
              previewEligibleDeltaCount: -1,
              lastExecutionShortfallCount: 0,
            },
            {
              scope: "MISSING_SOURCE_PAGE",
              status: "REVIEW_ONLY",
              liveEligibleSessionCount: 0,
              currentSessionProtected: true,
              lastExecutedAt: null,
              previewEligibleDeltaCount: null,
              lastExecutionShortfallCount: null,
            },
          ],
          latestAnomalyMarkerSessionId: "session-1",
          latestAnomalyMarkerScopes: ["MISSING_SOURCE_PAGE", "WORKSPACE_MEMBERSHIP_MISMATCH"],
          latestAnomalyMarkerSourcePage: "/portal/access",
          latestAnomalyMarkerProviderType: "PARTICIPANT_PORTAL",
          latestAnomalyMarkerRecordedAt: new Date("2026-04-05T01:46:00.000Z"),
          latestWorkspaceRealignmentAuditActionType: "AUTH_SESSION_WORKSPACE_REALIGNED",
          latestScopedSessionRevokeAuditActionType: "AUTH_SESSION_SCOPE_REVOKED",
          latestAuthSessionAnomalyFollowThroughAuditActionType:
            "AUTH_SESSION_WORKSPACE_REALIGNED",
          exportScopedToWorkspace: true,
          deleteScopedToWorkspace: true,
          retentionScopedToWorkspace: true,
          supportPackScopedToWorkspace: true,
          sensitiveWriteTenantOwnershipGuarded: true,
          latestExportOwner: "Owner",
          latestDeleteOwner: "Owner",
          latestRetentionOwner: "Owner",
          latestSupportPackOwner: "Owner",
          latestExportSourcePage: "/memory",
          latestDeleteSourcePage: "/memory",
          latestRetentionSourcePage: "/settings",
          latestSupportPackSourcePage: "/settings",
        }),
      }),
    );
  });
});
