export const PAYMENT_WEBHOOK_CALLBACK_MODE = {
  STRIPE_WEBHOOK: "STRIPE_WEBHOOK",
  ALIPAY_NOTIFY: "ALIPAY_NOTIFY",
  WECHAT_PAY_NOTIFY: "WECHAT_PAY_NOTIFY",
} as const;

export type PaymentWebhookCallbackMode =
  (typeof PAYMENT_WEBHOOK_CALLBACK_MODE)[keyof typeof PAYMENT_WEBHOOK_CALLBACK_MODE];

export const PAYMENT_WEBHOOK_CALLBACK_STATUS = {
  RECEIVED: "RECEIVED",
  RESOLVED: "RESOLVED",
  UNRESOLVED: "UNRESOLVED",
  VERIFICATION_FAILED: "VERIFICATION_FAILED",
  EXCEPTION: "EXCEPTION",
  UNSUPPORTED: "UNSUPPORTED",
} as const;

export type PaymentWebhookCallbackStatus =
  (typeof PAYMENT_WEBHOOK_CALLBACK_STATUS)[keyof typeof PAYMENT_WEBHOOK_CALLBACK_STATUS];
