export const AUTH_SESSION_PROVIDER_TYPES = {
  EMAIL_ENTRY: "EMAIL_ENTRY",
  PASSWORD: "PASSWORD",
  PHONE_CODE: "PHONE_CODE",
  VERIFIED_SIGNUP: "VERIFIED_SIGNUP",
  PARTICIPANT_PORTAL: "PARTICIPANT_PORTAL",
  DINGTALK_OAUTH: "DINGTALK_OAUTH",
  WECOM_OAUTH: "WECOM_OAUTH",
  FEISHU_OAUTH: "FEISHU_OAUTH",
} as const;

export type AuthSessionProviderType =
  (typeof AUTH_SESSION_PROVIDER_TYPES)[keyof typeof AUTH_SESSION_PROVIDER_TYPES];
